### ISSUE TITLE
ffi.metatype uses the "align" attribute instead of "aligned"

### ISSUE THREAD

**Issue by 999pingGG** [LuaJIT/LuaJIT#1005]
Consider the following script:

```lua
ffi = require 'ffi'

construct = ffi.metatype('struct __attribute((aligned(4))) { int value; }', {
  __tostring = function(self)
    return 'Value is ' .. tostring(self.value);
  end,
})

t = construct()
t.value = 10

print(t, t.value)
``` 

No error is thrown but the metatable is not working, the result is something like `cdata<struct 97>: 0x01bd281fa610        10`. If you delete `__attribute((aligned(4)))` it works outputting `Value is 10     10`. I've been searching the docs and (to a limited extent) the source but I found no evidence telling me that this is intended behaviour.

Using the latest 2.1 branch on Windows 10 64-bit.

**Comment by 999pingGG** [comment]
Turns out the problem is that the attribute should be `align` instead of `aligned`, this is not what gcc uses and what LuaJIT's docs state...

**Comment by MikePall** [comment]
`aligned` is the correct attribute name. There's no `align` attribute, the parser ignores it. Which means this is the same as a plain struct type again. And that's why this works.

The actual bug is a collateral of #861. Although `ffi.metatype()` accepted non-raw types after that change, it didn't use the raw type number for the lookup table.

Fixed. Thanks!
