### ISSUE TITLE
buildvm tool on aarch64 emits code into data island in text section

### ISSUE THREAD

**Issue by AWSjswinney** [LuaJIT/LuaJIT#1022]
On Linux `aarch64`, the `buildvm` host tool emits code as numeric constants into `src/lj_vm.S`. This is interpreted as data by both clang and gcc assemblers.

```asm
lj_BC_ISLT:
        .long 0xf87b7a60,0x794006b1,0xf87c7a61,0x910012b5
        .long 0x8b110ab1,0xd1408231,0xeb40833f,0x54000161
        .long 0xeb41833f,0x54000221,0x6b01001f,0x9a95b235
        .long 0xb84046b0,0x8b300ec9,0xd3483e1b,0xf947b528
        .long 0xd3507e1c,0xd61f0100,0xfc7b7a60,0x540131c3
        .long 0xfc7c7a61,0xeb41833f,0x540000e8,0x54013141
        .long 0x1e620021,0x14000004,0xfc7c7a61,0x540130c3
        .long 0x1e620000,0x1e612000,0x9a953235,0x17ffffed
```

Both assemblers follow the [spec for ELF on aarch64](https://github.com/ARM-software/abi-aa/blob/main/aaelf64/aaelf64.rst#mapping-symbols) and emit these constants as data islands marked by mapping symbols such as `$d` for data and `$x` for code. However, these sections are not data, but code and other code includes branch instructions which branch into these data islands.

If the symbols are stripped away as in a release build, then there is no problem in the final binary. However, in binaries with symbols included, this is not standard and can confuse dev tools such as llvm-bolt.

One possible solution would be to manually emit `$x` symbols into the assembly to override these data islands, but this is a hack. The diff below does this, but it doesn't current account for platforms other than `aarch64`.
```diff
diff --git a/bazel/foreign_cc/luajit.patch b/bazel/foreign_cc/luajit.patch
index b6da9912e8..db29eb5073 100644
--- a/bazel/foreign_cc/luajit.patch
+++ b/bazel/foreign_cc/luajit.patch
@@ -51,6 +51,30 @@ index 30d64be2..ae7ec875 100644
  #E= @:

  ##############################################################################
+diff --git a/src/host/buildvm_asm.c b/src/host/buildvm_asm.c
+index 7baa011f..2ed5a6b7 100644
+--- a/src/host/buildvm_asm.c
++++ b/src/host/buildvm_asm.c
+@@ -171,6 +171,7 @@ static void emit_asm_wordreloc(BuildCtx *ctx, uint8_t *p, int n,
+ /* Emit an assembler label. */
+ static void emit_asm_label(BuildCtx *ctx, const char *name, int size, int isfunc)
+ {
++  static int mapping_symbol_counter = 0;
+   switch (ctx->mode) {
+   case BUILD_elfasm:
+ #if LJ_TARGET_PS3
+@@ -198,8 +199,9 @@ static void emit_asm_label(BuildCtx *ctx, const char *name, int size, int isfunc
+       "\t.hidden %s\n"
+       "\t.type %s, " ELFASM_PX "%s\n"
+       "\t.size %s, %d\n"
+-      "%s:\n",
+-      name, name, name, isfunc ? "function" : "object", name, size, name);
++      "%s:\n"
++      "$x.mapping.%d:\n",
++      name, name, name, isfunc ? "function" : "object", name, size, name, mapping_symbol_counter++);
+     break;
+   case BUILD_coffasm:
+     fprintf(ctx->fp, "\n\t.globl %s\n", name);
 diff --git a/src/msvcbuild.bat b/src/msvcbuild.bat
 index d323d8d4..2e08a3a1 100644
 --- a/src/msvcbuild.bat
```

Would a patch like this (updated to not break other platforms) be acceptable? Or would some other solution be preferable?

**Comment by MikePall** [comment]
The proposed solution is not sufficient. The assembler implicitly emits a data island for the first `.long` following every plain assembler instruction, e.g. the `bl` from `emit_asm_wordreloc()`. So one would need to emit a mapping symbol at the start and after each `bl`.

But even then ... it looks like this isn't as easy as emitting additional `$x` symbols.

Check the symbol table with `readelf -s lj_vm.o` -- there are now both the implicit and the explicit mapping symbols for each of those addresses. It just so happens that `objdump` (or rather `libbfd`) picks up our symbols and the disassembly is correct. And maybe `llvm-bolt`, too (I haven't tried). But that's probably just a happy coincidence.

I tried to do the same for ARM (32 bit) by emitting `$a` mapping symbols. Here the opposite happens and it's all disassembled as data, no matter what symbols I add.

The only future-proof solution would be an ELF binary emitter, which gives us full control over the object file. This is not that hard (see `jit/bcsave.lua`), but there are some pitfalls. E.g. it needs to exactly match the ELF flags, extensions and relocation types for the cross-compiler toolchain. Otherwise the linker will complain or create a mess.

I think `llvm-bolt` would most likely screw up `lj_vm.o`, anway. There are many dependencies on the order and relative offsets of the interpreter code fragments. That's not visible to any tool.

So this issue then only affects the disassembly of the (non-stripped) LuaJIT binary. Which is nice to have, but doesn't affect the execution at all. Thus I'm marking this issue as an enhancement, but closing it.

Anyone who is brave enough to create an ELF binary emitter (and test it on all platform and toolchain combinations), please create a new issue and link here.
