### ISSUE TITLE
sometimes luajit trigger the ASSERT in aarch64 and abort

### ISSUE THREAD

**Issue by caohongqing** [LuaJIT/LuaJIT#1026]
OS: centos 7.6
ARCH: aarch64(ARM)

Sometimes my program is aborted by luajit and it print the log that is " LuaJIT ASSERT lj_emit_arm64.h:127: emit_lso: load/store offset 32768 out of range", but it's ok in x86.

**Comment by Buristan** [comment]
@caohongqing, may you provide a reproducer for this assertion failure, please?

**Comment by caohongqing** [comment]
Sorry, i didn't get the path to reproduce this assertion failure because it is occasional。There are few assertion failures among thousands of processes every day。
I wonder to know  in which case this assertion failure  occurs, please?
@Buristan 

ps: The assertion failure  happen in openresty.

**Comment by zhongweiy** [comment]
Probably, it is caused by the same issue in https://github.com/LuaJIT/LuaJIT/pull/1028. Could you check it whether the patch fix your problem?

**Comment by MikePall** [comment]
I don't think #1028 is related.

`emit_lso()` should never be called with an out-of-range offset. It would be best if you can provide a stack backtrace from a crash dump.

Otherwise somebody needs to check the ~50 `emit_lso()` callers (and some of their callers) for any possible violation of this assertion. Sorry, but I don't have time left this weekend for that.

**Comment by corsix** [comment]
I am suspicious about the `emit_lso(as, A64I_LDRx, key, idx, kofs);` call in `static void asm_hrefk(ASMState *as, IRIns *ir)`, as the check therein is `int bigofs = !emit_checkofs(A64I_LDRx, ofs)` which is against `ofs` rather than `kofs`.

Based on this suspicion, I can reliably hit the mentioned assert with the following:
```lua
local t = {}
local chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQ"
for c1 in chars:gmatch"." do
    for c2 in chars:gmatch"." do
        t[c1..c2] = 1
    end
end
for c1 in chars:gmatch"." do
    for c2 in chars:gmatch"." do
        loadstring("local t=... for i=1,100 do t[\""..c1..c2.."\"] = i end")(t)
    end
end
```
(A smaller repro might be possible; my Lua is somewhat rusty at the moment)

If I change the code to `int bigofs = !emit_checkofs(A64I_LDRx, kofs);`, then the above no longer hits the assert.

**Comment by MikePall** [comment]
Fixed. Thanks Peter!

**Comment by caohongqing** [comment]
You are so excellent. Thanks very much, @corsix @MikePall @zhongweiy @Buristan

**Comment by corsix** [comment]
Looking at this more, I am concerned about the `emit_opk` call at the very end of ARM64's `asm_hrefk`: `RSET_GPR` is passed as the allow set, which is going to cause a problem if `node` is selected as the victim register. It seems like `rset_exclude(RSET_GPR, node)` should be passed, or if being even more conservative, `allow` should be passed (which at this point will be `RSET_GPR` minus `node` minus `dest`).

**Comment by MikePall** [comment]
@corsix Fixed. Thanks!
