### ISSUE TITLE
Question about the rolling releases

### ISSUE THREAD

**Issue by stefanos82** [LuaJIT/LuaJIT#1053]
I have read https://www.freelists.org/post/luajit/LuaJIT-uses-rolling-releases ; congrats!

I have a question though and it's about

> The full version number in the format $major.$minor.$timestamp can be shown with: luajit -v

Instead of `$timestamp`, is there a way to use the commit hash?

For instance, if I have to report a buggy behavior, `LuaJIT 2.1.03c31124c` makes it a lot clearer than `LuaJIT 2.1.1692716794`, which commit initiated the reported problematic behavior.

Is it possible?

**Comment by MikePall** [comment]
Distros asked for a kind of release number, because most of them are still stuck on the concept of releases.

Others asked for a monotonic version number, so they could ensure it has a fix they depend on. #862

The commit hash is not monotonic. One cannot tell whether X.Y.41c9 is after or before X.Y.3b0f.

That left me with the choice of either manually incrementing a number on every commit (which makes a mess in the git history) or to find some automated way to derive a monotonic version number. I've opted for the latter and the timestamp of the latest commit solves both constraints.

The [status page](https://luajit.org/status.html#release) explains how to get to the commit from the version number. So, please feel free to report a bug against either a version number *or* a commit -- it's easy enough to figure out. Strictly speaking, one should only report issues verified against the latest commit, anyway.
