### ISSUE TITLE
`sudo make uninstall` command does not work as intended

### ISSUE THREAD

**Issue by stefanos82** [LuaJIT/LuaJIT#1059]
I thought it was my idea, but since the newly introduced rolling releases, the `sudo make uninstall` does not work as intended.

I have just pulled the latest changes and after executed the command, I run `ls /usr/local/bin/` to verify it uninstalled the previous release; it did not I'm afraid...

![image](https://github.com/LuaJIT/LuaJIT/assets/1777466/ec1b26e7-f0bc-44b6-937a-17835e2eb719)

**Comment by MikePall** [comment]
Well, it does work when you run the uninstall step with the exact same state as the install step (i.e. before pulling and building). IMHO deleting unrelated (older) installed files would be a bit too risky.

Anyway, distros use their own package manager for uninstalls. The uninstall feature of the Makefile isn't really that popular, I guess.

BTW: Please do not add screenshot images, when you could instead do a plain-text cut'n'paste. Text in images is *not searchable* and also a waste of bandwidth (37K vs. 200 bytes). That's why they are generally frowned upon in issue trackers.
