### ISSUE TITLE
JIT "closure constructors"

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#106]
"Closure constructors", which look like this:

``` lua
function mkcl(some, upvalues, here)
  -- "some", "upvalues", "here" aren't used in this function
  return function()
    -- "some", "upvalues", "here" are used in this function
  end
end
```

should be special-cased. The upvalues aren't shared with any other functions, which means it can be easily JITted. This is useful when making a VM-less VM design, for example:

``` lua
function make_op1(cont, arg1, arg2)
  return function(state)
    state[arg1] = #state[arg2] -- or something
    return cont(state)
  end
end

function make_op2(cont, arg1, arg2, arg3)
  return function(state)
    state[arg1] = state[arg2] + state[arg3] -- or something
    return cont(state)
  end
end

function stop(state)
  return state
end

do
  local f1 = make_op2(stop, 1, 2, 3)
  local f2 = make_op1(f1, 2, 2)
  local f3 = make_op1(f2, 3, 3)
  local state = f3({nil, "a", "b"})
  print(state[1], state[1] == 2)
end
```

Which is the concept the whole of [NoVM](https://github.com/SoniEx2/NoVM) is based on. JITted "closure constructors" would basically mean fully JITtable (incl. code loading) NoVMs in LuaJIT.

The reason I ask this is because I'm trying to make an emulator with LuaJIT, and for it to be good it needs to JIT to machine code. LuaJIT is amazing at JITting NoVM, excluding function prototype construction (which guess what - yep, I need this when JITting to NoVM >.<).

(Then there are the programmers who use closures for classes, but unlike this case, those tend to have shared upvalues...)

**Comment by kirbyfan64** [comment]
Did you forget to commit the source code to NoVM? The only files there are the license and readme...

**Comment by SoniEx2** [comment]
Oh... Uhh, I think I haven't yet finished that...

But this can be used as an example: (heavily commented the confusing part)

```lua
function make_op1(cont, arg1, arg2)
  return function(state)
    state[arg1] = #state[arg2] -- or something
    return cont(state)
  end
end

function make_op2(cont, arg1, arg2, arg3)
  return function(state)
    state[arg1] = state[arg2] + state[arg3] -- or something
    return cont(state)
  end
end

function stop(state)
  return state
end

do
  -- So, we want to take a function like this:
  -- function(a, b) return #a + #b end
  -- and convert it into a NoVM function.
  -- first let's split it up into opcodes:
  -- [takes 2 args, arg1 and arg2]
  -- [has 1 temporary, var1]
  -- LEN arg1 arg1
  -- LEN arg2 arg2
  -- ADD var1 arg1 arg2
  -- RETURN var1
  -- so we start from the bottom up: in this case, `stop` is basically `return`, altho `stop` returns the state. `make_op2` is basically OP_ADD.
  -- in this case, the state has both args and locals in the same place, so we want var1=1, arg1=2, arg2=3
  -- make the OP_ADD with `stop` as continuation. this means we return from the function after adding. it takes 2 and 3 and adds them together, putting the result in 1
  local f1 = make_op2(stop, 1, 2, 3)
  -- make the second OP_LEN, takes the length of 3 and puts it into 3. after doing that, calls `f1` so it can add the lengths together
  local f2 = make_op1(f1, 3, 3)
  -- make the first OP_LEN, takes the length of 2 and puts it into 2. after doing that, calls `f2` so it can take the other length
  local f3 = make_op1(f2, 2, 2)
  -- finally f3 is our entry point. calling it with 2 string arguments adds the length of the 2 strings.
  local state = f3({nil, "a", "b"})
  -- the length of "a" + the length of "b" should be 2, in this case. remember our OP_ADD puts the result in 1, and we passed the arguments in 2 and 3.
  print(state[1], state[1] == 2)
end
```

**Comment by drbo** [comment]
Closure conversion is well known in static compilers.  Perhaps the best approach is to perform it either during parsing or as a bytecode transformation.

**Comment by jirutka** [comment]
This would be also very useful for those of us who prefer to create “objects” using plain closures instead of metatables. :+1:

**Comment by drbo** [comment]
Also, JS VMs have no problem with this.

**Comment by katlogic** [comment]
Just to add to this. I did implement lambda lifting in luajit in my fork. It can be just me being inept, but the changes are quite invasive as a drastic rewrite of local/upvalue handling and fixups in lj_parse.c were needed - together with modified lj_func.c to so that single FNEW also instantiates all its lifted sub-closures too.

The code is still quite buggy to this day that the feature needs to be disabled at times :/

In retrospect, I should've done what Lua 5.2 does - coalesce closures at run time after checking if the upvalues are the same. Advantage would be correct 5.2 semantics, simple implementation and a bit less of gc pressure, disadvantage not being as good as true lambda lifting.

If LJ is not strongly pursuing 5.2 compatibility, not a worthy goal, IMO.

**Comment by DemiMarie** [comment]
Do Lua 5.1 and 5.2 have different semantics here?

**Comment by katlogic** [comment]
@DemiMarie: Yes.

**Comment by DemiMarie** [comment]
@katlogic How do they differ?  Is the Lua 5.1 semantics harder to optimize?

**Comment by katlogic** [comment]
@DemiMarie: Lua 5.2 semantically implements closure transformation at runtime (by comparing upvalues staying the same during closure value creation). In Lua 5.1, each closure is always new, just like in LuaJIT.

http://lua-users.org/lists/lua-l/2011-06/msg01350.html

**Comment by xch91** [comment]
Wow this feature would be so nice to have! It's essentially the basis of currying.

BTW can anyone suggest a convenient and reliable way to tell where in the code could hinder JIT compilation? What I am now doing is checking  NYI page against my source code and byte code manually. Any ideas are much appreciated :)

**Comment by bigbes** [comment]
@xch91 https://github.com/LuaJIT/LuaJIT/blob/master/src/jit/v.lua this should help you

**Comment by xch91** [comment]
@bigbes 
This is awesome! Thank you!

**Comment by xch91** [comment]
Hi @bigbes , after playing with it using some small functions and modules, I'm thinking if I can use it to perform static analysis of generated byte code. Understanding that JIT compilation has to be based on executed traces, I'm not very sure what I'm hoping to do is actually feasible though, esp. my use case is to analyze my extended module written for OpenResty, the HTTP server that extends Nginx using Lua to hook on requests life cycles.

My top concern over JIT compiling my code is, if my function entry has a closure construct, would my following code be able to JIT compile. This question might seem a bit noob here but I've done a bit of search online without finding very systematic documentation on LuaJIT's JIT compilation process. Would you kindly suggest some references where I can RTFM for better understanding of LuaJIT and ask more educated questions?

Thank you once again for your kind help!

**Comment by DemiMarie** [comment]
You can actually replace closures with tables/FFI cdata/etc that have a call
 metamethod.

**Comment by SoniEx2** [comment]
Yeah, but you lose optimization/inlining of constant upvalues, etc.

**Comment by xch91** [comment]
That was exactly where my concern is. If I accidentally coded something that falls back to interpreter horribly, I would like to know it at **static analysis phase**, like compile time instead of runtime or even only under excessive load. That would be way too late.

Also coming back to this issue's main point, using a curry construct is very natural for programmers from FP background, whereas __call metamethod is quite specific to Lua (no I don't know Python XD)

**Comment by lukego** [comment]
@xch91 This is a major challenge: How do you know whether your program will run efficiently?

I don't know of a way to accomplish this with static analysis. LuaJIT code generation is fundamentally very dynamic.

The approach we adopted in Snabb is to create a **benchmark phase** where we test the application under diverse heavy workloads and check for regressions from one branch to the next. This runs on CI and gates merges into important branches.

We are also working on profiler-directed code inspection to help focus on the generated code that actually matters. (It doesn't matter whether initialization code can JIT efficiently but it is necessary that all of the "inner loops" do.)

**Comment by lukego** [comment]
@xch91 Here is an example benchmark checking several branches for regressions based on ~15,000 individual benchmarks: https://hydra.snabb.co/build/1381744/download/2/report.html.

**Comment by xch91** [comment]
@lukego that's a cool process to incorporate but can be a big investment too esp. if the project is not as sizable.

I have something as simple as follows (no upvalues inside the commented portion):
```lua
local M = {}

local function request(method)
  return function(url, payload, headers)
    -- some code that incapsulates API calls
  end
end

M.jget = request('GET')
M.jput = request('PUT')
M.jpost = request('POST')

return M
```
The `jget`, `jput`, `jpost` calls don't seem to be JIT-able at the entry point, per this issue points out. I have some other utility functions that have sealed upvalues which are very common in other languages of good function interface. But apart from the closure construct at entry point, the function bodies are pretty bland and straightforward.

So as you suggested, if it doesn't matter whether initialization code can JIT efficiently but it is necessary that all of the "inner loops" do, my utility functions should be considered _fine_ generally?

**Comment by lukego** [comment]
> that's a cool process to incorporate but can be a big investment too

Yeah. On the one hand the JIT is a pain because it forces you to do a lot of benchmarking to know how your application performs in practical situations. On the other hand automating performance QA can really pay dividends so it doesn't hurt to get a push. (_What appears to be a fault, often, by a change of viewpoint, turns out to be one of the greatest assets you can have._ - [Hamming](http://www.cs.virginia.edu/~robins/YouAndYourResearch.html).)

> So as you suggested, if it doesn't matter whether initialization code can JIT efficiently but it is necessary that all of the "inner loops" do, my utility functions should be considered fine generally?

I have a short answer, a medium answer, and a long answer :).

### Short

Yes, it's fine for "out of the way" code not to JIT.

### Medium

You need a few things:

1. A way to measure your performance e.g. standard benchmark suite.
2. A way to decide if performance is okay. Perhaps performance must satisfy promises made in documentation, new releases must not be slower than older releases, proposed optimizations must be faster than the original code, etc.
3. A way to fix performance when it is not okay e.g. profiling tools to highlight the problem and documentation to understand how to fix it. For example LuaJIT tools `jit.v`, `jit.dump`, `jit.prof`, and the webpages warning about NYI bytecodes and unbiased branches and so on.

I suppose that everybody is finding their own solutions in this space, be it something lightweight or something heavy weight. I reckon there is a lot of potential for new tools and documentation

### Long

I am working on a lot of profiling tools at the moment. Once they are finished I would love to see them adopted by other LuaJIT branches. I am developing them on my RaptorJIT fork.

Selected links:

- Standard benchmark report to evaluate optimizations: https://github.com/raptorjit/raptorjit/issues/46#issuecomment-288061478.
- Top-down Optimization Guide: raptorjit/raptorjit#68.
- IR Code visualizer: https://github.com/raptorjit/raptorjit/pull/63#issuecomment-310138536.
- JIT dumps enriched with profiler data: https://github.com/raptorjit/raptorjit/pull/63#issuecomment-309408425.

I see these are reusable tools to make it easy to understand how an application performs, find the root causes of any performance problems, and make effective optimizations that are well reasoned (not based on trial-and-error voodoo, etc.)

Hoping to collaborate with more people on this stuff in the future!

**Comment by xch91** [comment]
RaptorJIT is totally awesome! It looks esp. promising to be an optional Lua implementation in OpenResty.

Thank you so much for your patient answer here and I do hope one day I can learn enough to contribute to RaptorJIT with my PR :)

**Comment by SoniEx2** [comment]
this whole thing is useless because it's only relevant at load-time and a completely pointless optimization at runtime.

#491 would have real runtime gains and is much easier to optimize than this BS of an issue.

please direct your attention to #491 or open a separate issue if you really think you have a real use-case where creating closures from function arguments and nothing else would be beneficial.
