### ISSUE TITLE
Fix cur_L restoration after return from coroutine call

### ISSUE THREAD

**Issue by fckxorg** [LuaJIT/LuaJIT#1066]
Consider the following Lua C module:
```C
#include <lua.h>
#include <lauxlib.h>

static int error_after_coroutine_return(lua_State *L)
{
	lua_State *innerL = lua_newthread(L);
	/* Remove thread. */
	lua_pop(L, 1);
	luaL_loadstring(innerL, "print('inner coro')");
	lua_pcall(innerL, 0, 0, 0);
	luaL_error(L, "my fancy error");
	return 0;
}

static const struct luaL_Reg libcur_L[] = {
	{"error_after_coroutine_return", error_after_coroutine_return},
	{NULL, NULL}
};

LUA_API int luaopen_libcur_L(lua_State *L)
{
	luaL_register(L, "libcur_L", libcur_L);
	return 1;
}
```

And the following Lua script:
```lua
local libcur_L = require('libcur_L')

local function onesnap_f(var)
  if var then
    return 1
  else
    return 0
  end
end

-- Compile function to trace with snapshot.
if jit then jit.opt.start('hotloop=1') end
onesnap_f(true)
onesnap_f(true)

local r, s = pcall(libcur_L.error_after_coroutine_return)
onesnap_f(false)
```

After building it like this:
```
$ gcc -O0 -ggdb3 -L$HOME/LuaJIT/src -lluajit -I$HOME/LuaJIT/src -fPIC --shared -o libcur_L.so libcur_L.c
```

And running like this:
```
LUA_PATH="$HOME/LuaJIT/src/?.lua;;" LD_LIBRARY_PATH=$HOME/LuaJIT/src $HOME/LuaJIT/src/luajit -jon cur_L.test.lua
```

One can obtain the following output:
```
inner coro
[1]    313309 segmentation fault (core dumped)  LUA_PATH="LuaJIT/src/?.lua;;" LD_LIBRARY_PATH=LuaJIT/src LuaJIT/src/luajit
```

Examining this execution with GDB, we can see that even after the inner coroutine return, the cur_L was not restored to the original Lua state. Opposing to the #740, it doesn't seem to be a Lua/C API misuse.
```
Breakpoint 2, error_after_coroutine_return (L=0x7ffff7c23380) at repro.c:11
11              luaL_error(L, "my fancy error");
(gdb) p L
$12 = (lua_State *) 0x7ffff7c23380
(gdb) p innerL
$13 = (lua_State *) 0x7ffff7c25b90
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x0000555555591b64 in lj_trace_exit (J=0x7ffff7c236b8, exptr=0x7fffffffe0c0) at lj_trace.c:917
917       setcframe_pc(cf, pc);
(gdb) p (lua_State*)(G(L)->cur_L.gcptr64)
$14 = (lua_State *) 0x7ffff7c25b90
```

**Comment by corsix** [comment]
> it doesn't seem to be a Lua/C API misuse

There is API misuse here, though the misuse is easily fixed and the issue remains. The easy fix is removing the two lines 	`/* Remove thread. */` and `lua_pop(L, 1);`, and the issue is that the result of `lua_newthread` is subject to garbage collection, so the GC is technically allowed to free `innerL` between `lua_pop(L, 1);` and `luaL_loadstring(innerL, "print('inner coro')");` (though in practice `lua_pop` won't trigger a GC, and then while `innerL` is the active thread, it'll be a GC root).

**Comment by corsix** [comment]
There's a potential quibble about whether `lua_pcall(innerL, 0, 0, 0);` is legitimate, or whether following `lua_newthread` the only allowable thing is to push onto its stack the main function plus any arguments and then call `lua_resume`. I'll sidestep this for now by noting that the issue persists even if `lua_pcall(innerL, 0, 0, 0);` is replaced with `lua_resume(innerL, 0);`, and then come back to this later. We could also quibble about `luaL_loadstring(innerL`, but there are various workarounds there too, for example `luaL_loadstring(L` followed by `lua_xmove(L, innerL, 1);`.

If not using the C API, the only way to switch coroutine is via `coroutine.resume` or via the result of `coroutine.wrap`, both of which immediately restore `cur_L` after yielding/erroring back to the original coroutine. Hence to hit this issue we first need to call into a C function. That C function needs to change `cur_L` by calling `lua_resume` (or `lua_c?pcall` if taking the broad view). After `lua_resume` returns, a wide range of operations will correct `cur_L`: calling `lua_resume|lua_c?p?call` will correct it, as will returning from the C function. The only problematic path is leaving the C function by throwing an error. If that error is caught by `lua_resume|lua_c?pcall`, then we're back in the same place: the catching C function will correct `cur_L` if it either returns or calls `lua_resume|lua_c?p?call`. If the error is caught by `coroutine.resume` then `cur_L` is immediately fixed. Hence to hit this issue we need the error to be caught by the fast-function `x?pcall`. When `x?pcall` then returns to its caller, we can be executing bytecode in the VM with an incorrect `cur_L`, and things will go badly if we enter a trace before correcting `cur_L`.

The fix proposed in #740 was to set `cur_L` when throwing an error, and that would plug the hole, though the above analysis suggests that it would also be viable to plug it at the point of catching:
```diff
diff --git a/src/lj_err.c b/src/lj_err.c
index 6e50cbee3b..036cbbb744 100644
--- a/src/lj_err.c
+++ b/src/lj_err.c
@@ -174,12 +174,15 @@ static void *err_unwind(lua_State *L, void *stopcf, int errcode)
     case FRAME_PCALL:  /* FF pcall() frame. */
     case FRAME_PCALLH:  /* FF pcall() frame inside hook. */
       if (errcode) {
+       global_State* g;
        if (errcode == LUA_YIELD) {
          frame = frame_prevd(frame);
          break;
        }
+       g = G(L);
+       setgcref(g->cur_L, obj2gco(L));
        if (frame_typep(frame) == FRAME_PCALL)
-         hook_leave(G(L));
+         hook_leave(g);
        L->base = frame_prevd(frame) + 1;
        L->cframe = cf;
        unwindstack(L, L->base);
```

---

Going back to the quibble, for sake of argument, let's say that you want to create a new coroutine, move some arguments over to it, and then resume it. This might look like:
```c
lua_State *L2 = lua_newthread(L);
lua_checkstack(L2, n) || luaL_error(L, "stack overflow on L2");
lua_xmove(L, L2, n);
lua_resume(L2, n-1);
```
Unfortunately, the 5.1 reference manual states that `lua_checkstack` can throw an out of memory error (aside: this is unfortunate, and 5.2 corrects this to make it so that `lua_checkstack` never throws, and I think we should follow the 5.2 behaviour here). If following the rule of "when C code operates on other Lua states [...], it should use them only in API calls that cannot raise errors", then we need to perform this `lua_checkstack` call within a `lua_c?pcall` call. At this point, we cannot quibble about doing `lua_c?pcall` on L2. In other words, `lua_pcall(innerL, 0, 0, 0);` is legitimate. If that argument wasn't convincing, then we could instead note that `lib_jit.c:jit_profile_callback` does a `lua_pcall` on a coroutine object, so it should be fine to do so (though it also does a `lj_str_new` call passing L2, and that could throw via OOM, which goes against our rule of only performing non-throwing operations on foreign coroutines).

At this point it is instructive to look at `coroutine.resume`, as surely (like the above C code) it needs to perform a stack check before moving the arguments over. Looking at `lib_base.c:ffh_resume`, there's a `lj_state_growstack(co, (MSize)(L->top - L->base))` call, and it looks like `lj_state_growstack` can throw (either OOM or LJ_ERR_STKOV). This means that the following causes bad things to happen:
```lua
local function recurser() recurser(coroutine.yield()) end
local co = coroutine.create(recurser)
while coroutine.resume(co, 1, 2, 3, 4, 5, 6, 7, 8, 9) do end
```

It also looks like `lj_api.c:lua_checkstack` calls through to `lj_state_growstack`, meaning that the LuaJIT implementation of `lua_checkstack` can throw in more situations than the reference manual dictates.

There's a commit tidying this up at https://github.com/corsix/LuaJIT/commits/lua_checkstack.

(As one final bonus remark on this side issue, see https://github.com/LuaJIT/LuaJIT/issues/962#issuecomment-1705511741)

**Comment by corsix** [comment]
Coming back to `cur_L`, I find the concept of `cur_L` generally displeasing. It exists so that on-trace code (and supporting adjacent code, such as `lj_gc_step_jit` and `lj_vm_exit_handler`) can get the current `lua_State*`, but said `lua_State*` exists in the current cframe at `CFRAME_OFS_L`, so it is always retrievable with a single sp-load instruction. The "only" complication is that the offset from sp isn't known until the end of assembly process, so it would need a fixup pass once the trace's own stack size is known.

**Comment by MikePall** [comment]
I've taken the `lj_err.c` fix and the `lua_checkstack` fix. Thanks!

I may consider eliminiating `cur_L`, but not in v2.1. Please move this part of the discussion to a separate issue and tag it 3.0 enhancement.

AFAIR there are third-party tools that try to traverse the Lua stack while a trace is running and they rely on `cur_L`. They need some replacement functionality. LuaJIT really ought to provide documented and reliable functions for extended VM introspection and debugging. But again, not in 2.1.
