### ISSUE TITLE
VM handler call on constructed testcase

### ISSUE THREAD

**Issue by ligurio** [LuaJIT/LuaJIT#1087]
Imagine we have the following C snippet `trace_abort.c` that executes a Lua chunk with attached empty C function as a trace hook using `jit.attach`:

```c

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"

static void
jit_attach(lua_State *L, void *cb, const char *event)
{
	lua_getglobal(L, "jit");
	lua_getfield(L, -1, "attach");
	lua_pushcfunction(L, (lua_CFunction)cb);
	if (event != NULL) {
		lua_pushstring(L, event);
	} else {
		lua_pushnil(L);
	}
	lua_pcall(L, 2, 0, 0);
}

/**
 * When trace recording starts or stops.
 */
static int
trace_cb(lua_State *L) {
	(void)L;
	return 0;
}

int
main()
{
	lua_State *L = luaL_newstate();
	if (!L)
		return -1;

	luaL_openlibs(L);
	jit_attach(L, (void *)trace_cb, "trace");
	luaL_dostring(L, "jit.opt.start('hotloop=1')");
	luaL_dostring(L, "repeat until a >= 'b' > 'b'");

	/* Triggers segmentation fault. */
	jit_attach(L, (void *)trace_cb, NULL);
	lua_close(L);

	return 0;
}
```

Build a C snippet with a command below:
`clang trace_abort.c -g -ggdb3 -O0 -o trace_abort -I./LuaJIT/src/ ./LuaJIT/src/libluajit.a -lm`

`trace_abort` will segfaults on execution with following backtrace:

```c++
(gdb) run
Starting program: /home/sergeyb/sources/lua-c-api-tests/trace_abort 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555557e77d in trace_abort (J=0x7ffff7f9b6b8) at lj_trace.c:615
615         lj_vmevent_send(L, TRACE,
(gdb) bt
#0  0x000055555557e77d in trace_abort (J=0x7ffff7f9b6b8) at lj_trace.c:615
#1  0x000055555557f7d2 in trace_state (L=0x7ffff7f9b380, dummy=0x0, ud=0x7ffff7f9b6b8) at lj_trace.c:738
#2  0x0000555555596ea4 in lj_vm_cpcall () at buildvm_x86.dasc:1250
#3  0x000055555557f956 in lj_trace_ins (J=0x7ffff7f9b6b8, pc=0x7ffff7f9b548) at lj_trace.c:758
#4  0x000055555555d94a in lj_dispatch_call (L=0x7ffff7f9b380, pc=0x7ffff7f9b54c) at lj_dispatch.c:494
#5  0x00005555555988c2 in lj_vm_hotcall () at buildvm_x86.dasc:2511
#6  0x0000555555569947 in lua_pcall (L=0x7ffff7f9b380, nargs=2, nresults=0, errfunc=0) at lj_api.c:1145
#7  0x000055555555a8d5 in jit_attach (L=0x7ffff7f9b380, cb=0x55555555a8e0 <trace_cb>, event=0x0) at trace_abort.c:42
#8  0x000055555555a82f in main () at trace_abort.c:67
(gdb)
```

As I got it right, `lj_vmevent_send` in `trace_abort` expects a hook function to be called from Lua and a hook function implemented in C breaks it, right?

Patch below workarounds a problem:

```diff
diff --git a/src/lj_trace.c b/src/lj_trace.c
index f311d54b..1bcbed22 100644
--- a/src/lj_trace.c
+++ b/src/lj_trace.c
@@ -614,6 +614,7 @@ static int trace_abort(jit_State *J)
     J->cur.linktype = LJ_TRLINK_NONE;
     lj_vmevent_send(L, TRACE,
       TValue *frame;
+      TValue *bot = tvref(L->stack)+LJ_FR2;
       const BCIns *pc;
       GCfunc *fn;
       setstrV(L, L->top++, lj_str_newlit(L, "abort"));
@@ -622,12 +623,15 @@ static int trace_abort(jit_State *J)
       frame = J->L->base-1;
       pc = J->pc;
       while (!isluafunc(frame_func(frame))) {
+	TValue *pframe = frame_prev(frame);
+	if (pframe <= bot)
+	    break;
 	pc = (frame_iscont(frame) ? frame_contpc(frame) : frame_pc(frame)) - 1;
-	frame = frame_prev(frame);
+	frame = pframe;
       }
       fn = frame_func(frame);
       setfuncV(L, L->top++, fn);
-      setintV(L->top++, proto_bcpos(funcproto(fn), pc));
+      setintV(L->top++, isluafunc(fn) ? proto_bcpos(funcproto(fn), pc) : 0);
       copyTV(L, L->top++, restorestack(L, errobj));
       copyTV(L, L->top++, &J->errinfo);
     );
```

**Comment by corsix** [comment]
I disagree with the analysis, but nevertheless the patch looks plausible (albeit there might also be something neater we can do in this scenario). Firstly, `lj_vmevent_send` shouldn't care what kind of function you've set  via `jit.attach`. As for what _is_ happening, during the recording of `repeat until a >= 'b' > 'b'`, an error is encountered (unsurprisingly), which (along with raising the error) causes an asynchronous trace abort. That trace abort remains pending until an appropriate time for it to be handled, which in this case is the `lua_pcall(L, 2, 0, 0);` done as part of `jit.attach(trace_cb, nil)`. Part of that handling is reporting said abort to the previously-attached handler, and as part of that, we're searching for the topmost Lua frame on the stack that was active when the trace abort happened, as that indicates where the abort happened. Unfortunately, because the abort was due to an error, and the error was caught by a lua_pcall with errfunc=0, the Lua frame that caused the abort was already removed as part of error processing, so the search cannot find it. Furthermore, in this particular case, there are _no_ Lua frames on the stack, which isn't something the search code had considered possible.

**Comment by ligurio** [comment]
Just want to say it is not a constructed testcase, it was an attempt to gather LuaJIT metrics in fuzzing tests (see https://github.com/ligurio/lua-c-api-tests/pull/30). And yes, I know that function `jit.attach` is not a part of public API.

**Comment by MikePall** [comment]
Fixed. Thanks!
