### ISSUE TITLE
Not understanding sbuf macros

### ISSUE THREAD

**Issue by MaryWan1982** [LuaJIT/LuaJIT#1089]
#define sbufL(sb) \
  ((lua_State *)(void *)(uintptr_t)(mrefu((sb)->L) & SBUF_MASK_L))
#define setsbufL(sb, l)		(setmref((sb)->L, (l)))
#define setsbufXL(sb, l, flag) \
  (setmrefu((sb)->L, (GCSize)(uintptr_t)(void *)(l) + (flag)))
#define setsbufXL_(sb, l) \
  (setmrefu((sb)->L, (GCSize)(uintptr_t)(void *)(l) | (mrefu((sb)->L) & SBUF_MASK_FLAG)))

only setsbufXL_(sb, l)  add "&   SBUF_MASK_FLAG"   , setsbufL(sb, l) was not,   why  sbufL(sb) add "& SBUF_MASK_L"？

lua_State *L    in   function lua_newstate

  L = &GG->L;

L is a address  point,    if the address  low 3bit is not zero,     sbufL(sb)  get error   L,   access it will crash;

**Comment by MikePall** [comment]
That's nonsense. LuaJIT obviously works, so why do you infer it must crash? The low bits of pointers *are zero* and that's why they can be repurposed. The masking/merging is all what these macros are about.

Also, **do not ever** create editorialized or sensationalist titles for issues. Especially when you do not understand the topic. Next time will get you blocked.

**Comment by MaryWan1982** [comment]
> That's nonsense. LuaJIT obviously works, so why do you infer it must crash? The low bits of pointers _are zero_ and that's why they can be repurposed. The masking/merging is all what these macros are about.
> 
> Also, **do not ever** create editorialized or sensationalist titles for issues. Especially when you do not understand the topic. Next time will get you blocked.

someone got the L point low bits were not zero, like this "0xb38c01cc,   0xb38d2f6c,  b3288f6c,......",  the low bits is "1100",  so....
