### ISSUE TITLE
arm32  about sbufL(sb)   

### ISSUE THREAD

**Issue by MaryWan1982** [LuaJIT/LuaJIT#1091]
> That's nonsense. LuaJIT obviously works, so why do you infer it must crash? The low bits of pointers _are zero_ and that's why they can be repurposed. The masking/merging is all what these macros are about.
> 
> Also, **do not ever** create editorialized or sensationalist titles for issues. Especially when you do not understand the topic. Next time will get you blocked.

someone got the L point low bits were not zero (arm32), like this "0xb38c01cc,   0xb38d2f6c,  b3288f6c,......",  the low bits is "1100",  so....

_Originally posted by @MaryWan1982 in https://github.com/LuaJIT/LuaJIT/issues/1089#issuecomment-1729132355_

**Comment by wan1984** [comment]
log:
j_state_newstate  L b38c01cc,  G(L) b38c020c, tmpbuf b38c028c
lj_buf_tmp_:  L b38d2f6c,  G(L) b38c020c  
lj_strfmt_pushvfL:  L b38d2f6c,  G(L) b38c020c,
 lj_buf_more2:  sb b38c028c
lj_buf_more: 44444 sb b38c028c
buf_grow  sb b38c028c
lj_mem_realloc  L b38d2f68, -------the Parameter L now form b38d2f6c  change to b38d2f68 , because  use :sbufL(sb)

one quesetion :How do you ensure that the lower three bits of the address are all zeros?

**Comment by MikePall** [comment]
You're not using the original sources, since this clearly does not happen here. You've made some changes to the allocator at least. Allocators **must** obey minimum alignment, which is at least 8 bytes on all platforms.

**Comment by corsix** [comment]
The bundled memory allocator in `lj_alloc.c` guarantees 8-byte alignment, i.e. lower three bits will be zero. That allocator will be in use unless one of the following is true:
- You pass a custom allocator to `lua_newstate`.
- You specify `-DLUAJIT_USE_SYSMALLOC` as an additional build option.
- You use one of the console build scripts that specify `-DLUAJIT_USE_SYSMALLOC` as a default.

In any of those cases, we fall back to the alignment guarantees of `malloc` (the [Lua manual](https://www.lua.org/manual/5.1/manual.html#lua_Alloc) doesn't _explicitly_ call out alignment requirements on custom allocators, but does so implicitly by saying that they must behave like `malloc`). Standard `malloc` must return memory suitably-aligned for any primitive type. On 64-bit systems, pointers typically have 8-byte alignment, so we're fine. On other systems, `double`s often have 8-byte alignment, so again we're fine. This doesn't cover every single case though, and it looks like you've stumbled upon such a case. It would be good to know full details of your platform and compiler and build settings, so that we have a concrete example to point at (you've said arm32, but is this with FPU or software-emulated floating point? Which OS? If Linux, which libc? etc).

Short of a new GC and associated allocator that would guarantee 16-byte alignment, some patching-up is possible. `lj_state_newstate` could benefit from over-allocating by 8 or 12 bytes, so that `GG_State` is always 16-byte aligned (thereby cleaning up `LJ_KSIMD`, and ensuring 8-byte alignment of the initial `lua_State*`). `lj_state_new` could also over-allocate by 4 bytes to ensure 8-byte alignment of any additional `lua_State*`s. Corresponding deallocations would need to know about this, and possibly remove the alignment bump before freeing the pointer (c.f. `cdataisv`).

**Comment by MikePall** [comment]
I don't think it's helpful to hide this discussion under this bug report.

Platforms with system allocators that do not provide at least 8 byte alignment have never been supported.

Also, 16 bytes is the current minimum that malloc provides on all POSIX platforms, since GCC and LLVM widened `max_align_t` a few years ago and [C libraries had to follow suit](https://github.com/jemalloc/jemalloc/issues/1533).

The new GC in 3.0 will offer (at least) 16 bytes and also remove the ability to plug in a system allocator (except as a dumb backend). No allocator-related changes will go into 2.1, so the discussion is moot.

**Comment by wan1984** [comment]
The memory malloc  is not modified. There is a low probability occurs that the preceding log problem
