### ISSUE TITLE
ffi.istype question

### ISSUE THREAD

**Issue by sonoro1234** [LuaJIT/LuaJIT#1106]
The following script:

```Lua
local ffi = require"ffi"
local a = ffi.new("unsigned short[?]",1)
print(a, ffi.istype("short[]",a), ffi.istype("unsigned short[]",a))
```

prints `cdata<unsigned short [?]>: 0x001ea380   true    true`

is this expected?
That prevents me to know the C type correctly of a pointer that could be signed or unsigned

**Comment by corsix** [comment]
[The documentation](https://luajit.org/ext_ffi_api.html#ffi_istype) for `istype` describes several cases of checking whether `obj` is compatible with `ct` rather than checking whether `obj` is exactly `ct`. One of those cases is pointers, where `unsigned short*` is considered compatible with `short*`. Arrays aren't explicitly mentioned in the documentation, but in practice follow the same compatibility rules as pointers: `unsigned short[]` is considered compatible with `short[]`.

I'm not sure what your use-case is, but [ffi-reflect](https://github.com/corsix/ffi-reflect) _might_ be better suited to it than `ffi.istype`.

**Comment by sonoro1234** [comment]
Thanks very much for answering.

> I'm not sure what your use-case is, but [ffi-reflect](https://github.com/corsix/ffi-reflect) _might_ be better suited to it than `ffi.istype`.

I was stuck with ffi-reflect https://github.com/corsix/ffi-reflect/issues/8 but is already solved so I must have a try.

My use case is for the project https://github.com/sonoro1234/LuaJIT-ImGui where a C++ library (Dear imgui) is wrapped in a C library (cimgui) to be used from LuaJIT ffi. Specifically I want to emulate function overloading from LuaJIT so that based on argument ctypes the relevant C function is called. ffi-reflect could be used in code generation but I would prefer something quicker and simpler to be used in the generated scripts for performance reasons.

I still havent tried with ffi.typeof but

```Lua
print(ffi.typeof("short*")==ffi.typeof"unsigned short*")
```
prints false so that it looks promissing.

**Comment by corsix** [comment]
Yes, `ffi.typeof` will return a type-information object representing the exact type of the passed-in object (which must be a cdata object, or otherwise be a string which'll be parsed as a type). These type-information objects can be used in various ways, including:
- Calling a type-information object, which will construct an object of that type.
- Comparing two type-information objects with `==` or `~=` to establish exact type (in)equality.
- Calling `tonumber` on a type-information object, which gives an opaque number representing the type. The resultant number can be used with `==` or `~=`, giving the same behaviour as the previous point. Notably, the resultant number can also be used as a table key (whereas a type-information object cannot be meaningfully used as a table key). The mapping from type to number is stable within the context of a single Lua VM, but is not guaranteed to be the same in different VMs.

**Comment by sonoro1234** [comment]
The first obstacle found is:

```Lua
ffi.cdef[[typedef signed long long ImS64;]]
print(ffi.typeof"ImS64" == ffi.typeof"int64_t", ffi.typeof"ImS64", ffi.typeof"int64_t")
```
prints `false   ctype<int64_t>   ctype<int64_t>`

I know that `long` and `char` usage is discouraged being platform specific but the cdef comes from Dear ImGui and I am not sure if could be changed

**Comment by corsix** [comment]
You're observing two things:
1. `int` and `long` and `long long` are three distinct C types, even if `sizeof(int) == sizeof(long)` or `sizeof(long) == sizeof(long long)` (you can thank the C standard for this one). Your `ImS64` is `long long` whereas LuaJIT's `int64_t` is `long`.
2. The `__tostring` on type-information objects is designed for convenience rather than exactness, and always gives `"int64_t"` or `"uint64_t"` for 64-bit integers, regardless of whether they're `long` or `long long`.

As we're in the area, it is also worth remarking that `char` and `signed char` and `unsigned char` are three distinct types according to the C standard, but LuaJIT currently _doesn't_ follow this, and instead has just two distinct types here.

**Comment by sonoro1234** [comment]
I am running in 32bit LuaJIT so perhaps this explain ffi.typeof comparison between `long` and `int64_t` fails but it also fails against `int32_t`.

Regarding pointers   `int32_t*` , `int32_t[1]`  , `int32_t[?]` and `int32_t[]` are all different compared by ffi.typeof but should use the same overloaded function. I would like to understand the difference between `int32_t[?]` and `int32_t[]` . The first can be created as `ffi.new('int32_t[?]',1)` but how would the second one be created?

**Comment by corsix** [comment]
> I am running in 32bit LuaJIT so perhaps this explain ffi.typeof comparison between `long` and `int64_t` fails but it also fails against `int32_t`.

This feels like a bug to me; LuaJIT's `int64_t` _should_ be a typedef for one of `int` / `long` / `long long`, but when `sizeof(long) == 4`, LuaJIT's `int64_t` is in fact a typedef for a distinct type that you cannot otherwise refer to. I would suggest something like the following:
```diff
diff --git a/src/lj_ctype.h b/src/lj_ctype.h
index 45e7234ed7..f4a456c181 100644
--- a/src/lj_ctype.h
+++ b/src/lj_ctype.h
@@ -277,6 +277,7 @@ typedef struct CTState {
 #endif
 
 /* Common types. */
+#define CTF_LONG_IF8 (CTF_LONG * (sizeof(long) == 8))
 #define CTTYDEF(_) \
   _(NONE,              0,      CT_ATTRIB, CTATTRIB(CTA_BAD)) \
   _(VOID,              -1,     CT_VOID, CTALIGN(0)) \
@@ -289,8 +290,8 @@ typedef struct CTState {
   _(UINT16,            2,      CT_NUM, CTF_UNSIGNED|CTALIGN(1)) \
   _(INT32,             4,      CT_NUM, CTALIGN(2)) \
   _(UINT32,            4,      CT_NUM, CTF_UNSIGNED|CTALIGN(2)) \
-  _(INT64,             8,      CT_NUM, CTF_LONG|CTALIGN(3)) \
-  _(UINT64,            8,      CT_NUM, CTF_UNSIGNED|CTF_LONG|CTALIGN(3)) \
+  _(INT64,             8,      CT_NUM, CTF_LONG_IF8|CTALIGN(3)) \
+  _(UINT64,            8,      CT_NUM, CTF_UNSIGNED|CTF_LONG_IF8|CTALIGN(3)) \
   _(FLOAT,             4,      CT_NUM, CTF_FP|CTALIGN(2)) \
   _(DOUBLE,            8,      CT_NUM, CTF_FP|CTALIGN(3)) \
   _(COMPLEX_FLOAT,     8,      CT_ARRAY, CTF_COMPLEX|CTALIGN(2)|CTID_FLOAT) \
```

---

> Regarding pointers `int32_t*` , `int32_t[1]` , `int32_t[?]` and `int32_t[]` are all different compared by ffi.typeof but should use the same overloaded function. I would like to understand the difference between `int32_t[?]` and `int32_t[]` . The first can be created as `ffi.new('int32_t[?]',1)` but how would the second one be created?

It can be created as the trailing member of a structure, for example:
```lua
ffi.cdef[[
  typedef struct {
    int values[];
  } S;
  void* malloc(size_t);
]]
local s = ffi.cast("S*", ffi.C.malloc(4))
s.values[0] = 42
```

**Comment by sonoro1234** [comment]
Just to make clear what is happening:

```Lua
local ffi = require"ffi"

print(ffi.typeof("int64_t")==ffi.typeof"int")
print(ffi.typeof("int64_t")==ffi.typeof"long")
print(ffi.typeof("int64_t")==ffi.typeof"long long")
print(ffi.typeof("uint64_t")==ffi.typeof"int")
print(ffi.typeof("uint64_t")==ffi.typeof"long")
print(ffi.typeof("uint64_t")==ffi.typeof"long long")

print(ffi.sizeof"int",ffi.sizeof"long",ffi.sizeof"long long")
```

Running in 32 bits compilation posts all `false` and `4  4  8`
Running in 64 bits compilation does the same.

**Comment by sonoro1234** [comment]
Thanks to everybody!! Now `ffi.typeof("int64_t") == ffi.typeof"long long"` and `ffi.typeof("uint64_t")==ffi.typeof" unsigned long long"` in both 32 and 64 bits

I would like to ask another question related with overloaded functions discrimination.
Now it is working this way: I am checking the typeof of the relevant arguments for every function. 

```Lua
  if typeof(a1)=="int"  then return F1 end
   if typeof(a1)=="float" and typeof(a2)=="float" then return F2 end
   if typeof(a1)=="float" and typeof(a2)=="int" then return F3 end
  error"cant find overload"
```
but I am not sure is this would be more or less performant

```Lua
  if typeof(a1)=="int" then return F1
  elseif typeof(a1)=="float" then
      if typeof(a2)=="float" then return F2
      elseif typeof(a2)=="int" then return F3
      else error"bad type in a2"
  else error"bad type in a1"
  end
```
