### ISSUE TITLE
Debug build with msvcbuild.bat script

### ISSUE THREAD

**Issue by igor725** [LuaJIT/LuaJIT#1127]
When the `debug` argument is passed to the `msvcbuild.bat` script, `%LJCOMPILE%` on [line 101](https://github.com/LuaJIT/LuaJIT/blob/43d0a19158ceabaa51b0462c1ebc97612b420a2e/src/msvcbuild.bat#L101) should run with `/MDd` argument, not `/MD`. This [change](https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170#remarks) will allow to compile correctly debugging version of  `lua51.dll`. Otherwise Lua modules compiled with debugging symbols cannot make some system calls:
![Code_2023-12-03_16-07-39](https://github.com/LuaJIT/LuaJIT/assets/40758030/bf1b0da3-228c-4794-bbd6-0b792d0fb395)

**Comment by MikePall** [comment]
Fixed. Thanks!

**Comment by MikuAuahDark** [comment]
Apparently this breaks our assumption of LuaJIT linking with `/MD` (multithread DLL) instead of `/MDd` (multithread **debug** DLL).

For a bit of context, we start adopting so-called "Source Indexing" to ease debugging our program (either by us or by end-user) without needing full git checkout of our program source code at specific tree.

To have proper source indexing without sacrificing performance, we compile our program in "Release" configuration but at same time generates PDBs. For LuaJIT, LuaJIT build script doesn't generate PDB without `debug` option. So, we compile LuaJIT with `msvcbuild.bat debug` so the LuaJIT build script generates `lua51.pdb` which then consumed for our source indexing mechanism.

Turns out, one of our unsuspecting users trying nightly build of our program started getting error that `vcruntime140d.dll` and `ucrtbased.dll` can't be found. We run dependency walker on the nightly build and found out that LuaJIT links with them instead of the usual `vcruntime140.dll` and `ucrtbase.dll` (note the -d suffix in their filename).

[Note that the `-d` suffix DLLs is not redistributable](https://learn.microsoft.com/en-us/cpp/windows/preparing-a-test-machine-to-run-a-debug-executable?view=msvc-170) so we can't just ship those DLLs as part of our program.

> Debug versions of an application aren't redistributable, and **debug versions of the Visual C++ library DLLs are also not redistributable**.

Perhaps always emitting `lua51.pdb` regardless of `debug` option in here is feasible?

**Comment by MikePall** [comment]
Well, which VC++ option generates a (useful) PDB file without debug mode? And without unwanted side-effects for release mode. Propose a change and I might merge it.

**Comment by MikuAuahDark** [comment]
Something like this suffice my needs.
```diff
diff --git a/src/msvcbuild.bat b/src/msvcbuild.bat
index 91cfd065..62b310bc 100644
--- a/src/msvcbuild.bat
+++ b/src/msvcbuild.bat
@@ -25,7 +25,7 @@
 @set DASC=vm_x64.dasc
 @set LJDLLNAME=lua51.dll
 @set LJLIBNAME=lua51.lib
-@set BUILDTYPE=release
+@set BUILDTYPE=/DEBUG /RELEASE
 @set ALL_LIB=lib_base.c lib_math.c lib_bit.c lib_string.c lib_table.c lib_io.c lib_os.c lib_package.c lib_debug.c lib_jit.c lib_ffi.c lib_buffer.c
 
 @setlocal
@@ -92,12 +92,12 @@ buildvm -m folddef -o lj_folddef.h lj_opt_fold.c
 
 @if "%1" neq "debug" goto :NODEBUG
 @shift
-@set BUILDTYPE=debug
-@set LJCOMPILE=%LJCOMPILE% /Zi %DEBUGCFLAGS%
+@set BUILDTYPE=/DEBUG
+@set LJCOMPILE=%LJCOMPILE% %DEBUGCFLAGS%
 @set LJDYNBUILD=/MDd /DLUA_BUILD_AS_DLL
-@set LJLINK=%LJLINK% /opt:ref /opt:icf /incremental:no
 :NODEBUG
-@set LJLINK=%LJLINK% /%BUILDTYPE%
+@set LJCOMPILE=%LJCOMPILE% /Zi
+@set LJLINK=%LJLINK% %BUILDTYPE% /opt:ref /opt:icf /incremental:no
 @if "%1"=="amalg" goto :AMALGDLL
 @if "%1"=="static" goto :STATIC
 %LJCOMPILE% %LJDYNBUILD% lj_*.c lib_*.c
```

This patch will always generate PDB regardless if "debug" is specified or not. When "debug" is specified, it will link using `/MDd` instead of `/MD` while retaining same behavior.

I don't quite like using the existing `BUILDTYPE` variable for `/DEBUG /RELEASE` so feel free to change as needed.

**Comment by MikePall** [comment]
I've added some more cleanups. Please check. Thanks!
