### ISSUE TITLE
Question: deterministic execution of user-supplied scripts in scope?

### ISSUE THREAD

**Issue by ds-sloth** [LuaJIT/LuaJIT#1153]
Hi, thank you for your work on this project. I'm one of the maintainers for a platforming game engine and we are planning to add user scripting support using a Lua implementation. We're currently considering PUC Lua and LuaJIT.

We have one clear requirement due to our planned network play features: if a particular commit of our engine starts at a certain state and gets a set of user inputs, it *must* end up at the same state, regardless of which platform the program is executing on (including interpreter vs JIT).

This needs to hold even if the user scripts are buggy and invoke behavior undefined by the Lua standard (I'm particularly concerned about the bug of relying on key order: #626, #693, #702). We need either a way of controlling the undefined behavior, or a way of totally forbidding it.

It's unclear to me to what extent our determinism requirement fundamentally conflicts with the design of LuaJIT. Is our use case in the scope of LuaJIT?

Thanks for your time!

**Comment by corsix** [comment]
I think you're going to have an uphill struggle with this, both for PUC Lua and LuaJIT. Various things come to mind (non-exhaustive):
1. `tostring` on non-scalar types, for example `print(tostring({}))` will print something pseudo-random every time.
2. Iteration order of non-scalar types as table keys, for example `local t = {[{"a"}]=1,[{"b"}]=1,[{"c"}]=1} for k in pairs(t) do print(k[1]) end` will usually print a different order every time.
3. Iteration order of strings as table keys. This is build-time configurable in LuaJIT, for example `LUAJIT_SECURITY_PRNG=0` to use a fixed PRNG seed, or `LUAJIT_SECURITY_STRID=0` to use allocation order rather than PRNG for string hashing (though in both cases you might find that the strings allocated during LuaJIT initialisation are platform-dependent).
4. As a LuaJIT-specific thing, whether you're using DUALNUM mode or not. Some platforms _require_ DUALNUM, whereas others have it as an option but disabled by default. As an added wrinkle, DUALNUM conflates -0 and +0 in a few scenarios, and in some of those, whether or not it conflates depends on whether it is running in interpreter or in JIT.
5. In some places, doubles are cast to integers, with the semantics for out-of-range inputs being platform-dependent. To pick one example from many, consider `local t = {[2147483647]="x"} print(table.concat(t, "", 2147483647, 2^33))` on x64 versus arm64. LuaJIT additionally has this come up a lot for FFI code doing floating -> integer conversion, and for `bit` library calls where the inputs are non-integral and/or beyond +/-2<sup>51</sup> (see https://bitop.luajit.org/semantics.html#undefined).
6. The platform's C library is inherited in many places, for example does `print(('%.20f'):format(math.sinh(2)))` give the same thing on all the platforms you care about? Does `os.date` depend on the current locale? LuaJIT might have a slight advantage in this area, as it implements several things from scratch rather than depending on libc.
7. As a LuaJIT-specific thing, throwing errors from JIT-compiled code (e.g. OOM, or `buffer.decode` with invalid input) is slightly hairy, with the behaviour slightly differing between interpreted / JIT-compiled with internal unwinder / JIT-compiled with external unwinder.
8. The bytecode format (i.e. the output of `string.dump`) can be platform-dependent; whether PUC Lua or LuaJIT wins in this regard depends on the various platforms you care about.
9. The maximum stack/recursion depth can vary by platform (and, for LuaJIT, whether you're in JIT or in interpreter). As an example, consider `local n = 0 local function f() n = n + 1 f() end pcall(f) print(n)`.
10. As a LuaJIT-specific thing, the `ffi` library deliberately inherits the platform's semantics in various places, for example `print(require"ffi".sizeof("long"))`.
11. Whether and when LuaJIT will try to JIT-compile any given piece of code is non-deterministic. This is _generally_ unobservable (modulo a few cases listed above), but is _potentially_ observable via the GC, as traces are garbage collectable objects, so allocating one can advance the GC slightly, which can affect when GC triggers, which is observable by when finalisers run or by when weak tables get cleared (if some of your platforms are 32-bit and others are 64-bit, these GC observability remarks apply more widely, as for most types of object, allocating one will push the GC forward different amounts).

**Comment by ds-sloth** [comment]
Wow, this is an extremely helpful list, thanks very much! Many of these are things I am aware of from our C++ base engine (floating-point semantics, stack depth, etc), and some of them are totally new to me (`tostring`, the issue that garbage collector-invoked finalisers will interleave ordinary code execution at unpredictable points).

> with the semantics for out-of-range inputs being platform-dependent

The reference you provided suggests that we'd need to ban the bit library (fair enough, we don't expect user code to be doing serious arithmetic), but do you know whether LuaJIT intentionally ignores IEEE-754 compliance in general? (My understanding was that ensuring `-fno-fast-math` or equivalent would be sufficient to ensure IEEE-754 compliance in host code and PUC Lua.)

**Comment by CapsAdmin** [comment]
This seems like an oddly strict requirement to me, so maybe I'm missing something. 

I've used Lua and LuaJIT in a similar context for many years where server and client needs to have the same state. (for example a character controller with clientside prediction) and the determinism you worry about here has never really been a big problem for me and other people in practice.

Given that you want to run user scripts, you'd probably need to get rid of ffi and various os.* and io.* library functions as well as the ability to run bytecode for security reasons.

Of course, key order and some other things can be a problem if you're not aware of the behavior. But making scripters aware and perhaps provide workarounds can go a long way.

- You can provide a custom pairs function that has deterministic order and/or provide a custom table object that does this.
- If you want to go higher level, you can have a custom key value object that automatically syncs between server and client.
- math.random is also an obvious one. Provide a custom random function that uses the seed from some shared network frame counter.

**Comment by ds-sloth** [comment]
Thanks for the comment. I agree that some of these issues may be relatively minor in practice, though I don't want to rule anything out before testing. Thanks for the notes regarding randomness and security.

The reason we have this oddly strict requirement is that we are implementing "lockstep" networked play -- this doesn't include any state synchronization logic, only content and input synchronization logic. Naturally, this can go very wrong if the game logic diverges between clients, but we generally see full determinism in our C++ base engine, so we are hoping to keep this approach viable as we add scripting.

**Comment by CapsAdmin** [comment]
Most likely the first out of sync problem you'll encounter regardless of scripting language is that some script will do something silly you didn't anticipate. :)

If I were you, I'd make use of the debug tooling you probably have to at least periodically check if everything is in sync.

**Comment by MikePall** [comment]
I'm taking the opportunity to remind you about the difficulties of [sandboxing Lua or LuaJIT](https://luajit.org/faq.html#sandbox). You pretty much need process-level sandboxing to allow those scripts to do anything interesting.

Also, think about your threat model. Wether users install third-party scripts *on their own initiative* and *on their own PC* (like MODs) or users get third-party scripts installed automatically makes a big difference.

In the former case you could invoke a S.E.P. (Somebody Else's Problem). In the latter case you need to inspect, test and approve all scripts (and every update to them) in any case. Which means you don't need to bother with sandboxing or complicated workarounds for non-determinisms. You just need to do a good automatic *and* manual check of the scripts.

**Comment by corsix** [comment]
> Do you know whether LuaJIT intentionally ignores IEEE-754 compliance in general? (My understanding was that ensuring `-fno-fast-math` or equivalent would be sufficient to ensure IEEE-754 compliance in host code and PUC Lua.)

To the best of my knowledge, LuaJIT should do what you want so long as `-fno-fast-math` is specified; the C parts of LuaJIT are subject to the whims of the C compiler, but `-fno-fast-math` should keep the C compiler honest, while the assembly/JIT parts of LuaJIT assume that operands _might_ be NaN/infinity/subnormal/minus-zero and so for example won't optimise away `x != x`, won't re-associate floating-point expressions, etc. The `math.min` and `math.max` functions used to have platform-dependent edge-cases around NaNs/minus-zero, but I think all backends now use exactly the x86 `minss` / `maxss` semantics for these functions.

As we're in the area, I'll also mention `-ffp-contract=off`, which is what you need to keep the C compiler honest with regard to introducing FMA instructions. Since #918, LuaJIT does the equivalent of `-ffp-contract=off`, and if you want FMA introduction (platform-dependent) then you need to specify `-Ofma` or similar.

**Comment by ds-sloth** [comment]
Thanks to everyone for this true wealth of information. This is all extremely valuable.

I'm excited to see that Factorio has done something like this in production software.

> think about your threat model

First off, I'm honored to have you sharing your advice here. :)

There won't be any automatic script downloading, so to a certain extent we can invoke somebody else's problem. (Our dev team is small enough that full review of everything users create is not feasible.) That said, process-level sandboxing is impossible, so this is somewhat scary. One of our primary targets is the Switch homebrew environment, and I believe that all homebrew applications have quasi-root privileges there.

I'm curious that you think it's not feasible to sandbox Lua, but very much inclined to trust you on this. I had thought it would be reasonable to simply disable all libraries interacting with the environment at compile-time, also disable any dynamic code loading, and only allow Lua code to interact with the game engine via our own carefully-constructed interfaces. What can go wrong here?

> keep the C compiler honest with regard to introducing FMA instructions

Wow, I had had no idea that FMA was on by default in the `gnu*` dialects of `gcc`. That's very interesting given that one would normally think that the compiler should follow IEEE-754 by default. Thanks a lot for bringing this to my attention. I suppose we must not have enough sensitivity to numerical boundaries in our core engine to have noticed this so far, but scripts are much less controllable.
