### ISSUE TITLE
msvcbuild.bat static option doesn't build a DLL?

### ISSUE THREAD

**Issue by fiendish** [LuaJIT/LuaJIT#1156]
The static option to msvcbuild.bat doesn't do what I expect.
I believe it should also build a Lua51.dll but using /MT instead of /MD so that msvcrt is used.

**Comment by MikePall** [comment]
That's not what 'static' means in this context. This build option creates a static library to be embedded into an executable.

Linking against the dynamic or static MSVCRT is an orthogonal concern. The use of `/MT` has many downsides, which is why there's no explicit build option for it. If you really want that, then modify `msvcbuild.bat`.
