### ISSUE TITLE
Statically linked C module segfaults on library unload when using `lua_sethook` under MinGW

### ISSUE THREAD

**Issue by sewbacca** [LuaJIT/LuaJIT#1178]
I am trying to compile a C module and link it against the static version of LuaJIT, under mingw/msys2. This works fine, except when the given module sets a hook. A segmentation fault occurs when the C library is unloaded, even though the program runs fine. I was trying to reproduce this example also under Ubuntu, but there it doesn't even compile (see question #1177).

**Reproducible Example**

```c
// bug.c
#include <lua.h>

static void l_hook(lua_State* L, lua_Debug *ar) { }

LUA_API int luaopen_bug(lua_State* L)
{
	lua_sethook(L, l_hook, LUA_MASKCOUNT, 1);
	return 0;
}

```
Compiling the C module:
```shell
# Compiling under msys
> gcc -shared -fPIC -g -o bug.dll bug.c -l:libluajit-5.1.a -IC:/msys64/ucrt64/include/luajit-2.1 -Wl,--export-all-symbols -lm
```

```lua
-- test.lua
require "bug"

-- Disabling jit fixes the issues
-- jit.off()

local str = ""
for i = 1, 25000 do -- Give luajit something to optimize
	str = str..i
end
```

Invoked via
```shell
> luajit test.lua
```

The use case is to compile a Lua library, which can be used as both a Lua C module and a C standalone library. This works fine when linking against the static versions of Lua 5.1 and Lua 5.4.

**Comment by MikuAuahDark** [comment]
I don't think static linking and C modules go together in Windows environment regardless of the compiler.

**Comment by sewbacca** [comment]
> I don't think static linking and C modules go together in Windows environment regardless of the compiler.

Please help me understand this, as for Lua versions 5.1 and 5.4, shared C modules linked statically against Lua work just fine on Windows and Linux. Linking shared C modules statically against LuaJIT only compiles on Windows and works fine unless `debug_sethook` is used. And then it only breaks if jit is enabled *and* the library is unloaded (no problems running the program). Linking a shared library with the static version of LuaJIT on Linux doesn't even compile.

**Comment by MikuAuahDark** [comment]
Yeah. Loading C modules with statically linked Lua is undefined behavior.

**Comment by MikuAuahDark** [comment]
Complete internal state in entire of `lua_State` may be true for vanilla Lua, but not for LuaJIT. LuaJIT may have additional static variables which doesn't have to equal across different statically linked Lua.

As for your last question., it's possible but it's not gonna be pretty. You have to invoke all Lua C API functions through function pointers, because what you want to do is to avoid having any references to Lua C API function (`lua_sethook`, `lua_top`, etc.). Treating the `lua_State*` as an opaque pointer. You retrieve the Lua C API function pointer when Lua calls `luaopen_*` exported C function. You may also want to avoid certain Lua macros as they expand to direct Lua C API function calls (which again, is not something you want).

As for the last thing to say, if you want to statically link Lua, you shouldn't load any C modules. I'm sure Mike would have similar answers to me, more or less.
