### ISSUE TITLE
Windows x64 memory overflow problem 0xE24C4A02

### ISSUE THREAD

**Issue by shrec** [LuaJIT/LuaJIT#1183]
hello I'm developing game server and i integrated luajit 2.1 latest branch in my app. i build it with msvcbuild.bat file
i have high load in game server for luajit in 1 second I'm calling lua function and also from many places calling lua_pcall with different frequency it works stable but some times it gives exception 0xE24C4A02 i debuged code build lua as debug version and what i see when error 0xE24C4A02  diffference between J->pc and J->bc_min always 1003 this happening differently some times exception 0xE24C4A02  rise on start of app.exe sometimes after long run. what is the problem how to determine and fix it? i tested same with lua 5.4 and no errors and exceptions.

**Comment by corsix** [comment]
0xE24C4A02 should be thrown and caught routinely as part of LuaJIT's Windows x64 implementation of Lua runtime errors; calling `error()` in Lua code (or otherwise doing something that should raise an error) will cause LuaJIT to raise 0xE24C4A02, which LuaJIT should then catch at an appropriate `lua_pcall` (or Lua `pcall` / `xpcall`) site.

If you're seeing an uncaught 0xE24C4A02, that suggests one of a few things:
1. An error is being thrown without an appropriate `lua_pcall` (or Lua `pcall` / `xpcall`) on the call stack to catch it.
2. You've built LuaJIT in a way which causes its error handlers to not be registered in a way which `RaiseException` can find them (unlikely if you're using an unmodified `msvcbuild.bat`).
3. You're hitting some kind of LuaJIT bug.

It isn't clear to me what has caused you to mention "memory overflow", or to mention "J->pc and J->bc_min". The latter suggests that `J` is one of the local variables presented by the (Visual Studio?) debugger at the point where there's an uncaught 0xE24C4A02. If so, do you have any other state presented by the debugger (for example a partial call stack)?

**Comment by shrec** [comment]
J->pc and J->bc_min is lua state variables  i mean this happening this is exception

 pc = J->pc;
  if (J->framedepth == 0 &&
     (MSize)((char *)pc - (char *)J->bc_min) >= J->bc_extent)
    lj_trace_err(J, LJ_TRERR_LLEAVE);

in lj_record_ins i cant catch this error it calls exit and app crashing and exiting

**Comment by corsix** [comment]
`lj_record_ins` is only called from `trace_state`, `trace_state` is only called via `lj_vm_cpcall(J->L, NULL, (void *)J, trace_state)`, and the whole point of `lj_vm_cpcall` is to catch exceptions such as this one. If it is failing to catch the exception, then it suggests you have some kind of build-time setting to disable exceptions.

**Comment by shrec** [comment]
how i will disable it? how to build luajit source for x64 windows correctly so not rised this exception and don't kill app
