### ISSUE TITLE
"Table overflow" on {...} table construct when cross-compiling for aarch64 with -Ofast

### ISSUE THREAD

**Issue by Simon-L** [LuaJIT/LuaJIT#1184]
Hello. A bit unsure to post this here as it's not an issue with LuaJIT and rather with a build system assumption. Or a lower level hardware problem. And I'm not familiar with LuaJIT's codebase at all.

Building for arm64 linux from current git with `make CROSS=aarch64-linux-gnu- TARGET_CFLAGS="-Ofast"` , the following code throws a table overflow error:
```lua
function foobar (...)
  local vars = {...} -- <- table overflow happens here
  for i=1,#vars do
    print(vars[i])
  end
end

foobar('a', 'b', 42)
```
Changing the optimisation with eg. `-O3` instead of `-Ofast` solves the issue and the expected prints occur.

I found out while using [losc](https://github.com/davidgranstrom/losc), itself providing a copy of lua-struct, [here is the line that initially triggered the failure](https://github.com/iryont/lua-struct/blob/master/src/struct.lua#L29). I am using the Rocknix distribution where the build script passes the generic target CFLAGS to luajit: https://github.com/ROCKNIX/distribution/blob/main/packages/lang/luajit/package.mk#L44 containing `-Ofast` by default

**Comment by MikePall** [comment]
Oh, well ... please check the GCC docs on what `-Ofast` does:
> [...] **Disregard strict standards compliance.** -Ofast enables all -O3
> optimizations. It also enables optimizations that are not valid
> for all standard-compliant programs.  It turns on **-ffast-math**, [...]

Now search for `"-ffast-math"` and find a million threads about why this is a *really, really bad idea*.

It's completely irresponsible to use such a compiler option distro-wide. It's also pointless as this options *does not make your programs fast*, despite the misleading name. In fact, it makes quite a few programs run slower because the L1 I-cache overflows. And it will break lots of programs silently and subtly -- as you can see here.

Arguably, the GCC maintainers are to blame for the naming of this option. But one should probably avoid using a fringe distro whose maintainers do not understand C compiler options, too.
