### ISSUE TITLE
Why does this lead to such a result, and how should bit.tohex be used properly

### ISSUE THREAD

**Issue by baby0o01999** [LuaJIT/LuaJIT#1186]
a = 0x142912290
b = 0x142912290ULL
print(bit.tohex(a)) -- 42912290

print(bit.tohex(b)) -- 0000000142912290

**Comment by corsix** [comment]
`bit.tohex` does an implicit `bit.tobit` on its 1<sup>st</sup> argument, and then formats the result as a hex string. That implicit `bit.tobit` call is the cause of what you're observing. When called with a 64-bit FFI integer (as in your `b`), `bit.tobit` does nothing, but when called with a regular Lua number (as in your `a`), `bit.tobit` has the semantics:
> Undefined behaviour if input is below -2<sup>51</sup> or above +2<sup>51</sup>. If input isn't integral, round or truncate it to an integer in an implementation-defined way. Return the (unique) integer in the range -2<sup>31</sup> through 2<sup>31</sup>-1 which is equal to the input modulo 2<sup>32</sup>.

In practice, these semantics boil down to "take the low 32 bits; discard any bits above that".

If you don't want the implicit `bit.tobit` call, then `bit.tohex` is not for you. Perhaps you're after `('%x'):format(a)` instead of `bit.tohex(a)`.

**Comment by MikePall** [comment]
A user-centric explanation:

Plain numbers in Lua are floating-point doubles. Whether written in decimal or hex. The mentioned number is outside of the range of 32-bit signed integers. It's truncated before it can be used in (32 bit) bit operations.

FFI `LL` or `ULL` decimal or hex number literals are 64 bit integers. And they stay in that domain when used in (64 bit) bit operations.
