### ISSUE TITLE
luaL_newstate blocks in getrandom() without entropy source

### ISSUE THREAD

**Issue by SeaAndSand** [LuaJIT/LuaJIT#1188]
In my C application on the arm-linux board, I call luaL_newstate and find that it may block. If I put this function in a relatively forward position in main, it will not block. I suspect that the blocking of luaL_newstate is caused by insufficient memory.

**Comment by SeaAndSand** [comment]
arm32 & luajit v2.1.0-beta3

**Comment by MikePall** [comment]
Well, you really need to initialize and fill the Linux kernel entropy pool. Otherwise you'll run into problems with many security-related (TLS, SSH etc.) or security-concious libraries (such as LuaJIT).

If your board has a hardware RNG (most do), then add the device to the config and enable it in the device tree. If not, there are some other ways to do this (search for: `linux entropy sources`).

Also, there's no v2.1.0-beta3 anymore. Always use the current git version.
