### ISSUE TITLE
luajit vs luajit2

### ISSUE THREAD

**Issue by IlyaIndigo** [LuaJIT/LuaJIT#1191]
Hello!
I'm a nginx maintainer in openSUSE and I recently had a need to build nginx-lua-module for redis access and I just now found out about luajit and luajit2 and I want to figure out whether I should replace luajit with luajit2, make them alternatives or use luajit2 only for nginx-module-lua.

What is the difference in them and what are the advantages and disadvantages of each over the other.
OpenResty claims luagit2 works much better with mginx-module-lua.
That's all I understand so far.
Why can't OpenResty patches just be added to upstream?
Is it possible to replace luajit with luajit2 in the operating system and what consequences will this cause, for example for gegl used in gimp?
Or does luajit2 work better only with nginx-module-lua and luajit is better for everything else?
https://github.com/openresty/luajit2/issues/224

**Comment by MikePall** [comment]
First: I'm not responsible for the confusing distro package naming. Please refer to your fellow maintainer colleagues.

The OpenResty LuaJIT variant is just a fork of LuaJIT. They added some changes upon which the OpenResty integration depends. Most of these either do not make sense upstream or are unwanted, rejected and/or unmaintained. And a few are outright dangerous (known HashDoS, unsealed secure PRNG state).

Considering their upstream tracking of important fixes is slow and error-prone, too, there is no place for this fork outside of the OpenResty package itself.

I guess you have their fork as a separate package because distros just like to keep up the modularity illusion. Their own OpenResty releases build against an enclosed copy, anyway. One cannot just glue together nginx + nginx-lua + LuaJIT and hope to get OpenResty.

**Comment by IlyaIndigo** [comment]
Thank you for the reply!

There is no confusion about the name in their fork from my point of view.
I don't understand why these projects exist separately from each other and what their differences are.

From your answer I understand that luajit2 contains risky and unsafe patches and you do not recommend using it for anything other than nginx-module-lua.
Correct me if I have misunderstood you.

As for why I build nginx+(nginx-modulu-lua with liajit2 and lua-resty-core)+lua-resty-redis, I, like many other users of the distribution, want to get this functionality out of the box from a reliable source, and not connect third-party repositories that can contain anything and then depend on them.
And they don't build openresty for openSUSE Tumbleweed.

I still don't understand what a product called openresty is, for me it's just the name of the company that made nginx-module-lua and I've successfully built and used it so far and that's what I wanted and that's enough for me.
