### ISSUE TITLE
IR_ABC hoisting failure

### ISSUE THREAD

**Issue by pwnhacker0x18** [LuaJIT/LuaJIT#1194]
[poc.txt](https://github.com/LuaJIT/LuaJIT/files/15138037/poc.txt)

**Comment by Buristan** [comment]
Hi! I simplified the reproducer to the following:
```
LUA_PATH="src/?.lua;;" src/luajit -Ohotloop=1 -O-fuse -e '

local function f()
  s={nil,nil,nil,nil}
  local t = {}
  for i = 1,2 do
    if i ~= 1 then
      for i = -0,i  do
        if i ~= 0 then
          s[i]=nil
          s={}
       end
      end
    end
  end
  f()
end
f()
'
```

The reason is the missing ABC check for AREF (see `0019 0020`) in the variant part of the loop:
```
0005 >  tab SLOAD  #2    T
0006    int FLOAD  0005  tab.asize
0007 >  p32 ABC    0006  0001
0008 >  p32 ABC    0006  0003
0009    p64 FLOAD  0005  tab.array
0010    p64 AREF   0009  0003
0011    tab FLOAD  0005  tab.meta
0012 >  tab EQ     0011  NULL
0013    nil ASTORE 0010  nil
....        SNAP   #3   [ ---- ---- ---- ---- ---- ---- ---- ---- 0003 0001 ---- ---- ---- ]
0014 >+ tab TNEW   #0    #0
0015  + int ADD    0003  +1
....        SNAP   #4   [ ---- ---- 0014 ---- ---- ---- ---- ---- ]
0016 >  int LE     0015  0001
....        SNAP   #5   [ ---- ---- 0014 ---- ---- ---- ---- ---- 0015 0001 ---- 0015 ]
0017 ------ LOOP ------------
....        SNAP   #6   [ ---- ---- 0014 ---- ---- ---- ---- ---- 0015 0001 ---- 0015 ]
0018 >  int NE     0015  +0
0019    p64 FLOAD  0014  tab.array
0020    p64 AREF   0019  0015
0021    nil ASTORE 0020  nil
```

The reason is missing `PHIBARRIER` for `fload_tab_tnew_asize()` and etc.
With the following patch, the behaviour is fixed:

```diff
diff --git a/src/lj_opt_fold.c b/src/lj_opt_fold.c
index 96780fa2..f917b479 100644
--- a/src/lj_opt_fold.c
+++ b/src/lj_opt_fold.c
@@ -2164,6 +2164,7 @@ LJFOLDF(fwd_href_tdup)
 LJFOLD(FLOAD TNEW IRFL_TAB_ASIZE)
 LJFOLDF(fload_tab_tnew_asize)
 {
+  PHIBARRIER(IR(fins->op1));
   if (LJ_LIKELY(J->flags & JIT_F_OPT_FOLD) && lj_opt_fwd_tptr(J, fins->op1))
     return INTFOLD(fleft->op1);
   return NEXTFOLD;
@@ -2172,6 +2173,7 @@ LJFOLDF(fload_tab_tnew_asize)
 LJFOLD(FLOAD TNEW IRFL_TAB_HMASK)
 LJFOLDF(fload_tab_tnew_hmask)
 {
+  PHIBARRIER(IR(fins->op1));
   if (LJ_LIKELY(J->flags & JIT_F_OPT_FOLD) && lj_opt_fwd_tptr(J, fins->op1))
     return INTFOLD((1 << fleft->op2)-1);
   return NEXTFOLD;
@@ -2180,6 +2182,7 @@ LJFOLDF(fload_tab_tnew_hmask)
 LJFOLD(FLOAD TDUP IRFL_TAB_ASIZE)
 LJFOLDF(fload_tab_tdup_asize)
 {
+  PHIBARRIER(IR(fins->op1));
   if (LJ_LIKELY(J->flags & JIT_F_OPT_FOLD) && lj_opt_fwd_tptr(J, fins->op1))
     return INTFOLD((int32_t)ir_ktab(IR(fleft->op1))->asize);
   return NEXTFOLD;
@@ -2188,6 +2191,7 @@ LJFOLDF(fload_tab_tdup_asize)
 LJFOLD(FLOAD TDUP IRFL_TAB_HMASK)
 LJFOLDF(fload_tab_tdup_hmask)
 {
+  PHIBARRIER(IR(fins->op1));
   if (LJ_LIKELY(J->flags & JIT_F_OPT_FOLD) && lj_opt_fwd_tptr(J, fins->op1))
     return INTFOLD((int32_t)ir_ktab(IR(fleft->op1))->hmask);
   return NEXTFOLD;
```

The loop part looks like the following after the patch:
```
0014 >+ tab TNEW   #0    #0
0015  + int ADD    0003  +1
....        SNAP   #4   [ ---- ---- 0014 ---- ---- ---- ---- ---- ]
0016 >  int LE     0015  0001
....        SNAP   #5   [ ---- ---- 0014 ---- ---- ---- ---- ---- 0015 0001 ---- 0015 ]
0017 ------ LOOP ------------
....        SNAP   #6   [ ---- ---- 0014 ---- ---- ---- ---- ---- 0015 0001 ---- 0015 ]
0018 >  int NE     0015  +0
....        SNAP   #7   [ ---- ---- 0014 ---- ---- ---- ---- ---- 0015 0001 ---- 0015 ]
0019    int FLOAD  0014  tab.asize
0020 >  p32 ABC    0019  0001
0021 >  p32 ABC    0019  0015
0022    p64 FLOAD  0014  tab.array
0023    p64 AREF   0022  0015
0024    nil ASTORE 0023  nil
....        SNAP   #8   [ ---- ---- 0014 ---- ---- ---- ---- ---- 0015 0001 ---- 0015 ---- ]
0025 >+ tab TNEW   #0    #0
0026  + int ADD    0015  +1
....        SNAP   #9   [ ---- ---- 0025 ---- ---- ---- ---- ---- ]
0027 >  int LE     0026  0001
0028    int PHI    0015  0026
0029    tab PHI    0014  0025
---- TRACE 2 stop -> loop
```

**Comment by MikePall** [comment]
IMHO the proposed fix is overreaching. It foils allocation sinking in particular.

Sorry, running out of time to further analyze this right now.

**Comment by corsix** [comment]
> The reason is the missing ABC check for AREF (see `0019 0020`) in the variant part of the loop:

I agree up to here.

> The reason is missing `PHIBARRIER` for `fload_tab_tnew_asize()` and etc.

I can see why this fixes the problem, but I concur with Mike that this is overreaching.

-----

As context, as part of compiling `t[idx]`, `rec_idx_abc(J, #t, idx, ...)` can just emit a regular `IR_ABC(#t, idx)`, but if `idx` is a loop iteration variable (or a loop iteration variable plus/minus a constant), it prefers to emit `IR_ABC(#t, loop_lower_bound_of(idx))` and `IR_ABC(#t, loop_upper_bound_of(idx))`, with the hope that these two checks can then be hoisted out of the loop. By construction, `loop_lower_bound_of(idx)` and `loop_upper_bound_of(idx)` are hoistable, even if they don't obviously look like it (e.g. `loop_lower_bound_of(idx)` can be taken to be just `idx`), so the whole `IR_ABC` should be hoistable iff `#t` is hoistable. If `loop_lower_bound_of(idx)` and `loop_upper_bound_of(idx)` and `#t` are all obviously hoistable, then this hoisting occurs naturally as part of the "Regular invariant ins?" / "Shortcut." in`loop_unroll`. If one of them isn't obviously hoistable, then we have to work harder; `rec_idx_abc` specially marks the hopefully-hoistable `IR_ABC` instructions with an IR type of P32 (rather than I32), then `LJFOLDF(abc_invar)` notices this marker, and returns `DROPFOLD` if `#t` is hoistable (remembering that it doesn't need to check the other operand for hoistability, because the other operand of these specially marked `IR_ABC` is hoistable by construction). Determining whether `#t` is hoistable becomes the fiddly part. When `LJFOLDF(abc_invar)` is executing, then several layers up in the call stack will be `loop_unroll`, and `loop_unroll` easily knows whether `#t` is hoistable (it is the `op1 == ir->op1` test, where `op1` comes from `op1 = subst[ir->op1];`), but this information isn't easily available to `LJFOLDF(abc_invar)`. To get the information, it relies on a previous iteration of `loop_unroll`: when `loop_unroll` previously visited `#t`, it'll end up doing one of:
1. Setting `subst[#t] = #t` (either from "Regular invariant ins?" / "Shortcut.", or from a folding chain that does CSE and ends up back at the original instruction).
2. Setting `subst[#t]` to some new instruction that occurs after `J->chain[IR_LOOP]` (NB: within `loop_unroll`, `J->chain[IR_LOOP]` is the variable called `invar`).
3. Setting `subst[#t]` to some constant.
4. Setting `subst[#t]` to some pre-existing non-constant instruction that occurs before `J->chain[IR_LOOP]`, and marking said pre-existing instruction with `irt_setphi`.

`LJFOLDF(abc_invar)` receives `subst[#t]` as `fins->op1`, so case 2 is excluded via `fins->op1 < J->chain[IR_LOOP]` and case 4 is excluded via `!irt_isphi(IR(fins->op1)->t)`, leaving us in either case 1 or case 3. Herein we reach the root of the issue: the logic does not currently exclude case 3. The proposed patch eliminates a bunch of fold rules that allow `#t` to be substituted by a constant, thereby preventing case 3 from arising, but said fold rules are correct in isolation. One possible alternative would be to further abuse the type field on `IR_ABC` to encode whether `#t` is itself a constant: if `#t` is a constant, then it is trivially hoistable, and if `#t` isn't a constant but `subst[#t]` _is_ a constant, then we're in case 3 rather than case 1 and so it isn't hoistable.

```diff
diff --git a/src/lj_opt_fold.c b/src/lj_opt_fold.c
index ce78505b..e14bf54a 100644
--- a/src/lj_opt_fold.c
+++ b/src/lj_opt_fold.c
@@ -1935,10 +1936,13 @@ LJFOLDF(abc_k)
 LJFOLD(ABC any any)
 LJFOLDF(abc_invar)
 {
-  /* Invariant ABC marked as PTR. Drop if op1 is invariant, too. */
-  if (!irt_isint(fins->t) && fins->op1 < J->chain[IR_LOOP] &&
-      !irt_isphi(IR(fins->op1)->t))
-    return DROPFOLD;
+  /* Invariant ABC marked as P32 or U32. Drop if op1 is invariant too. */
+  if (!irt_isint(fins->t) && fins->op1 < J->chain[IR_LOOP]) {
+    if (irt_isu32(fins->t))
+      return DROPFOLD;
+    else if (!irref_isk(fins->op1) && !irt_isphi(IR(fins->op1)->t))
+      return DROPFOLD;
+  }
   return NEXTFOLD;
 }
diff --git a/src/lj_record.c b/src/lj_record.c
index 6666b3c6..3ba2ce8b 100644
--- a/src/lj_record.c
+++ b/src/lj_record.c
@@ -1395,12 +1395,13 @@ static void rec_idx_abc(jit_State *J, TRef asizeref, TRef ikey, uint32_t asize)
       /* Runtime value for stop of loop is within bounds? */
       if ((uint64_t)stop + ofs < (uint64_t)asize) {
 	/* Emit invariant bounds check for stop. */
-	emitir(IRTG(IR_ABC, IRT_P32), asizeref, ofs == 0 ? J->scev.stop :
+	uint32_t abc = IRTG(IR_ABC, tref_isk(asizeref) ? IRT_U32 : IRT_P32);
+	emitir(abc, asizeref, ofs == 0 ? J->scev.stop :
 	       emitir(IRTI(IR_ADD), J->scev.stop, ofsref));
 	/* Emit invariant bounds check for start, if not const or negative. */
 	if (!(J->scev.dir && J->scev.start &&
 	      (int64_t)IR(J->scev.start)->i + ofs >= 0))
-	  emitir(IRTG(IR_ABC, IRT_P32), asizeref, ikey);
+	  emitir(abc, asizeref, ikey);
 	return;
       }
     }
```

**Comment by MikePall** [comment]
Fixed. Thanks!
