### ISSUE TITLE
FFI floats comparison

### ISSUE THREAD

**Issue by Matrix89** [LuaJIT/LuaJIT#1216]
It seems that when comparing two ffi floats only the integer part is checked eg. 0.1 and 0.5 are equal.

```lua
LuaJIT 2.1.1710088188 -- Copyright (C) 2005-2023 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> ffi = require("ffi")
> a = ffi.cast("float", 0.1)
> b = ffi.cast("float", 0.1)
> = a == b
true
> b = ffi.cast("float", 0.5)
> = a == b
true
> b = ffi.cast("float", 1)
> = a == b
false
>
```

Is this intentional or a quirk of how floats actually work?

**Comment by MikePall** [comment]
Please never box scalar numbers with `ffi.new("int")`, `ffi.new("float")` or similar! This is only useful for passing arguments to vararg functions. Ditto for `ffi.cast()`.

Explicitly boxing scalars *does not improve performance* or force `int` or `float` arithmetic. Or whatever the intention possibly was.

It just adds costly boxing, unboxing and conversions steps. And it may lead to surprise results, because cdata arithmetic on scalar numbers is always performed on 64 bit integers.

I've added this to the documentation. Thanks!
