### ISSUE TITLE
is it possible to use debug.sethook ONLY for specific thread (coroutine)?

### ISSUE THREAD

**Issue by poznir** [LuaJIT/LuaJIT#1230]
i was trying to set hook only for specific coroutine, but it seems like it sets it on the global thread ALWAYS,
is it possible to get it hook JUST specific thread? (like in vanilla Lua)

Example:

**CODE:**

`local co = coroutine.create(function() end)

print("before global", tostring(debug.gethook()))
print("before co", tostring(debug.gethook(co)))

debug.sethook(co, function() end, "c")

print("after global", tostring(debug.gethook()))
print("after co", tostring(debug.gethook(co)))`

**RUN:**

`before global	nil
before co	nil

after global	function: 0x217193faa8b8
after co	function: 0x217193faa8b8`

**Comment by MikePall** [comment]
Hooks are always global in LuaJIT. But you can check for the running coroutine in your hook function.

The problem with Lua 5.x handling hooks only at the coroutine level: debuggers, profilers, runtime limiters, memory limiters etc. need to catch *all* execution paths for *all* coroutines. These tools would need to intercept all coroutine creations and set the hook early enough. But that's quite difficult, since coroutines can be created not just via `coroutine.*` Lua functions, but also from C code in arbitrary C modules. And ... even if they manage to accomplish that, they would still be out of luck when attaching to an already running Lua VM.
