### ISSUE TITLE
Two-parameter logarithm gives incorrect answers for matching inputs

### ISSUE THREAD

**Issue by DUznanski** [LuaJIT/LuaJIT#1240]
The two parameter logarithm `math.log(x,y)` often gives incorrect answers when `x == y`, which should give `1` in all sensible cases (`x > 0 and x ~= 1`)

Which values exactly have problems varies between systems: on my Windows machine, `log(10,10)` gives a value slightly smaller than 1, but on my friend's Linux system that particular value works fine.  However, in all cases, many other values do not work correctly: on all systems tested with the script below, some 13-14% of numbers give a non-1 answer:

`n = 0; for x = 1,10,0.000001 do if math.log(x, x) ~= 1 then n = n + 1 end end; print((n-1) / 9000000)`

For other languages, and other versions of lua, this result is 0. 

Luajit's implementation of the logarithm with given base uses a different method than other sources I've seen for this task: it does `log(x) * (1/log(y))` where others use `log(x)/log(y)`.  These others include all mainline versions of lua starting with 5.2.0, C#, Python, and Rust.  Curiously, luajit's source warns specifically `/* Do NOT join the expression to x / y. */`, and has since this function's first appearance in 2012, but doesn't explain why.

This different implementation is the cause of this issue: taking the reciprocal explicitly like this introduces inaccuracies because almost no representable numbers have representable reciprocals.

**Comment by corsix** [comment]
> Curiously, luajit's source warns specifically `/* Do NOT join the expression to x / y. */`, and has since this function's first appearance in 2012, but doesn't explain why.

My assumption as to why: so that the logic in the interpreter matches the logic in the JIT compiler. In turn, when `y` is constant, the JIT compiler is able to constant-fold `1/log(y)`.

**Comment by MikePall** [comment]
The two-argument form was solely introduced for compatibility with Lua 5.2. Sadly, this is yet another imprudent and gratuitous idea from Rio, since it doesn't (can't) offer any accuracy guarantee.

There's no standard C math library function for a two-argument logarithm base N. No matter how it's derived from what the math library provides, it won't be accurate for the whole input range -- the base itself is no exception in general. Adding a dependency on some huge external library (or copying its code) would be unreasonable just for this function. So the only choice was to at least make it consistently inaccurate, see Peter's comment.
