### ISSUE TITLE
[FR] Per-key specializations of __index and __newindex functions for hot keys.

### ISSUE THREAD

**Issue by Asmageddon** [LuaJIT/LuaJIT#1268]
Just like loops and functions, certain table element accesses can be very hot and performance-critical, but indirect accesses through nontrivial `__index` and `__newindex` functions are not optimized the same way direct access is.

For example, imagine an `__index` function which first checks whether the key matches a string, then whether it's present in a `cdata` object, then another (rarely/never changed) table, then checks if that table contains a `"__get_" .. key` function and if so returns its output, and finally, failing that, calls another function, say `__custom__index`. This is a real example from a class system I've written for personal use.

If the JIT generated per-key specializations, e.g. `__index(*, "x")`, `__index(*, "y"), etc. individual accesses could be reduced to just a single function call - or even inlined as a direct access, in cases where, for example, `obj.x` results in calling `class.__get_x` which simply returns `obj._x`. 

Currently, this does not appear to be the case, with performance declining with the complexity of the `__index`/`__newindex` function, which I believe to be a slight oversight.

If I'm misunderstanding something, or something else is preventing optimizing this, I apologize but would nonetheless like to find a solution - even just being able to store some fields in cdata and some in the table itself without taking a performance hit, could enable a lot of optimizations both memory- and speed- wise.

**Comment by MikePall** [comment]
The compiler cannot simply rely on your intuition or assumption that something 'rarely or never changes'. Specialization involves a correctness guarantee in the form of verified constraints and/or inlined checks. That's the complicated and expensive part -- in particular to handle the case when the assumption turns out to be wrong.

Also, compilers do not have an intuition. Specialization must only be triggered for common patterns with a high reward and not for special cases. Efficient code generation for inverse or alternative cases is hard in general. And specialization back-off is very expensive (invalidate all generated code and data which was based on the wrong assumption). Over-specialization often looks great on micro-benchmarks, but can easily destroy performance for many common cases.

Specialization is a powerful tool in a compiler toolchest, the use of which must be tightly controlled. 

> [...] a class system I've written [...]

Well ... there's your problem.

It's a common and [often discussed](https://www.freelists.org/post/luajit/double-free-or-corruption-issue-HELP,2) phenomenon that Lua newcomers with some experience in other languages have a tendency to write complicated class frameworks as their first mission.

Quoting myself from the mailing list from some time ago:

* Do not invent your own class framework. 
* Do not invent your own dispatch mechanism. 
* Do not try to imitate the dispatch mechanism of any language you've previously learned. 
* Lua metatables and the `__index` metamethod are fine -- you'll get used to them.

**Comment by Asmageddon** [comment]
@MikePall Ah, that makes sense, I've learned something new. Thank you for your detailed response. 

That said, it's not so much replicating OOP itself that I want, as it is to efficiently combine cdata-backed storage with typical table behavior and getters/setters usable via dot syntax on top.

I kind of want to ask further questions, or do further feature requests(like for `__set/get_*` metamethods, or marking code as finalized for the JIT to fully inline), but on some level I recognize that I'm just entertaining my neurosis about performance that nothing I'm going to be writing anytime soon will need.
