### ISSUE TITLE
Incorrect recording of getmetatable() for IO handlers

### ISSUE THREAD

**Issue by ligurio** [LuaJIT/LuaJIT#1279]
Recording of `getmetatable` call with a file descriptors represented by userdata object `UDTYPE_IO_FILE` (like `io.stdout`) leads to violation of assertion in `rec_check_slots`. This happens because `lj_record_mm_lookup` lacks of the corresponding corner case.

The following script illustrates the issue:

```lua
make CFLAGS="-ggdb -g -O0 -DLUA_USE_APICHECK -DLUA_USE_ASSERT" -j10
./src/luajit -Ohotloop=1 -e "
local o = io.stdout
for i = 1, 4 do
  r = getmetatable(o)
end
"
LuaJIT ASSERT lj_record.c:121: rec_check_slots: slot 7 ref -1138 out of range
Aborted (core dumped)
```

Suggested patch:

```diff
--- a/src/lj_record.c
+++ b/src/lj_record.c
@@ -1075,7 +1075,7 @@ int lj_record_mm_lookup(jit_State *J, RecordIndex *ix, MMS mm)
     int udtype = udataV(&ix->tabv)->udtype;
     mt = tabref(udataV(&ix->tabv)->metatable);
     /* The metatables of special userdata objects are treated as immutable. */
-    if (udtype != UDTYPE_USERDATA) {
+    if (udtype > UDTYPE_IO_FILE) {
       cTValue *mo;
       if (LJ_HASFFI && udtype == UDTYPE_FFI_CLIB) {
        /* Specialize to the C library namespace object. */
```

**Comment by MikePall** [comment]
Fixed (differently). Thanks!

The proposed fix would disable the specialization for all IO metamethods.

**Comment by ligurio** [comment]
> The proposed fix would disable the specialization for all IO metamethods.

This specialization omits the check of `__metatable` field precense and the check for the metatable itself. So, if we change the metatable on the object after the trace is compiled, the trace becomes invalid.

Imagine we have a snippet `repro.lua` with a reproducer similar to the original problem:

```lua
local o = io.stdout
local getmetatable = getmetatable
local function test()
  local r
  for i = 1, 4 do
          r = getmetatable(o)
  end
  return r
end
-- Compile.
print(test())
-- Change mt.
getmetatable(io.stdout).__metatable = "IO metatable"
print(getmetatable(io.stdout))
print(test())
```

The result of execution by LuaJIT with committed fix and enabled compiler:

```sh
$  ./src/luajit -Ohotloop=1 repro.lua
table: 0x7e03c5e3de98
IO metatable
table: 0x7e03c5e3de98
```

The result of execution by LuaJIT with committed fix and disabled compiler (same as for the vanilla Lua):

```sh
$  ./src/luajit -joff repro.lua
table: 0x76175404ee98
IO metatable
IO metatable
```

The result may be even worse with using `debug.setmetatable()` (I know your position regarding the `debug` module - it's usage is unsafe):

```
$ ./src/luajit -Ohotloop=1 -e '
local o = io.stdout
local getmetatable = getmetatable
local function test()
  local r
  for i = 1, 4 do
          r = getmetatable(o)
  end
  return r
end
-- Compile.
print(test())
-- Delete mt.
debug.setmetatable(io.stdout, nil)
collectgarbage()
print(getmetatable(io.stdout))
print(test())
'

table: 0x777ba4cdfe98
nil
...
Segmentation fault (core dumped)
```

Therefore, the proposed specialization is dangerous.

**Comment by ligurio** [comment]
> Builtin types (`io` library file objects, etc.) are generally considered special by LuaJIT.

But the `io` type isn't special in LuaJIT. It has the same semantics in the vanilla Lua. Although this is not mentioned in the Lua 5.1 Reference Manual, [the corresponding section of the Lua 5.4 Reference Manual](https://www.lua.org/manual/5.4/manual.html#6.8) mentions the presence of the metatable for `io` objects:

> The metatable for file handles provides metamethods for __gc and __close that try to close the file when called.

So, its metatable may be accessed and changed (via `getmetatable()` or `debug.setmetatable()`), as it is mentioned in the comment.

**Comment by MikePall** [comment]
Well, but that's exactly the problem.

In general, userdata objects should *always* set `__metatable` to prevent access to the actual table. Otherwise it's trivial to crash a classic Lua/C API library by exchanging methods in the `__index` table against methods from other userdata objects.

Most classic C modules check the metatable name in the registry or the metatable identity. LuaJIT checks against a hidden subtype in the IO userdata object, which is much safer. This means you cannot fool these IO methods by adding them to a foreign userdata object's metatable. But you can do the inverse.

But -- as you've pointed out -- the IO object metatable is accessible in Lua 5.1 (which is what's relevant for LuaJIT). And surely some code out there takes advantage of that. So, sadly, we cannot change that unconditionally.

Removing an important optimization is not the way to go here. Peter is right, we should probably anchor the metatable. Then, if someone still insists on changing the IO object metatable and gets weird results, that falls under the "if it hurts, don't do it" category.

If you still have issues with that, then a) run `getmetatable(io.stdout).__metatable = "IO"` upon initialization in *your project* and b) verify that the userdata metatables and `__index` tables of *all* classic C modules in your project are inaccessible.
