### ISSUE TITLE
Fix or ditch trace stitching

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#13]
Trace stitching is currently broken and disabled.

It was quite useful for some code bases with many C calls that would otherwise cause a NYI. It was not so useful for other code bases where enough effort has been put into converting the code to do C calls with the FFI (e.g. OpenResty).

Previous discussion: http://www.freelists.org/post/luajit/small-script-to-reproduce-bogus-trace-stitch-errors-at-line-0-with-coroutines-in-latest-21,1
(please read the whole thread)

If this is to be fixed and re-enabled, please note the stitching heuristics haven't been successfully tuned at all. The trace length turned out not to be a useful criterion, when evaluated in isolation. The -Ominstitch limit was effectively used as an on/off switch.

**Comment by mraleph** [comment]
I've been thinking about this today because code base I work with hits a lot of "NYI: C function" aborts.

I came up with a way to fix stitching which is while being somewhat hacky - seems to be our best shot. 

The core idea is to store boxed _stitch link_ on the stack instead of storing trace number directly on the stack. There is no lightweight boxed `GCobj` so I just decided to go with `GCudata` for this:

```
slot where traceno used to be
v                             v base
[   *    ][  cont  ][  frame ][  ....  ]
    | 
    \--> [ GCudata { int32_t link } ]
```

`link` value is either: 

* *positive value* - _linked state_ - trace number that `cont_stitch` should proceed to;
* *zero* - _blacklisted state_, `cont_stitch` should proceed to `cont_nop`;
* *negative value* - _need to stitch state_ - start tracing and then link trace number `~link` to the newly created trace;

Every time tracer modifies `->link` for some `GCtrace` or flushes this trace away it checks if this trace has `linktype == LJ_TRLINK_STITCH` in which case it finds stitch link box by looking at the last slots of the last snapshot and patches the value contained in the box. 

This way even if the trace dies the stitch link can live on (with a 0 inside because `lj_trace_free` will set it to `0`) and `cont_stitch` will function properly. 

There is one very dodgy part here: touching stitch box object inside `lj_trace_free` -  because we don't know whether trace & box are dying together (in which case box could very well be already freed by a sweeper) or box continues to live on. The way I "solve" this dependency is by assigning a metatable with a dummy `__gc` finalizer to the udata representing the stitch box. This way `GCtrace` object always dies before its stitch box (trace dies during the sweep phase, stitch box dies much later) which makes it safe to look at the stitch box inside `lj_trace_free`.

This solution has certain memory overhead (a udata with finalizer per stitched trace, plus a metatable containing that finalizer if any trace was stitched) but this overhead seems to be reasonably low and is only paid for stitched traces. Solution has a low implementation complexity and doesn't seem to have any architecture implications because it mostly reuses already existing machinery. 

Alternative solution I considered was to write `GCtrace` itself into the slot where its number used to be written - but that requires massaging things like IR typing (which does not support `GCtrace` constants - it's "type" slot is taken by `IRT_P64`) and solving a self-reference problem (have to patch IR constants once actual `GCtrace` is allocated by `trace_save`). So this seems to be more complicated compared to the workaround described above.

I have a patch implementing this fix for x86 ready - so, Mike, if you think this approach has a reasonable ratio of cost/benefit/hackiness[*] and you don't see a mistake in my reasoning then I'll port it to all other supported platforms and send you a PR.

Otherwise, it was a fun exercise - and at least I found another bug in process :)

[*] - I personally feel that it's OK approach, though I am not happy with the fact that I have to box a 4 byte number into a box with 24 byte header (on x86).

**Comment by MikePall** [comment]
After pondering over this for a while, it becomes clear what the real issue was: let the GC do its work and not try to second-guess it with a link number instead of a proper GC reference on the stack. Thank you for the insight!

I think putting the GCtrace object itself on the stack would be the cleanest solution. Freeing the trace needs to blacklist the link, of course.

The chicken-and-egg problem with code generation could be solved by putting a load from a non-moving location into the IR and filling in the final GCtrace later. Maybe split `lj_ir_k64_find()` into search and alloc and only use the alloc part. Then it's always the last allocated K64 constant. Since `irt_to_itype()` is dumb, one could just tag the load as IRT_P64 and `asm_stack_restore()` would do its job. There are a bunch of asserts that might get in the way, but they'll trigger quickly.

**Comment by mraleph** [comment]
Yep, I completely agree with your assessment that putting `GCtrace` into that slot **is** without doubt the cleanest solution [I just was not sure how complicated it would be - so decided to approach it from the side]. 

The only draw back it has, as far as I see it, is that continuations pointing to these _almost dead_ traces will retain more memory compared to a separate _stitch link box_ approach: whole `GCtrace` object + potentially all side traces, sibling root traces and linked traces - in the corner case when trace becomes almost dead when `GCproto`, it was anchored to, died (as opposed to explicit trace flushing - which will just prune strong links between traces and minimize set of retained objects). 

I will give it a shot and send you a PR.

> Freeing the trace needs to blacklist the link, of course.

Do you mean *flushing*? Freeing (as in `lj_trace_free`) won't happen while `GCtrace` is referenced from the stack. Yep, flushing will mark trace as blacklisted.

**Comment by MikePall** [comment]
Memory use ought to be irrelevant for a weird corner case that took 1.5 years to reproduce. ;-)

Yes, flushing.

**Comment by MikePall** [comment]
Thanks! The second approach has been applied to my git master (with modifications).
