### ISSUE TITLE
Why fixed length arrays can be copied but not VLA?

### ISSUE THREAD

**Issue by sonoro1234** [LuaJIT/LuaJIT#1320]
Why fixed length arrays can be copied but not VLA?
gives error: `cannot convert 'float [?]' to 'float [?]'`

```Lua
local ffi = require"ffi"
local VLA = ffi.new("float[?]",5,{1,2,3,4,5})
local V5 = ffi.new("float[5]",{1,2,3,4,5})

local ty = ffi.typeof(V5)
local Y = ty(V5)

print(V5[2],Y[2])

local ty = ffi.typeof(VLA)
local nelem = ffi.sizeof(VLA)/ffi.sizeof(ty,1)
print(ty, nelem)
local Y = ty(nelem,VLA)

print(VLA[2],Y[2])
```

**Comment by MikePall** [comment]
Because, in general, the size of a VLA/VLS is not known to the VM. That's just like in C, where you need to manage the length of arrays yourself.

Technically speaking, the size is known for objects managed by the GC. But not for objects allocated via `malloc`, `mmap` or managed by C libraries. Which is what the VLA/VLS support is mainly intended for.

Anyway, copying variable-length data is often done with offsets, too. And it needs knowledge of both the source and the destination lengths and extra-careful coding to avoid buffer-overflows. That's outside the scope of a low-level library,
 such as the FFI.
