### ISSUE TITLE
Reduce string hash collisions

### ISSUE THREAD

**Issue by bungle** [LuaJIT/LuaJIT#168]
I started this discussion first on LuaJIT mailing list:
http://www.freelists.org/post/luajit/Slowness-due-to-memory-allocation-related-problems

This was also discussed on Hacker News a few years ago:
https://news.ycombinator.com/item?id=3401900

Since then it looks like many of the programming languages have fixed this issue using e.g. randomization. PUC Lua 5.3.2 also seems to have fix for this (don't know exactly when it was fixed there, though). LuaJIT has no fix for this, but there are at least a few unofficial fixes that _DO_ work:
- http://pastebin.com/MbpTPp1N
- http://pastebin.com/xhUbhd3X

How to reproduce:
1. Download this: https://github.com/bungle/lua-resty-template
2. Run `luajit -e 'require "resty.template.microbenchmark".run(1000)'` (in `lib` dir)
3. Run `luajit -e 'require "resty.template.microbenchmark".run(10000)'` (in `lib` dir)

Now compare the results with and without the patches mentioned above. Without patches the `3.` will be about 10x slower than the patched run on the same test (you can try also  `luajit -e 'require "resty.template.microbenchmark".run(100000)'` – 1000000 will start emitting out of memory when 2 GB limit is hit if you have not patched LuaJIT with some bigger memory space patches).

**Comment by drbo** [comment]
The best strong hash function is [SipHash][1].  An optimized implementation that runs quite quickly can be found [here][2].  SipHash is considered to be cryptographically secure, so it avoids all hash collision attacks provided that the 128-bit key is chosen at random and kept secret.

If SipHash is too slow (it might be) another option is to switch the layout of tables to use a balanced binary tree to handle collisions.  This mostly mitigates the problem since the degradation is only to O(log n).

[1]: https://131002.net/siphash/
[2]: https://github.com/floodyberry/siphash

**Comment by funny-falcon** [comment]
SipHash is too slow (for LuaJIT).

Look to the page you've linked: every 7byte string you push to Lua will consume 135 cycle with SSE2 on 32bit platform and 61 cycle on 64bit platform - it is huge amount of CPU time.

So it should be smarter. In https://github.com/LuaJIT/LuaJIT/pull/174 I'm proposing "smart hashing":
- use current hash most of time
- fallback to "harder" hash on collisions

With this scheme, SipHash could be used as fallback function. In fact, I've add an option to use 32bit cousin to SipHash, cause it is faster on 32bit platform, and I wish not use SSE.

But even with this "fallback" approach, it is measurable performance hit to use "strong cryptographic" function instead of "fast and dump" simple whole string hash. And larger function is, larger the hit is.

Perhaps, hardware assisted functions (using `aesenc` hardware instruction) may give good quality function with affordable performance. But, given Mike doesn't want to use platform dependent functions in this place, and even multiplication is forbidden, it will be hard to push it into code base.

And do not forget, when you will suggest SipHash as a function for hash table next time:
- SipHash13 is just enough for this use case, Jean-Philippe Aumasson (author of SipHash) confirms that
- SipHash24 is recommended for MAC - Message Authentication Code - ie when you sign a message, and attacker may see  this sign.

**Comment by MikePall** [comment]
The discussion mixes two different issues:

1. Cryptographically secure hashing.
2. Improving the string hash quality.

In detail:

1. Cryptographically secure hashing is an explicit non-goal.

  1. It's simply unattainable for **the** core data structure of LuaJIT.

  2. A weakened variant is pointless, since it can still be exploited.

  3. Corollary: if you're operating in a context where maliciously crafted data might affect your service, then make sure this doesn't end up as an interned string.

2. Improving the hash quality may be a potentially interesting goal.

  1. But it has to be weighed against the resulting performance impact. Changing a sparse, near constant-time hash to a dense, linear-time hash is a drastic step.

  2. NB: hashing has to be deterministic, due to a couple of internal shortcuts.

  3. To evaluate such a change, it's _not_ helpful and likely misleading to use benchmarks that only employ synthetic strings. It's easy to construct collisions for any non-cryptographically secure hash. But that doesn't say anything about the impact on the average case or the likeliness of the worst case (still) occuring.

3. There are more options:

  1. Don't intern long strings. This has wider reaching consequences for the whole VM and is a non-trivial change.

  2. Use a different data structure, such as a parallel binary search. Needs very careful evaluation.

  3. Combine both options.

**Comment by daurnimator** [comment]
> Don't intern long strings. This has wider reaching consequences for the whole VM and is a non-trivial change.

This option is notable as PUC-Rio lua has taken this route.

**Comment by funny-falcon** [comment]
@MikePall look at https://github.com/LuaJIT/LuaJIT/pull/174 - it keeps using current sparse hash until long collision chain is detected. So that, usual workload is not affected.

When long collision chain is detected, only strings that are not covered by sparse hash (ie longer than 12bytes) and only for this collisioned chain are created with full hash (for default case).

"internal shortcuts" are handled by computed "sparse hash" for a string, that has "full hash" computed. It looks like, all "shortcuts" are for small strings, so that, their performance is not affected.

Benchmark shows no effect on benchmark with no "bad" strings (case 1: unpatched 0.196ms , patched 0.192ms - statistically same) (it could be even faster cause of first commit - compare hashsum while traversing collision chain).

As a bonus, last commit adds option "SMART_STRINGS=2": strong hash function used for all strings that fall in long collision chain - it will cover all paranoid needs. Used function is as resistant to "Seed Independent Collisions" as SipHash, but it is not crypto-safe, cause uses less state and produce just 32bit output. It is slower than SipHash on 64bit platform, but faster on 32bit platform.

**Comment by drbo** [comment]
A couple suggestions:

- Instead of a weakened SipHash, just use SipHash-1-3 and truncate the output if necessary.  Crypto algorithms are brittle &ndash; you can't change them and expect any guarantees unless you are a cryptographer yourself.
- The table I am most worried about is the string intern table.  While it _might_ be okay for LuaJIT's ordinary tables to not be resistant to HashDOS, if the intern table is vulnerable then all strings must be stored in FFI data structures.  That means that &ndash; unless one is willing to risk bugs leading to arbitrary code execution due to violations of memory safety &ndash; one must pay an extra indirection (to keep the FFI data structures in the metatable hidden), and one loses compatibility with most libraries.
- Judy arrays would be a good choice.  Unfortunately the only implementation is LGPL and it doesn't allow strings with NUL bytes in them.

**Comment by funny-falcon** [comment]
SipHash has awful performance on 32bit platform. This 32bit version has all SipHash's properties valuable for hash table, and it has same perfornance either on 32bit or 64bit.

**Comment by drbo** [comment]
@funny-falcon Yes, SipHash is slow on 32 bit.  The solution is to write it using SIMD instructions, either using compiler intrinsics or just placing it in the assembler part of LuaJIT.

The reason why a 32-bit version of SipHash doesn't have SipHash's problems is that one does not get as much nonlinearity, which is critical for security.  The best 32-bit crypto hash function is Chaskey, which is not really any faster than SipHash.

Having thought further, the best thought seems to be to use a HAT-trie and universal hash function.  HAT-tries are cache optimized and are resistant to hash collisions (worst case degradation is O(log n)), at least as long as the fan out is not too high.  Universal hash functions provide an unconditional guarantee of security against all non-adaptive attacks against a hash table.  They are also very fast – and, unlike cryptographic hash functions, _do_ scale down.  For _recent_ Intel processors the best such hash function is CLHash, but otherwise a universal hash function based on evaluating a polynomial modulo a prime, such as polynomial evaluation of a 64-bit key modulo 2^66 - 5.  Note that this can be heavily optimized – look up Poly1305 to for a related example.  And they provide a **provable** guarantee against any attacks in which the attacker is not allowed to submit values after the hash table is created.

**Comment by funny-falcon** [comment]
> The reason why a 32-bit version of SipHash doesn't have SipHash's problems is that one does not get as much nonlinearity, which is critical for security.

@drbo But SipHash's author (Jean-Philippe Aumasson) doesn't agree with you. He says, 32bit version actually  mixes bits *faster* than 64bit version so gives better non-linearity. The single reason why 32bit version is not "secure" is smaller state and 32bit result. That is what he said.

Don't mix crypto-security and hash tables, please. Hash tables doesn't need cryptographically secure functions. They need protection from hash flood (seed independent collisions). Cryptographically secure hash provides protection from hash flood, but it is really overkill.

All your other suggestions are huge modifications. You are free to make a pull request. Lets write meaningful code, not meaning words

**Comment by DemiMarie** [comment]
@funny-falcon sorry!

**Comment by DemiMarie** [comment]
Here are two concrete proposals.  Both keep the current data structure in the fast path, while falling back to a slower (but more robust) alternative in the slow path.

1. Instead of using linear probing to back the hash table, use a tree.  This solves most of the DoS problem – a slowdown to O(n log(n)) is likely to be unexploitable.
2. Use a 2 level hash, with a (cryptographically) strong hash function as the backup hash.  This solves the problem entirely.

**Comment by strrchr** [comment]
I found some hard coded hash values in lj_cparse.c and lib_ffi.c.
If I change the hash algorithm for string interning, I must change these hard coded hash values too.
Horrible!

**Comment by funny-falcon** [comment]
My patch has work around.

**Comment by funny-falcon** [comment]
@DemiMarie
One proposal has implementation and bechmark ( #174 ).
Other is just theoretical suggestion.

**Comment by DemiMarie** [comment]
I like your proposal and hope that it will be merged.

**Comment by corsix** [comment]
An alternative workaround would be to extend GG_State to include all of
these strings, and then identify said strings based on their offset
relative to g rather than based on their (fast) hash value. The same
inclusion-in-GG_State/offset trick could be used for lexically reserved
identifiers instead of the current GCstr::reserved field, which could be
beneficial in the context of the New GC (as abolishing the GCHeader would
leave no convenient space for the GCstr::reserved field, and inclusion in
the GG_State block would be a nice alternative to the LJ_GC_FIXED flag).

**Comment by DemiMarie** [comment]
Do you (or anyone else) plan on implementing the new GC?

**Comment by fsfod** [comment]
Maybe someone :wink: has already working partial implementation of the new GC.  That also allocates the GG_State in the arena and was thinking about the a similar idea to Corsix's for built-in strings allocating them after it you could use the strings cellId in place of reserved id.
I'm not the biggest fan of losing the gct field from objects though because it will no longer be possible to enumerate the objects in an arena based on block bits and for fixed strings the ctype system also creates them you would have to keep them all in a big hash table instead of a dense cellId list per arena.

**Comment by DemiMarie** [comment]
Do you know who the someone is?

**Comment by DemiMarie** [comment]
@fsfod are you that someone :wink: ?

**Comment by thegrb93** [comment]
Apparently HashDOS is being used against luajit powered games now? https://github.com/Facepunch/garrysmod-issues/issues/3526

**Comment by gonzalezjo** [comment]
Hey, that's me. Yeah, here was the code that I used to generate collisions: https://github.com/gonzalezjo/ljhashdos/blob/master/gen.c

**Comment by MikePall** [comment]
Fixed.
