### ISSUE TITLE
The new memory allocator in v2.1 breaks DragonFlyBSD x86_64

### ISSUE THREAD

**Issue by agentzh** [LuaJIT/LuaJIT#181]
Our OpenResty user, lhmwzy, recently reported new regression in the new LuaJIT v2.1 branch on DragonFlyBSD x86_64:

```console
    ~/gh-luajit> ./src/luajit -e 'print("hi")'
    ./src/luajit: cannot create state: not enough memory
```

I've confirmed that the issue was introduced by the git commit 0c6fdc1039a:

```
commit 0c6fdc1039a3a4450d366fba7af4b29de73f0dc6
Author: Mike Pall <mike>
Date:   Mon Apr 18 10:57:49 2016 +0200

    Rewrite memory block allocator.

    Use a mix of linear probing and pseudo-random probing.
    Workaround for 1GB MAP_32BIT limit on Linux/x64. Now 2GB with !LJ_GC64.
    Enforce 128TB LJ_GC64 limit for > 47 bit memory layouts (ARM64).
```

Before this commit, LuaJIT v2.1 builds and runs fine:

```console
    ~/gh-luajit> ./src/luajit -e 'print("hi")'
    hi
```

More details on the OS:

```
~/gh-luajit> gcc --version
gcc 5.2.1 [DragonFly] Release/2015-07-18
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/gh-luajit> uname -a
DragonFly test.com 4.4-RELEASE DragonFly v4.4.1.18.gc5db8-RELEASE #0: Thu Jan 28 15:02:10 CST 2016     foo @terst.com:/usr/obj/usr/src/sys/foo  x86_64
```

We can confirm that FreeBSD x86_64 works normally though :)

**Comment by MikePall** [comment]
This is strange, because the changes should not affect DragonFly (a not-officially supported architecture BTW).

Could @lhmwzy please verify whether adding `defined(__DragonFly__)` to `lj_alloc.c` near line 340 where it checks for `FreeBSD` resolves the matter? With the current git v2.1, of course. Thanks!

**Comment by lhmwzy** [comment]
change 
#if  (defined(__FreeBSD__) || defined(__FreeBSD_kernel__)) &&      !LJ_TARGET_PS4
to 
#if defined(__DragonFly__) || (defined(__FreeBSD__) || defined(__FreeBSD_kernel__)) &&      !LJ_TARGET_PS4

no help.
# ./luajit
src/luajit: cannot create state: not enough memory

**Comment by lhmwzy** [comment]
/h/l/LuaJIT-2.1 # src/luajit
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> 
/h/l/LuaJIT-2.1 # src/luajit
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> 
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
src/luajit: cannot create state: not enough memory
/h/l/LuaJIT-2.1 # src/luajit
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
>    


occasionally can run but mostly can not run

**Comment by mraleph** [comment]
Out of curiosity I probed every single page in the lower 32-bit address space on DragonFly - apparently `mmap(hint, ...)` only returns values from the lower 32bit if you pass hint less than `0x400000` which is image base.

I think the reason in this code from `mmap` implementation 

```c
		/*
		 * Set a reasonable start point for the hint if it was
		 * not specified or if it falls within the heap space.
		 * Hinted mmap()s do not allocate out of the heap space.
		 */
		if (addr == 0 ||
		    (addr >= round_page((vm_offset_t)vms->vm_taddr) &&
		     addr < round_page((vm_offset_t)vms->vm_daddr + maxdsiz))) {
			addr = round_page((vm_offset_t)vms->vm_daddr + maxdsiz);
		}
```

As you can see it uses kernel global parameter `maxdsiz` and not `RLIMIT_DATA` value from the current process. That's why setting rlimit does not help.

**Comment by MikePall** [comment]
Thanks! That explains why the previous version worked, because it passed `0x10000` as a hint.

But ... if your analysis is correct, then we can't allocate more than ~4MB in total on DragonFly. Which is entirely useless beyond tiny code snippets (OK, so that's what the Nginx Lua scripts are mostly used for).

In other words: either the DragonFly kernel maintainers fix hinted mmap or I'll have to add an explicit `#error DragonFly does not respect mmap hints, complain to kernel maintainer`.

**Comment by lhmwzy** [comment]
so,this is a DragonFly issue?

**Comment by lhmwzy** [comment]
<dillon> what mmap() flags are being passed ?

<dillon> If they are passing MAP_FIXED then mmap() is certainly allowed to fail if the address is in a reserved area.  If they aren't, then mmap() is allowed to return any address (the hint is just a hint).
<dillon> I'll run a quick test
<dillon> mmap() properly returns a valid mapping in my tests
<dillon> if MAP_FIXED is not passed (which it shouldn't be).  
<dillon> that valid mapping is past the 4GB mark
<dillon> there is nothing in the mmap() spec that guarantees that a hinted address should be returned.
<dillon> let alone based on the current resource limit
<dillon> on 64-bit systems, dragonfly's adhoc memory allocations (when MAP_FIXED is not used) will always be > the 32GB mark.  That's totally permitted by the spec
<dillon> If they want to allocate space from a specific fixed address, they should use MAP_TRYFIXED
<dillon> (using MAP_FIXED is usually a bad idea since the fixed address might have already been allocated, and MAP_FIXED will override it)

**Comment by MikePall** [comment]
Yes, we are aware that `mmap()` hints are not mandatory. And that `MAP_FIXED` has the wrong semantics (that's why we don't use it).

Yet, the POSIX spec for `mmap()` says:

```
A non-zero value of addr is taken to be a suggestion of a process address near which the mapping should be placed.
```

We are talking about three different things from the kernel perspective:
* What's permitted by the spec: basically everything.
* What can be expected by a reasonable implementation: simply hand out the address, if it's free.
* And what happens in practice: most kernels do just that.

I don't see why a kernel implementation would want to deviate from the intent of the spec. I'm not aware of anyone passing non-NULL hints by mistake. Actually, the only practical use I can imagine is precisely what we do here: trying to get some control over the address space layout due to internal constraints (required address ranges and/or alignment).

While it's laudable that someone attempted to rectify the `MAP_FIXED` semantics, `MAP_TRYFIXED`is a non-standard NetBSDism (and just codifies what the spec intended with hints). We can certainly try to use that, if it's defined and if it fixes the problem.

@lhmwzy Please try to add `|MAP_TRYFIXED` to `MMAP_FLAGS` in `lj_alloc.c` and report back on your findings. Thanks!

**Comment by lhmwzy** [comment]
OK.
change  line 214 from
#define MMAP_FLAGS      (MAP_PRIVATE|MAP_ANONYMOUS)
to
#define MMAP_FLAGS      (MAP_PRIVATE|MAP_ANONYMOUS|MAP_TRYFIXED)

everything runs well.

src/luajit
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> print ("hello")
hello

**Comment by MikePall** [comment]
Fix applied.
