### ISSUE TITLE
Support for shebang in binary code files

### ISSUE THREAD

**Issue by szakharchenko** [LuaJIT/LuaJIT#188]
Regular Lua supports skiping e.g. "#!/usr/bin/env lua" ath the beginning of the file, no matter whether it's a source or compiled file; LuaJit, however, only seems to support it for source files. If I try running a binary file with a shebang line prepended, LuaJIT 2.0.4 says: `luajit: cannot load malformed bytecode`.

**Comment by MikePall** [comment]
This is intentional. Bytecode loading is not secure.

For Lua 5.1, quite a few guides recommended to check the loaded data for a leading escape character to prevent loading of bytecode into a Lua-level sandboxed environment. Most of them fail to account for the shebang ...

LuaJIT does support the Lua 5.2 extensions to the `load*` and `lua_load*` calls that allow explicit control over source vs. bytecode loading. But that doesn't help those apps that are stuck with the older recommendations.
