### ISSUE TITLE
Regard std::uncaught_exception when raising Lua errors as C++ exceptions

### ISSUE THREAD

**Issue by Systemcluster** [LuaJIT/LuaJIT#203]
The value observed by [`std::uncaught_exception`](http://en.cppreference.com/w/cpp/error/uncaught_exception) is not set when LuaJIT raises Lua errors as C++ exceptions.

Example code:

```c++
struct checker {
    ~checker() {
        if(std::uncaught_exception()) 
            std::cout << "unwinding\n";
    }
};

auto l = luaL_newstate();
try {
    checker c;
    luaL_checknumber(l, -1);
}
catch(...) {
    std::cout << "caught\n";
}
```

Expected output: 
> unwinding 
> caught

Observed output:
> caught

(Tested with `g++-mp-7 (MacPorts gcc7 7-20160703_0)`  and `Apple LLVM version 8.0.0 (clang-800.0.31)` on OSX 10.11.5.)

**Comment by MikePall** [comment]
This cannot be fixed.

On targets with full exception interoperability, LuaJIT actually throws a system exception, not a C++ exception. Since C++ uses system exceptions, too, it'll be able to catch those. But any additional sugar provided by C++ is not there, e.g. typed exceptions or the mentioned flag.

LuaJIT cannot use any of the C++ machinery to throw exceptions, as that would imply a hard dependency on the C++ runtime.
