### ISSUE TITLE
IOS/OSX: NYI error when calling C function using FFI on ARM64

### ISSUE THREAD

**Issue by opedge** [LuaJIT/LuaJIT#205]
I'm trying to use FFI with dylib on iOS, but I'm getting the following error: "NYI: cannot call this C function (yet)". After some debug I found that this error is coming from this line: https://github.com/LuaJIT/LuaJIT/blob/v2.1.0-beta2/src/lj_ccall.c#L358

Everything works fine on armv7 or i386, but not on arm64.

What kind of arm64 feature ffi lacks for now according to this line of code?

**Update:** I discovered that this issue appears only when trying to call C function with mixed arguments: pointers and ints/doubles. If C function arguments are only pointers - everything works.

**Comment by kirbyfan64** [comment]
Seems to be register arguments smaller than 8 bytes?

**Comment by opedge** [comment]
What does it mean? Maybe something wrong in building my dylib library? But on armv7 everything works fine.

**Comment by MikePall** [comment]
This is due to Apple's insistence on using a non-standard ARM64 ABI for iOS: [iOS ARM64 Function Calling Conventions](https://developer.apple.com/library/ios/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html). And IMHO for no good reason at all.

I'll merge the required changes, if anyone provides a patch. But this is going to be ugly.

As a workaround, use `int64_t` or `uint64_t` for any arguments beyond the 8th integer argument. You need to do this in both the C code and the FFI declaration. Or consider redesigning your C functions to use fewer arguments.

**Comment by DemiMarie** [comment]
Are there any other cases where this issue can arise (solely with regards to LuaJIT FFI)?

**Comment by corsix** [comment]
Looking into this, I noticed two additional problems:
1. On OSX, the ARM64 JIT miscompiles vararg calls, as Apple always puts variable arguments on the stack (i.e. never in registers). The interpreter handles this correctly in `lj_ccall.c`, but the JIT does it wrong in `lj_asm_arm64.h`.
2. Should we ever support Windows on ARM64, I suspect that both the interpreter and the JIT miscompile vararg calls, as [Microsoft apparently](https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-160#addendum-variadic-functions) puts all floating-point arguments in GPRs / stack (i.e. never in FPRs) for vararg functions (even for the fixed arguments).

I am not addressing problem 2 at the moment, but it shouldn't be too hard to address at some point in the future. With that put to the side, there are seemingly three problems here:
1. On OSX, the ARM64 JIT miscompiles vararg calls.
2. [ignored]
3. On OSX, the ARM64 interpreter NYI aborts on small (<8 bytes) fixed arguments that should be passed via the stack (i.e. once the 8 GPRs and/or FPRs are exhausted).
4. On OSX, once the interpreter is taught to handle the above, the JIT will also need fixing up to match.

The interpreter change for 3 is less ugly than I feared, amounting mostly to a variant of the code that counts stack usage in bytes rather than slots. The JIT change for 1+4 is rather more ugly, as it requires information that `asm_gencall` doesn't currently have: the number of fixed arguments, and the size in bytes of every stack-based fixed argument. I can see two ways of addressing this:
- When appropriate, pass the type signature of the called function through to `asm_gencall`, and have `asm_gencall` jointly iterate the components of the type signature and the IR arguments. This is annoying because not all call instructions in the IR remember the type signature of the called function (though thankfully, where it isn't available, we don't actually need it).
- Encode the additional information in the IR: have the ARM64 backend insert a TREF_NIL at the end of the fixed arguments before the variable ones (c.f. the x86 backend inserting special TREF_NIL values into the argument list), and elide the IR instructions extending stack-based fixed arguments to at least 32 bits and/or insert narrowing casts down to 8 or 16 bits (so that the size stored in the IR node gives the size of the argument). This requires `crec_call_args` to have some knowledge of the backend calling convention, which is ugly, but there's precedent for this in x86. The narrowing casts are also somewhat ugly.

I've explored both approaches - the former at https://github.com/corsix/LuaJIT/commits/arm64-osx-callingconv and the latter at https://github.com/corsix/LuaJIT/commits/arm64-osx-callingconv-b.

(I've not yet done much testing of either implementation, so there could very well be horrific bugs hiding in either at the moment)

**Comment by igormunkin** [comment]
Peter, thanks! Looks like the first branch should resolve tarantool/tarantool#6097.

**Comment by A-Babin** [comment]
I encountered this error trying to call C functions with vector types, but I see that the [ffi semantics](https://luajit.org/ext_ffi_semantics.html#status:~:text=But%20no%20operations%20other%20than%20loading%2C%20storing%20and%20initializing%20them%20are%20supported%2C%20yet.) page says:
> Native vector types may be defined with the GCC mode or vector_size attribute. But no operations other than loading, storing and initializing them are supported, yet.
