### ISSUE TITLE
Internal string formatting for doubles

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#21]
String scanning uses builtin code since 2.0. And it simplified many things, like weirdness with locale settings, dependency on buggy `strtod()` etc.

String formatting has been rewritten for 2.1. But a dependency on sprintf() remains for formatting doubles. This should be replaced with builtin code.

Formatting floating point numbers is surprisingly hard, if one wants to do it both correct, fast and with constant memory.

TODO: Add links to papers and find a suitable algorithm that covers the cases that LuaJIT needs: `tostring()` and the specific subset of options for `string.format("%...[fg]")`.

**Comment by kostja** [comment]
Basically, to do it portably, you need dtoa.c library by David M.Gay. It uses a lot of allocations, though. MySQL patched dtoa to use fewer allocations and even those on a custom allocator, but this code is GPLed, while dtoa itself is copyleft. So, what needs to be done, is repeating MySQL work but releasing the work under BSD rights. I am not aware of any alernatives to this approach, even though I've researched this code thoroughly. This is interesting to our team since we have identical issues with formatting.

**Comment by MikePall** [comment]
IMHO dtoa.c is horrific.

AFAIK there are plenty of non-GPL options out there in the form of BSD/MIT licensed libc variations. However, I don't know whether they use a precise algorithm, which special cases they handle and what their memory footprint is. Investigation needed.

Anyway, to be accepted into the code base, this most certainly needs to be written from scratch, within the design constraints of LuaJIT. But it does help of course to take a look at clean (!) existing code which already implements the chosen algorithm.

**Comment by kostja** [comment]
+1 re dtoa.c code, let's not forget it's 25 years old.
MySQL code here: https://github.com/mysql/mysql-server/blob/5.7/strings/dtoa.c
Last time I looked all libc implementations were either based on dtoa or broken.

**Comment by mraleph** [comment]
There is also [Grisu](http://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf).

**Comment by MikePall** [comment]
Applied.
