### ISSUE TITLE
Possible optimisation for int-to-string conversion on x86

### ISSUE THREAD

**Issue by alnsn** [LuaJIT/LuaJIT#212]
[I posted this on ML about 24 hours ago but it got stuck somewhere]

Hi,

I had discussed faster int to string conversion with Mike a while
ago and the conclusion was that general conversion is skewed towards
small numbers where it's hard to compete with scalar code. But I'd
like to share my code anyway, in case if somebody finds it useful.

The code below is based on "%04u" primitive: for a given number
from 0 to 9999, it writes four ascii digits representing that
number to low bytes of xmm register.

It works best for bigger numbers.  For instance, "%08u" conversion
is nearly 2 times faster while "%04u" conversion is only about 1.4
times faster than the corresponding LuaJIT code on my haswell laptop.

For those who prefer urls, the code is also available on github:
https://gist.github.com/alnsn/83ae6391c66bc1f117b9b6b5fbf2c331

Alex

PS github doesn't let me attach .c file. Get the code from the link above.

**Comment by MikePall** [comment]
As explained in private mail before:

While it may be faster for 'bigger numbers', this code is rather unlikely to beat the simple C code in practice. The common distribution of numbers is heavily skewed towards very small numbers.

Also, converting integers to strings is a rather uncommon activity in real-world applications. Optimizing that beyond the minimally tuned (and portable) implementation that's already present in LuaJIT is a non-goal, since it'll only increase the code size.
