### ISSUE TITLE
Parser doesn't catch some out-of-scope gotos

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#228]
Test case:

``` Lua
repeat
  do ::label:: end
  do goto label end
  break
until false
```

The `goto` should cause a syntax error, since the label is inside an unreachable scope.

But the `break` at the end convinces the parser otherwise. Instead, the `goto` that ought to cause an error is left pointing at itself.

Tricky.

**Comment by stefanos82** [comment]
Without knowing much about Lua's guts or LuaJIT's, I have tested this test case using both versions 5.2.4 and the latest 5.3.3 release; they both seem to catch the error:

```
stefanos@debian:~$ lua5.3
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> repeat do ::label:: end do goto label end break until false
stdin:1: no visible label 'label' for <goto> at line 1
```

Indeed it's an interesting issue I must say.

**Comment by DemiMarie** [comment]
Bug is in `fscope_exit`: if a loop contains a break [`gola_fixup` will not be called][1] leaving unresolved labels undetected.  This cannot cause problems for valid code because `parse_label` [calls `gola_resolve`][2] on each newly parsed label.

[1]: https://github.com/LuaJIT/LuaJIT/blob/master/src/lj_parse.c#L1283
[2]: https://github.com/LuaJIT/LuaJIT/blob/master/src/lj_parse.c#L2419

**Comment by MikePall** [comment]
Applied. Thank you very much!
