### ISSUE TITLE
Improve lexer scanning speed

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#23]
Yes, the lexer is quite fast, but it could be improved even more. The lexer currently (slowly) copies all source characters before interning tokens, scanning numbers, etc. The inner loop for that, as emitted by the C compiler, looks ghastly.

But most of the time it could just pass a pointer to the input buffer. At least if the look-ahead is big enough. There are some difficulties with escapes et al, but one could just fall back to the current copy strategy.

The conditions for this tuning would change, if there was a more efficient approach to string interning: write directly to a buffer and either use that for the new string or recycle it. But that probably depends on the new GC. And it might not be that helpful here, since in practice most of the tokens _are_ already interned.

**Comment by demetri** [comment]
Is there some target for a minimum meaningful difference in performance? I have some experience writing moderately-high-performance zero-copy resumable lexers for NLP applications (including UTF8 support and some limited language/locale sensitive lexing rules). It was a transition-table driven design with a "lexer action bytecode", so each input byte cost a lookup into a ~256 byte table and decoding a 16-bit "action" bytecode indicating lex boundaries and token types. If I recall correctly it was in the ballpark of 100MB/sec on a 2.4GHz machine in 2010, so something like 24 cycles per byte.

If that's anywhere near useful I'd be happy to see if I can help with this.

**Comment by MikePall** [comment]
You're absolutely right: evaluating the potential effect of this tuning should be the first step.

We want a performance ceiling, so one should simplify the conditions: pass a large piece of (diverse) Lua code in a single buffer to the lexer. Any special cases, like string escapes, should be removed or ignored. Then blindly replace the copying in the lexer with counting and reference passing. Ignore error reporting etc. Then measure the speedup and see if it's worth it.

**Comment by demetri** [comment]
Getting a performance ceiling sounds easy enough, even for someone like me :) I can take this on.

Mike, might you by any chance have existing code I could look at to get a test harness up quickly? Just something that lets me load up a string full of Lua code and intercept the beginning/end of parsing.

I'm sure I can figure it out myself but it would be my first time looking at that part of the code. If you happen to have something close to hand that I could use as a starting point it would be appreciated. If not I'll survive :)

**Comment by demetri** [comment]
Perhaps I managed to understand the lexer/parser code more easily than I expected.

Is it accurate that in order to perform this test I need only insert some code inside lj_load.c inside the function cpparser() such that after lj_lex_setup() and before lj_parse(), I spin lj_lex_next() to completion, then bail out and report timing?

Or have I missed something in my understanding of how lj_lex / lj_parse / lj_load interact?

**Comment by MikePall** [comment]
Yes, that would be a lowest-level benchmarking harness.

I thought more along the lines of calling `loadstring()` on some big piece of code. That would measure the changes in the lexer in context. I'm not even sure whether the lexer or the parser or the bytecode generator dominate the cost of compiling source code to bytecode. They call tons of intertwined helper functions elsewhere, so it's hard to properly attribute the costs when profiling.

**Comment by demetri** [comment]
Right, I actually started from the `loadstring()` idea you proposed and traced down the call chain until I got to `cpparser()` as the one actually responsible for instantiating a lexer and `lj_parse()` as the one responsible for spinning it. I can try it both as a raw loop over `lj_lex_next()` and as-called-by `lj_parse()` to see if we can find out how much `lj_lex_next()` itself affects the performance of parsing.

In any case, thanks for the clarification! I'll have some time work on this later today, and should have some baseline numbers tomorrow.

**Comment by demetri** [comment]
Er sorry, one last question: do you have an idea for a representative piece of code? If not I'll probably put together a simple random generator so I can generate source code of tunable size and complexity.

**Comment by MikePall** [comment]
I don't think generated code provides a good benchmark. That is, unless you study enough real-world code to improve the generator to the point where it can successfully imitate the patterns of real-world code. Which is an interesting task, but missing the point.

I'd just grab anything from big repos that turn up in a search for Lua code (e.g. OpenResty has lots of Lua code). Then wrap each file into a dummy function and concatenate all of them to a giant file. That mix might be (somewhat) representative of what a Lua lexer/parser has to handle.

**Comment by demetri** [comment]
Ok, this was easier than I thought. Here are my tentative conclusions, with explanations to follow:

1) `loadstring()` on a pre-allocated string, running the full lexer and parser, runs at about 50MB/sec (2013 MacBook Pro, 4-core i7)

2) Running just the lexer and no parser logic, it runs about 117MB/sec.

3) If you convert 1+2 to relative timings, the lexer alone takes about 40% as much time as the full lexer/parser/loadstring logic.

4) So if we could somehow get the lexer down to 0, we could hope for `loadstring()` to run perhaps at twice the current speed. That gives one conservative performance ceiling.

5) So now how much of the lexer cost comes from the "wasteful" copying of input bytes? An imperfect measurement I've devised suggests that the copying accounts for about 12% of time taken by the lexer alone. That would be about 5% of the overall cost of `loadstring()`.

6) If we don't find a flaw in my measurement metholodogy, then it seems like the potential reward for designing a better / zero-copy lexer is limited.

There is one important caveat: my 12% estimate comes from an indirect measurement that could be misleading due to cache coherency issues (i.e. the effect may be a larger fraction in non-instrumented code).

Here's my methodology:

1) I created two parallel clones of this repo, hereafter "LJ" and "LJHack". LJ is the reference, LJHack is my modified/instrumented version. Both were built with "make clean && make amalg", and I left the executables in their respective /src directories so that I could programmatically call each variant.

2) I grabbed all the Lua code modules linked from the official OpenResty repository (~10k lines in ~35 files). This seemed a little low to me so perhaps I made a mistake somewhere? But superficially it seems correct. In any case it's a matter of seconds to rerun the test with a different pool of source files.

3) I created an amalgamated source file consisting of many (thousands of) functions. Each function's contents were the contents of one of the aforementioned files. I generated enough such functions, each with unique names like `wrapped_fn12345()`,  to reach 100MB of source code. I ran into two limits here: I couldn't go meaningfully over 100MB because I got the error "over 65536 constants" and I couldn't make the functions local (I assume this doesn't matter for lex speed purposes) because I got "main function has over 200 local variables".

4) I created a driver script "loadit.lua" that loads "amalg.lua" into a Lua string, then calls loadstring(), checks for errors, and exits.

5) I timed execution with "time LuaJIT/src/luajit loadit.lua" using the reference LJ variant reliably getting timings around 2.2 seconds. If I removed the loadstring call (to get some idea of the string creation overhead) I got ~200ms. Hereafter I will report run-times net having subtracted 200ms of overhead. At 2 seconds of net run time this yields ~50MB/sec for the full lex/parse execution in the reference implementation.

6) I modified LJHack to process the lexing/parsing of loadit.lua as usual, but upon starting the lexing/parsing of amalg.lua to take a different codepath within `lj_parse()`. Specifically, where the very first call to `lj_lex_next()` happens it just spins in a loop until `ls->token` is `TK_eof` (i.e. it doesn't exercise any of the parsing logic, it just tests the lexer).

7) I timed LJHack with the same method "time LuaJITHack/src/luajit" on the same machine and reliably got timings about 850ms (42% compared to LJ), or about 117MB/sec.

Superficially, this suggests a that a bit under half of the cost of a full `loadstring()` is in the core lexing logic.

In order to measure how much of the lexing cost came from copying, I had a few options. The ideal, but complex, experiment would be to rearrange the code not to `save()` or `save_grow()` input bytes but instead to pass around pointers to the input buffer. This would have required a fair amount of modification to internal logic in the lexer so I took a different approach: adding *extra* copies of the input byte into an otherwise-unused 1MB circular buffer. By varying how many times each input byte was re-copied I could get a rough idea of how much the lexer would suffer if copies were more expensive.

Using a re-copy ratio of 100x I saw a ~13x ratio in the total run-time of the lexer alone, with nearly linear behavior for re-copy ratios between 0 and 100. If you work out the algebra for the relative timing (and assuming the non-copy cost is fixed), you'll find that the cost of the non-instrumented copies is roughly 12% of the total cost of the lexing.

**Comment by MikePall** [comment]
Thank you very much for the detailed investigation! These numbers will be helpful for any future tuning attempt.

I agree with both your reasoning and your conclusion that a potential speedup of max. 5% is not worth it. One needs the buffer for the more complicated cases, anyway. The proposed change would just increase code complexity without a real gain.

Closing as WONTFIX.
