### ISSUE TITLE
DynASM emitting jumps to wrong addresses

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#234]
I wrote a test program that uses DynASM.  When run, it segfaults because it tries to jump to an address with the high bit set.  The incorrect address is exactly `correct_address | (1ULL << 63)`.

**Comment by DemiMarie** [comment]
Here is the file that reproduces the crash.  It isn't minimized at all, but does successfully compile.  GDB shows that the segfault happens in the `JMP` instruction, when the code tries to jump to an address that has the high bit set.
[testcase.zip](https://github.com/LuaJIT/LuaJIT/files/556582/testcase.zip)

**Comment by MikePall** [comment]
x64 machine code doesn't have jumps with 64 bit range.

That's why absolute relocations (`REL_A`), as used by `jmp &`, are not supported and/or will give wrong results if out of range. External functions, like those defined in your code, are usually out of range.

Use PC labels for jumps between generated code pieces. Use `mov64 + jmp reg` or GOT-style indirect jumps for all other use cases.
