### ISSUE TITLE
ffi.strerror()

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#306]
Often, it is necessary to turn the `errno` value into a human-readable error message.

Doing this in a portable and thread-safe way is a mess.  `strerror` is portable, but thread-unsafe.  `strerror_r` is thread-safe, but glibc provides an incompatible version.  (It does provide a POSIX-compliant version, but via a macro, which doesn't help LuaJIT).  And Windows doesn't provide `strerror_r` at all, but rather `strerror_s` and `strerrorlen_s`, which again are incompatible.  Furthermore, LuaJIT does not provide a portable way of getting the C library (`ffi.abi 'glibc'` returns `false` on my glibc system).

`ffi.strerror` can be implemented in Lua using other FFI functions, provided that a way to get the libc version in use is present, or it can be implemented as a built-in in C.  Since it is mainly for use in user-facing error messages, there is no need to compile it (unless applications use it heavily for logging).  (The original value of `errno` is preferred for programmatic use, since the error message in general depends on the current locale).

**Comment by MikePall** [comment]
As you said, the portability issues for `strerror` are complicated. Shifting the burden from the FFI user to the LuaJIT core is not an acceptable proposition.

The FFI library provides a low-level API. It does not and will not offer an all-encompassing system library or portability layer (which BTW is really, really hard). This is simply outside of its scope.

[ The situation is different for `errno`, since one cannot safely access it at the FFI user level. That's why the core has to provide `ffi.errno`. ]

**Comment by DemiMarie** [comment]
Makes sense.
