### ISSUE TITLE
Cross compilation fails with newer(ish) -march flags.

### ISSUE THREAD

**Issue by DeadSix27** [LuaJIT/LuaJIT#310]
Probably has something to do with newer instruction sets?
make line:

```make
make HOST_CC="gcc -m64" CROSS=x86_64-w64-mingw32- TARGET_SYS=Windows CFLAGS="-march={see list below} -O3" amalg
```

Error:
```make
make all "LJCORE_O=ljamalg.o"
make[2]: Entering directory 'src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
Makefile:608: recipe for target 'host/buildvm_arch.h' failed
make[2]: *** [host/buildvm_arch.h] Illegal instruction (core dumped)
make[2]: Leaving directory 'src'
Makefile:577: recipe for target 'amalg' failed
make[1]: *** [amalg] Error 2
```
Failing marchs:
znver1 (ryzen), skylake, bdver4, broadwell, haswell

Working:
ivybridge, core2, and older probably (altho not tested)

Either way if its a instruction set I guess its one of those?: 
`FMA, AVX2, BMI, BMI2, F16C, MOVBE`

As those are the only difference between ivybridge and haswell for example.

But this goes beyond my understanding, always thought instruction sets have to be build upon/used in the code, so why does it fail if the code seemingly doesn't use them anyway.

**Comment by corsix** [comment]
Why on earth are you passing an `-march` flag with random instruction sets in the first place? What you are trying to achieve?

> always thought instruction sets have to be build upon/used in the code

No. As one example, having specified `MOVBE` in your `-march` list, `__builtin_bswap32` might get compiled to `movbe` rather than `mov`+`bswap`. As a more insidious example, having specified `BMI2` in your `-march` list, `<<` and `>>` operators might get compiled to `shlx` and `shrx` rather than `shl` and `shr`. As yet another example, having specified `AVX2`, a very clever compiler might decide to vectorise some random integer code with a bunch of AVX2 instructions (we have seen, for example, Clang turning [lj_math_random_step](https://github.com/LuaJIT/LuaJIT/blob/f50bf7585a32738c4fb719cb8fc59d02231fc8c3/src/lib_math.c#L120) into vectorised AVX2 instructions).

In general, by specifying an instruction set in your `-march` list, you're saying two things:
  1. If the C code wants to explicitly use instructions from that set, it can by including the appropriate header and calling the appropriate builtin.
  2. The C compiler is free to use instructions from that set, anywhere, for any reason.

As such, if you specify an instruction set in `-march`, don't expect your binary to run anywhere which doesn't have that instruction set. Cross-compilation is slightly more complex, in that you could if you wish specify different flags for the host-doing-the-compilation and the host-on-which-the-binary-will-run, but the same argument applies to both.

**Comment by DeadSix27** [comment]
> Why on earth are you passing an -march flag with random instruction sets in the first place?

 I'm just passing  -march=skylake and -O3, nothing else, is that random? (My target CPU is skylake and its only supposed to run on that)

On the other hand, thanks for the description as to how they actually work (a bit at least).

**Comment by iryont** [comment]
How about just ```-march=native``` instead.

**Comment by sindrom91** [comment]
If you're compiling on one machine for all of the others, you might want to use `TARGET_FLAGS` and/or `TARGET_CFLAGS` instead of just `CFLAGS`.

**Comment by DeadSix27** [comment]
@sindrom91 TARGET_CFLAGS I should use indeed, never thought of those, also doesn't "native" use the host? E.g cross compiling on amd-ryzen (for skylake) it would use znver1 ?

**Comment by iryont** [comment]
It does use the host as reference, but since you said you want to use it on a specific CPU then it should be compiled on a target machine instead.

You are specifying instruction set which will only work on certain CPUs, so you simply cannot expect it to work for every CPU.

There is nothing to talk about to be honest. Either compile the code with generic instruction set + some extended ones (e.g. SSE2) or compile it for a specific CPU (native option or provide a list of instructions available on a specific CPU considering the fact that you want to cross-compile it).

**Comment by DeadSix27** [comment]
@iryont Isn't that what I said?
> You are specifying instruction set which will only work on certain CPUs, so you simply cannot expect it to work for every CPU out there.
Either compile the code with generic instruction set + some extensions (e.g. SSE2) or compile it for a specific CPU

Yes, the one I will use it on. (skylake, which doesn't work)
Anyway, Ill just use -O3 then and ditch march.

**Comment by corsix** [comment]
> I'm just passing -march=skylake and -O3, nothing else, is that random? (My target CPU is skylake and its only supposed to run on that)

Apologies; I lined up `-march={see list below}` with the instruction set list, rather than the other lists.

> Anyway, Ill just use -O3 then and ditch march.

Or, as has been suggested, put your `-march` in `TARGET_CFLAGS` rather than in `CFLAGS` (as the latter specifies flags for both the build machine and the target machine, and apparently your build machine is older than your target machine).

**Comment by DeadSix27** [comment]
@corsix Ohhh, thats what I did not understand.... thanks for clearing that up, indeed my host is older than my target machine!
