### ISSUE TITLE
Write the JIT in Lua

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#353]
Would it be possible to write the JIT compiler in Lua?

Can a JIT written in Lua JIT itself?

**Comment by codeservice** [comment]
I think you can do this if you load jit as external library to Lua.
For example you can load sljit library and write compiler in Lua.

https://github.com/alnsn/luaSljit

**Comment by alnsn** [comment]
The author of luaSljit here.

If won't get close to a speed of JIT in LuaJIT even if you rewrite it using C API of sljit. Not all JITs are created equal.

**Comment by SoniEx2** [comment]
I want LuaJIT's JIT to be written in Lua and exposed through `require "jit"` so I can monkeypatch it and experiment with #106 without touching much C code (if any).

**Comment by codeservice** [comment]
It would be great if luajit keep logic in modules, like jit engine in one
lib and lua parser in another. In this case it would be possible use jit
engine in different projects with no relation to lua. Not sure if its
possible and any plans to do so.

On Sep 14, 2017 18:29, "Soni L." <notifications@github.com> wrote:

I want LuaJIT's JIT to be written in Lua and exposed through require "jit"
so I can monkeypatch it and experiment with #106
<https://github.com/LuaJIT/LuaJIT/issues/106> without touching much C code
(if any).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LuaJIT/LuaJIT/issues/353#issuecomment-329626504>, or mute
the thread

**Comment by jfmc** [comment]
You may have a look at the PyPy project (https://pypy.org/). Although it is for Python (not Lua) the problems are similar (AFAIK PyPy's JIT is written in Python).

**Comment by Techcable** [comment]
The LuaJIT compiler is ridiculously fast, compiling code much faster than even Java's fastest JIT, while still having better quality. Rewriting it in Lua would be a waste of effort that would signifigantly reduce performance. It wouldn't make the compiler any better either, as it already produces far better code than PyPy even though it's written in C.

The areas where the compiler produces bad code are mainly because it's a trace compiler, and the way to fix that is either [hyperblock scheduling](https://github.com/LuaJIT/LuaJIT/issues/37) or add a second 'method JIT'. I don't know if anyone ever implemented hyperblock scheduling in a production compiler, but I do know that firefox ditched their trace compiler for javascript because of the same issues with the compilation quality. However, I know that Mike Pall isn't as interested in LuaJIT so I doubt he'd be willing to personally impomewhat either of these fixes, and either way Lua wouldn't be helpful.

**Comment by SoniEx2** [comment]
I don't care so much about the speed of the interpreted JIT as much as I care about being able to experiment with it at runtime.

Also, having a JIT compile itself would be a good demo of the JIT's capabilities.

In bigger, JIT-heavy apps, the JIT would be already JITted, so performance wouldn't be a concern.

**Comment by szbnwer** [comment]
as i prefer semi-live coding (takes a ctrl+r instead of a single keydown, this makes life better) i can deeply understand this need. i also wanna understand one day all the luajit codebase, and if the same concepts are written in easy peasy lua, and being targets of instant childgames around them, that would make a lotsa goodies... however i don't think that it takes rewriting anythin inside luajit, but only a higher level implementation of it. whoever will make this project, they will achieve enlightenment on the road :D

**Comment by nico-abram** [comment]
Should this issue be closed? I don't think this really belongs as an issue. Bootstrapping doesn't make as much sense for a scripting language imho, and I don't think a request to completely rewrite a project in another language should be a valid issue.

**Comment by kirbyfan64** [comment]
It's a proposal that really isn't going to happen from practicality standpoint.
