### ISSUE TITLE
io.read('*n') bug

### ISSUE THREAD

**Issue by achan001** [LuaJIT/LuaJIT#374]
> x = 6.2e-323
> y = io.read('*n')
6.2e-323
> >
> = x, y
6.4228533959362e-323       5.928787750095e-323

**Comment by MikePall** [comment]
The number parser uses an internal function. `io.read()` uses `fscanf()`, i.e. a C library function.

I cannot reproduce this e.g. on Linux with glibc, which has a very precise implementation. It yields the same result as the internal number parser (6.4...). Which also happens to be the correct result, because it's the closest floating-point representation of the input number.

In other words: please complain to the vendor of your C library about it's inaccuracy.

**Comment by achan001** [comment]
Why not build your own fscanf (only for numbers) that reuse all the code from lj_strscan.c ?
The whole point of creating lj_strscan.c is to remove strtod dependency, which fscanf most
likely called for conversion.

**Comment by MikePall** [comment]
Good luck with providing a patch for that. The main issue is not grabbing more data from the stream as needed. Note that `ungetc()` is highly unportable and may only allow one push back.

**Comment by achan001** [comment]
if ungetc is valid to pushback max of 1 char, the same limitation apply to fscanf too
x, y = io.read('*n', '*l')
1.2exyz
= x, y
1.2     xyz     -- fscanf ALSO unable to pushback 'e'

so, a customized fscanf using lj_strscan.c is still a good idea.

FYI: gcc 7.1 (from latest strawsberry perl 5.26) still FAILED to fscanf 6.2e-323 correctly

**Comment by achan001** [comment]
just noticed gcc fscanf DOES NOT use strtod

strtod("6.2e-323", NULL) produce correct 6.4e-323 value
