### ISSUE TITLE
Get rid of NtAllocateVirtualMemory?

### ISSUE THREAD

**Issue by Xottab-DUTY** [LuaJIT/LuaJIT#419]
Can someone say to me why it's used? Why we don't just use malloc?

I know, we need to do a huge refactor, but it needs to be done. This will give us normal memory allocation without undocumented function usage.

**Comment by Necrolis** [comment]
[NtAllocateVirtualMemory](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntallocatevirtualmemory) is well documented, although its part of the WDK (not sure why the LJ source mentions it as "undocumented").

As for why `malloc` cannot be used, thats because LJ has some specific requirements when it comes to the pointers that get returned (in 64bit mode), mainly that they be within the first 2GB of addressable space; and `malloc` cannot fulfill those requirements. Please see the comments [here](https://github.com/LuaJIT/LuaJIT/blob/fb5e522fbc0750c838ef6a926b11c5d870826183/src/lj_alloc.c#L178).

**Comment by Xottab-DUTY** [comment]
Sorry, I didn't point my question clearly. I know that it uses the first 2GB. The question – why it does?

**Comment by Xottab-DUTY** [comment]
And thats why I said that we need to do a huge refactor if we want to use `malloc`.

**Comment by Laaas** [comment]
Can't you just use GC64?

**Comment by MikePall** [comment]
Use v2.1 and GC64 mode.

**Comment by Xottab-DUTY** [comment]
How to?

**Comment by MikePall** [comment]
Run:

`msvcbuild gc64`

**Comment by Xottab-DUTY** [comment]
Thank you =)
