### ISSUE TITLE
LJ_MAX_SLOTS needs to be adjusted when LJ_FR2 is enabled

### ISSUE THREAD

**Issue by sdmaclea** [LuaJIT/LuaJIT#432]
When using LJ_GC64, LJ_FR2 is enabled.  In this mode each bytecode register allocation consumes two slots.  This means in LJ_GC64 there is more slot pressure and the LJ_MAX_SLOTS needs to be increased to have the same VM capacity.

A simple definition like 
```
#define LJ_MAX_SLOTS	(250 + LJ_FR2*250)
```
may suffice.  It certainly fixed the error I saw while running the `testrep("", "a(")` test case in errors.lua in the lua 5.1 test suite on arm64 luajit 2.1 tip

**Comment by corsix** [comment]
> In this mode each bytecode register allocation consumes two slots.

This is incorrect. Function calls require two slots (plus one slot per argument) as opposed to one slot (plus one slot per argument). Nothing else requires additional slots.

In any case, `LJ_MAX_SLOTS` isn't something which can be easily increased. It is set just below 2<sup>8</sup> because of various 8-bit fields in the VM and in the bytecode format.

**Comment by sdmaclea** [comment]
You are correct.  The real issue is that `LJ_MAX_XLEVEL` is 200 which would require 200 additional slots. 
 So for LJ_FR2 the maximum nesting is about 125 levels.  Which is probably more than adequate.  

Perhaps the right answer would be to use
`#define LJ_MAX_XLEVEL	(200 >> LJ_FR2)` to get a better error message.
