### ISSUE TITLE
Android build is no more works

### ISSUE THREAD

**Issue by Wohlstand** [LuaJIT/LuaJIT#477]
Trying to compile for Android by existing way gives no result, and article needs to be updated:
* Latest Android NDK does using of CLang
* Attempt to compile REQUIRES complete multilib be installed into 64-bit system, otherwise, will not work with strong errors
* Given toolchains are now 64-bit only
* Oldest available ABI is 16

It's my attempt to compile for ARMv7 as example:
```bash
#!/bin/bash

# Android/ARM, armeabi-v7a (ARMv7 VFP)
NDK=/home/${USER}/Android/Sdk/ndk-bundle
NDKABI=16
NDKVER=$NDK/toolchains/llvm
NDKP=$NDKVER/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi$NDKABI-
NDKF="--sysroot $NDK/platforms/android-$NDKABI/arch-arm"
NDKARCH="-march=armv7-a -mfloat-abi=softfp"
make DEFAULT_CC=clang HOST_CC="clang -m32" CROSS=$NDKP TARGET_FLAGS="$NDKF $NDKARCH"
```

I think the manual here http://luajit.org/install.html is VERY outdated and needs to be actualized...

It's good that I using in my project the PUC-Rio lua as a fallback for target platforms where LuaJIT can't be built.

The question: what wrong in my script if I it's my fault?

Currently, I have error of missing `<string.h>` while building, possibly, because of missing or incorrect include path...

**Comment by Wohlstand** [comment]
Android build is completely resolving with CMake build: #476

**Comment by MikuAuahDark** [comment]
I successfully compiled LuaJIT using NDK r16b under Windows using Android ARM64 standalone toolchain. It should be even easier in Linux I guess. Here's the command-line (assume you have 64-bit GCC, Make, and aarch64-linux-android toolchain in your `PATH`):

```
make XCFLAGS="-D__ANDROID_API__=21" CROSS=aarch64-linux-android- TARGET_SYS=Linux -j4
```

And for amalgamated build, just add `amalg` after the command above.

Thing to note in here is that you have to specify `__ANDROID_API__` to correct Android API level. Otherwise it will complain about undefined reference to `stdin`, `stdout`, and `stderr`.

**Comment by Wohlstand** [comment]
However, with newer NDKs are using CLang, will fail.

**Comment by MikePall** [comment]
The documentation has been updated to work with the latest NDK.

**Comment by JCash** [comment]
I think the documentation could now be updated again, since the "gcc" doesn't exist in the NDK anymore.
