### ISSUE TITLE
Write the parser/compiler in Lua

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#488]
Rather than having the parser in C, write the parser in (pure-)Lua and run it against itself to produce a bytecode blob. Embed this resulting bytecode to provide the parser. This bytecode could then be trivially removed in specialized applications to make the runtime lighter. Additionally, this parser can be JIT-compiled and yielded through.

**Comment by Elronnd** [comment]
> Embed this resulting bytecode to provide the parser

Echhhh, that sounds ugly and error-prone.  I can understand the desire to make compilers bootstrap, but it doesn't *really* work unless they can compile to native code.  (Something like rpython/pypy could work, but I doubt anyone wants to take the work to make that happen.)

**Comment by SoniEx2** [comment]
The bytecode version and the LuaJIT version go hand-in-hand, so it's safe to embed a bytecode-based load()/lua_load(). As such, it's no more error-prone than having a bytecode compiler in the first place (which we do). We also already embed bytecode: https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/host/buildvm_libbc.h

**Comment by capr** [comment]
I tried this for Terra[1] and it turns out that a recursive-descent parser is a very bad load for a tracing JIT (chaotic branches, low iteration counts). Makes sense in hindsight since code has high entropy almost by definition. 

https://github.com/luapower/lx (lexer kept in C, parser in Lua)

**Comment by SoniEx2** [comment]
hey, if you can drop the FFI requirements (solve the bootstrapping problem, allow it to bootstrap from plain Lua) then that'd be nice. (it'd also be more useful to me)

otoh, rather than branching on your own (with if/else etc), have you tried something a little more... declarative? it might be better for LuaJIT. see: https://cybre.tech/SoniEx2/lua.cratera

**Comment by SoniEx2** [comment]
(in any case, it's not like the JIT really matters - code loading generally isn't something that happens often, usually limited to initialization.)

**Comment by SuperUserNameMan** [comment]
isn't this project already do that ??
https://github.com/franko/luajit-lang-toolkit

**Comment by exikyut** [comment]
Hi. Learning [about] Lua at the moment. :) Stumbled on this discussion while idly leafing through RaptorJIT's issue tracker (https://github.com/raptorjit/raptorjit/issues/248), and it got me thinking.

Crazy/wild/possibly-exponentially-bad idea: I can't help but wonder if a fully plumbed-out implementation of a feature like this would by design also make it possible to *extend* the language parser to support new syntax.

Also, there's this. You talk of instantiating and running blob compiler at bootstrap time. This is an excellent MVP, but if it were made possible to

- perform additional compilation steps *after* the initial bootstrap phase,
- rewire the compiler's behavior at runtime, and
- run source/input scans *before* the full tokenizer runs, looking for blob-loading instructions and executing them immediately as they are found

you'd be able to (re)define the language at runtime from a single script. LuaJIT could look like any language you wanted.

Want `{` and `}` to do the same thing as `do` and `end`? Imagine LuaJIT allowing you to do that by just adding some Lua to the top of a file. `{`/`}` doesn't work before this snippet, but it magically does immediately afterward.

The best part of all of this is that all of the code making this happen would only ever be happening at load time and during `eval()`. This eliminates a large proportion of performance/efficiency pressure.

A related idea: if you put this compiler *after* or *inside* the sandbox mechanism, when you create new sandboxes they'll have no parsers in them, and the code outside the sandbox could load a super-minimal compiler. If such a compiler only implemented variable handling and `=`, for example, you now have a great little secure option parser that *does not implement any of the syntax required to go and load more bytecode.* But you could also implement a mechanism that permanently disables compilation for that sandbox.

**Comment by szbnwer** [comment]
hi there! :)

`{}` is for tables, that are really fundamental in lua, and the syntax of lua is really deeply considered and hard to modify it without wrecking an actually nice language, and i think that the intention to change the syntax is a typical newbie-gotcha. on the other hand, there is a bunch of lua dialects out there with more-or-less hacked syntax, so its not impossible nor a plain-crazy thing to think about... personally i think that the important point is the abilities that a language has, and (mostly) not the way a programmer should write codes against it... theres something like intention oriented progamming paradigm (or whatever like, look after Charles Simonyi for getting an entry point into this world, but u wont find much about his stuffs, just the terminology can guide u forward in the topic) and dsl (=domain specific language if i say it right) that is an important keyword there as well. otherwise smalltalk has the ability to hack everything around it in runtime as the syntax elements are just plain hackable objects as everything there... smalltalk has many dialects as well, as the original smalltalk seems to be dead cuz of performance issues or what else... (check out the tools behind "studio" for raptorjit (maybe its called to be glamorous toolkit), and u8, that i know about) i think lua is hackable more than enough, and luajit with ffi and dynasm pushes that much further ... if we consider the abilities instead of the syntax... u can overload anything with any custom stuff u want, u can load whatever u want, and u can integrate tcc or whatever else to write compile link and run whatever in runtime, but i think thats not this much simple, as ffi is "unidirectional" as far as i know, so u can load but cant unload stuffs with ffi... that could be an actual feature that i wish for, but possibly it can be challenging. (note that actually u dont strictly need to integrate anything as external tools can do the trick just as well, and there is an interesting stuff somewhere on github, search for non-euclidean game (or whatever, ive seen it on youtube 1st), it integrates tcc on an interesting manner, but i consider it as its on a poc level (read as kinda limited).) personally i suggest u to deep dive into the internals of lua and luajit, and that will reorganize ur thoughts, and u will see that luajit is actually a miracle in itself with all those hacks that it has, and the important bit about this is that it has incredibly high cohesion in its sources, and actually that gives it all of its power greatness and beauty, and that is a reason to dont wish it to become something completely alienated from itself ... but the vm can be reused in itself, so such syntax hacking stuffs are possible as far as i know, and mostly it wont lose all of its greatness, so feel free to go deeper! :D and also, i would like to suggest u to play with `load`/`loadstring`/`loadfile`/`package.loadlib` to get a better direction about runtime hacking (i also play that game, ive got a graphical app where i can edit the sauces on a live-coding manner, and live-patch anything i want, and save whatever i like from my experiments, while i think that i could do anything even in runtime with my tools, but in the sense of functionality/appearance/whatever, but not syntax, or even that if i translate it to lua, like how moonscript does it, but im not really familiar with it. btw my project is currently private, but u will find it under the name Szoszi in the future, and nope, i cant predict the time for it :D )

actually whats ur main goal? having an ultimately hackable tool is worthless without utilizing it for anything serious... in that case u can write whatever u want in br*infuck and have it with the same amount of effort behind the actual result.

all the bests, have fun! :)

**Comment by exikyut** [comment]
ooh, a wall of text \**dives in*\*

> i think that the intention to change the syntax is a typical newbie-gotcha.

I agree. `{` and `}` make for a single poor example, admittedly ;) and one that is driven by my current (also poor) text editor's inability to auto-indent as I type `do` and `end`.

Hmm. Now I think about it, the parser would have to do a bit of extra work to discern between data list context and code scope context. Something JavaScript seems to do just fine, the question does remain - how many extra LOC would be needed...

> there is a bunch of lua dialects out there with more-or-less hacked syntax, so its not impossible nor a plain-crazy thing to think about

Cool, okay.

And this is what I was getting at with my hazy/hand-wavy thinking: make what must currently be done in C, possible to also do in Lua.

Suddenly you'd go from

- needing to modify C code - possible, but not for everyone (I don't mind it but find C's terseness a mild strain)
- needing to *fork the entire repo because you just modified the language itself*, and then come up with a new name for your fork, and then have it be subjected to critique and review, and in only a few circumstances (internal tooling, popularity, etc) have the result be used by more than a few people

to

- being able to add new syntax by writing Lua code 
- iterating really quickly since you don't have to worry about C
- being able to (in the case of widespread adoption) upload your compiler to a package manager

which could be interesting.

> personally i think that the important point is the abilities that a language has, and (mostly) not the way a programmer should write codes against it...

I specifically disagree.

But annoyingly, I can't find this article I'm looking for that conveys the point I want to make, I've been trying to find it for about 30-45 minutes now :( (the HDD with my bookmarks on it is currently inaccessible, yay).

It was describing how when the K programming language (as used in Kdb+) was taught to first-year students back in the 1980s, the students were able to fully grasp extremely complex computer-science constructs that had taken weeks (if not months) of classes full of hours-long blackboard explanations to convey the same ideas in COBOL or FORTRAN (I forget which).

K is in quite a different league to COBOL/FORTRAN, but it does seem that the language's syntax has a lot to do with its ability to allow you to program at a seemingly more efficient level of abstraction.

> theres something like intention oriented progamming paradigm (or whatever like, look after Charles Simonyi for getting an entry point into this world, but u wont find much about his stuffs, just the terminology can guide u forward in the topic)

Ah, https://en.wikipedia.org/wiki/Intentional_programming.

Hmm, yeah, this doesn't seem particularly scaffolded-out. But very interesting nonetheless! Thanks for the term, didn't know it before :D

> and dsl (=domain specific language if i say it right) that is an important keyword there as well. 

Yes - what I'm describing is essentially the ability to, with realistic restrictions, modify LuaJIT's DSL at runtime. I tried to figure out where to cram the term into my initial comment but couldn't find a spot. Heh.

> otherwise smalltalk has the ability to hack everything around it in runtime as the syntax elements are just plain hackable objects as everything there... smalltalk has many dialects as well, as the original smalltalk seems to be dead cuz of performance issues or what else...

Hmm, I've looked at Smalltalk a few times over the years. Also looked at the Oberon system as well. I must admit I can't get much out of either: videos on the subject have my eyes glazed over in seconds, and if I try and use them myself I feel I have to give the system *too much* input (more input than I'm comfortable with) to have it do what I want. Either this means it's a bit beyond my attention span, or there are some intuitivity/accessibility issues with the way such systems present themselves.

> (check out the tools behind "studio" for raptorjit (maybe its called to be glamorous toolkit), and u8, that i know about)

I actually watched https://www.youtube.com/watch?v=MQyxXSPXcwg last night, haha. That seems interesting as well, if not quite general-purpose (yet?).

> i think lua is hackable more than enough,

\**continues learning*\*

> and luajit with ffi and dynasm pushes that much further ...

I definitely agree. IMHO PHP's recent decision to use DynASM for the FFI engine was a refreshingly solid piece of engineering decisionmaking.

> if we consider the abilities instead of the syntax... u can overload anything with any custom stuff u want,

\**implements aforementioned ideas*\* :D

> u can load whatever u want,

\**ports the last frame of https://xkcd.com/413/ to Lua*\*

(OK, in all seriousness - I know that what you're describing can only be applied up to a point)

> and u can integrate tcc or whatever else to write compile link and run whatever in runtime,

...oh, huh. That's interesting. But why on earth would I want to do that, when I can use C from LuaJIT'S FFI just fine? Serious question.

> but i think thats not this much simple, as ffi is "unidirectional" as far as i know, so u can load but cant unload stuffs with ffi...

Ah.

> that could be an actual feature that i wish for, but possibly it can be challenging.

...Wouldn't you just need to make absolutely sure GC has cleaned up all the references, then free the memory?

> (note that actually u dont strictly need to integrate anything as external tools can do the trick just as well, and there is an interesting stuff somewhere on github, search for non-euclidean game (or whatever, ive seen it on youtube 1st), it integrates tcc on an interesting manner, but i consider it as its on a poc level (read as kinda limited).)

This? https://github.com/cnlohr/noeuclid

It mentions tcc, but not Lua. (Took me a bit to stop looking for Lua-related projects, heh.)

> personally i suggest u to deep dive into the internals of lua and luajit, and that will reorganize ur thoughts, and u will see that luajit is actually a miracle in itself with all those hacks that it has, and the important bit about this is that it has incredibly high cohesion in its sources, and actually that gives it all of its power greatness and beauty, and that is a reason to dont wish it to become something completely alienated from itself ...

Okay. I can't deny that this is very good advice :)

> but the vm can be reused in itself, so such syntax hacking stuffs are possible as far as i know, and mostly it wont lose all of its greatness, so feel free to go deeper! :D

I've heard that the rewritten LuaJIT VM was optimized around the way Lua works, and that while there's nothing stopping you from feeding the JIT non-Lua-idiomatic input, the result isn't guaranteed to be efficient/optimal.

> and also, i would like to suggest u to play with load/loadstring/loadfile/package.loadlib to get a better direction about runtime hacking (i also play that game, ive got a graphical app where i can edit the sauces on a live-coding manner, and live-patch anything i want, and save whatever i like from my experiments,

Cooool.

How do you handle the problems of state (re)initialization?

(Hmm, this makes me wonder about VM state snapshot/restore. That would be a pretty interesting idea. ...and now I realize that any objects referenced outside the VM that change after the snapshot would do bad things to the next resumed state. Heheh.)

Related, how do you handle updating between versions? Eg, you have some running code, then you change the contents of a table or two - how do you handle this?

Say I have an app that puts a window on the screen, and on reload I can clear the contents of the window (possibly by just drawing a white box over it, possibly also by emptying a widget tree), but the window itself stays on the screen so it's not constantly appearing/disappearing and stealing focus etc.

Now say I realize I need to change the code that's keeping the window on the screen, maybe to add a new entry in a table to let me set the window's maximum and minimum height, or to change whether the titlebar has minimize/maximize buttons (assuming a Win32-specific example would be most relevant).

How would you handle this kind of upgrde-in-place problem? The only way I know to handle this kind of thing is to basically `^C` and start again, and try and build out these parts of the code so they don't need touching often, if at all.

> while i think that i could do anything even in runtime with my tools, but in the sense of functionality/appearance/whatever, but not syntax, or even that if i translate it to lua, like how moonscript does it, but im not really familiar with it.

Ok. <sup><sub>(I don't really get this bit)</sub></sup>

> btw my project is currently private, but u will find it under the name Szoszi in the future, and nope, i cant predict the time for it :D )

I know what that's like. I have tons of ideas myself that I a) can see real-world impact from building and b) roughly know how to build, but finding the concentration is... hard :(

> actually whats ur main goal? having an ultimately hackable tool is worthless without utilizing it for anything serious... in that case u can write whatever u want in br*infuck and have it with the same amount of effort behind the actual result.

Ha. This one took far longer than I would have liked for me to figure out/realize. Totally agree.

Well, in terms of the idea I've suggested above, it's deliberately open-ended and vague because a) I admittedly don't (yet) know how LuaJIT works and I didn't want to project too much "it probably works this way" because I knew I'd likely be wrong, and b) because I'm not sure if such an idea is worth pursuing, so I added a minimally-viable level of detail.

In terms of Lua in general, I'm currently looking at different extension languages to build into a simple project (a semi-pointless one, intended to advance my understanding of programming), which I want to keep reasonably cross-platform. Currently making a really hard decision about whether to use LuaJIT or one of the other embedding-friendly languages and then have to port that to WASM so I can run in-browser, or punt and just use QuickJS.

But right now I unexpectedly decided the other day to rewrite the script that generates my `i3` statusbar output from Awk to LuaJIT, partially because the clock kept stopping (!!!) and partially because it was utterly unmaintainable and I wanted to add some new features. I must say, the ability to go "oh, LuaJIT doesn't have feature X" and then just make feature X exist via the FFI is... very very nice. :)

Mmmmm.

> all the bests, have fun! :)

Thanks! You too. Look forward to seeing the things you're building turn up here or elsewhere at some indeterminate point in the future ;)

**Comment by szbnwer** [comment]
sorry everyone for the amount, i tried to utilize some "[OFF]" delimiters for the more irrelevant parts :D otherwise i hope that i could write useful and interesting stuffs in general :)

[...]

> > i think that the intention to change the syntax is a typical newbie-gotcha.
> 
> I agree. `{` and `}` make for a single poor example, admittedly ;) and one that is driven by my current (also poor) text editor's inability to auto-indent as I type `do` and `end`.
> 
> Hmm. Now I think about it, the parser would have to do a bit of extra work to discern between data list context and code scope context. Something JavaScript seems to do just fine, but the question does remain - how many extra LOC would be needed...

hmm, i think u must be right :D otherwise i think its just a matter of time to find the zen about `do end` stuffs, but thats for the humans, not their editors :D

[...]

> needing to modify C code - possible, but not for everyone (I don't mind it but find C's terseness a mild strain)

then you will enjoy the blackmagic of luajit :D

> needing to _fork the entire repo because you just modified the language itself_, and then come up with a new name for your fork, and then have it be subjected to critique and review, and in only a few circumstances (internal tooling, popularity, etc) have the result be used by more than a few people

[...]

if something is asking for changing of the language itself, and it is really useful, then u can still send a pull request instead of making a new language (btw luajit is currently standing in one place and moonjit tries to bring it forward, so check that out if u havent done that already). otherwise u have all the tools to make anything nice upon the existing funds. bottlenecks can be handled via ffi and dynasm, abilities can be added via modules, but the language has a kinda strict pathway, so useful extensions are the things that can go inside, like a c preprocessor, that is actually a bad example, cuz that can be done without adding anything to the language itself and that is actually already done (its name is lcpp if im right, but i think i disliked its code base, so considered it as a possible resource only :D otherwise it has nice features if im right, but ive seen it too much before yesterday to be wise enough about it :D ) so i think u would only need to fork luajit if u would really want to reshape it, but ask urself 1st about ur usecase! :D

other than that, if u wanna experiment with the language itself, then u can experiment with plain lua, with much more simple internals, but i think the best approach is to plan & act instead of randomly experimenting by not knowing where u will go :D its better to leave those parts to the application domain... :D even if there u can find urself facing with walls, but yep, that takes even more planning from the very beginning!! :D

> > personally i think that the important point is the abilities that a language has, and (mostly) not the way a programmer should write codes against it...

[...]

> It was describing how when the K programming language (as used in Kdb+) was taught to first-year students back in the 1980s, the students were able to fully grasp extremely complex computer-science constructs that had taken weeks (if not months) of classes full of hours-long blackboard explanations to convey the same ideas in COBOL or FORTRAN (I forget which).

[...]

thats interesting, but apl and its dialects are somewhat like bf (i wrote some bf myself from my app :D ), so try to write something not so trivial in apl or k, leave it behind for 3 months and figure out what have u done there :D it can be efficitent, but not really human-friendly, and actually u can implement such behavior on top of any languages... u can even make a small regexp-like language for it that will be translated to predefined functions and whatever, or use functions with 2-3chars long names and chain them as u like it if u hate to type :D and this is the point where u can find ur zen. u can make a language upon lua that is actually started as lua, and then u can modify it, and if u like it, then u can try to implement it in c. :D

[...]

> Yes - what I'm describing is essentially the ability to, with realistic restrictions, modify LuaJIT's DSL at runtime. I tried to figure out where to cram the term into my initial comment but couldn't find a spot. Heh.

i think actually u dont want it that much :D dsl's are about special problem-domains, give each of them a new language that can take good care of that domain, but limit the all-over capabilities of that language, and that alienates them from each others... now u have small islands where u just killed the reusability of ur codes, and u must change ur mindset for touching one after an another, but u can handle the domains really fast in themselves...

[OFF]
[...] (smalltalk, studio, u8 and oberon stuffs)

ive mentioned smalltalk cuz of hackability, and yep, it is hard to digest it to me just as well, therefore ive mentioned studio, but not studio is the important bit, but the toolkit behind it, that has way more digestable sauces than u8 and smalltalk to me... check out the sauce of studio, and look up the toolkit that it uses, if ur interested in them. ive met with u8 on lua-l, my only current hint to find it is that the name of its author is Alejandro, and i had a long (also somewhat offtopic, sorry others! :D ) conversation with him there about the ideas behind his stuff and my stuff, if u find that, u can get some tasty mental food from both of us that i think is related to ur interests! :D ive also seen oberon, and it caught my attention as well, but i dont really remember to its details, but there are many nice stuffs out there that can be considered to be real gems, but those that gone too far from the safe coast have mostly shrunk in the space-time continuum :D some pointers that u may like to look up: templeos, nextstep (ive seen a good intro on youtube, but its hard to find good materials about it, and gnustep didnt give me any good feelings), luna (not related to lua, its based on haskell, but somewhat similar to my actual intentions), whatever graph based and graphical programming engines, and again, go to youtube and try to search for something like "future programming languages", and check out various programming paradigms as well. otherwise whenever i see such gems i basically think that they will be good for resources and bookmark them or save their sauces, instead of trying to jump from one island to an another, as ive really made my research when ive chose lua back in time! :D and still, i couldnt find any better common ground to build all my dreams on, but im checking out everything that could be interesting... btw many of such gems are collected via my github stars (there are so many reasons behind them) but good luck with them, there are really much of them... :D
[/OFF]

[...]

> > and u can integrate tcc or whatever else to write compile link and run whatever in runtime,
> 
> ...oh, huh. That's interesting. But why on earth would I want to do that, when I can use C from LuaJIT's FFI just fine? Serious question.

cuz ffi cant handle function bodies, but only their signatures, and the rest will come via a shared object that u can load... tcc can make ur shared objects, it can be used as a library, so u can use ffi to integrate tcc (lua[jit]-tcc, i dunno these projects in details, but they exists :D ) feed it good old plaintext sauces and link the results and apply whatever hack u want so in the meantime :D

> > but i think thats not this much simple, as ffi is "unidirectional" as far as i know, so u can load but cant unload stuffs with ffi...
> 
> Ah.
> 
> > that could be an actual feature that i wish for, but possibly it can be challenging.
> 
> ...Wouldn't you just need to make absolutely sure GC has cleaned up all the references, then free the memory?

i dunno the right answer, ive just read it around, i think Mike wrote about it in details on the lj mailing list, but it will be something about internalization of them, and most likely Mike considered this before he didnt implement that feature, but hopefully (and if im right) its cuz challenging, and not cuz impossible :D (maybe just the lack of need from enough serious players around)

[...]

[OFF]
> This? https://github.com/cnlohr/noeuclid

[...]

yep :D

[...]

> How do you handle the problems of state (re)initialization?

[...]

> Related, how do you handle updating between versions? Eg, you have some running code, then you change the contents of a table or two - how do you handle this?

im separating things like functions, config-like data and runtime data; then i serialize the config-like data, and everything can be initialized from that, while it can be saved when it is changed :D the codes are at two places currently* one called to be "core" and the other is "lab", core is loaded when i start the app, lab is where i experiment with things, and i can move chunks between these two. i can run multiple instances, either the current codebase or a modified one (the latter means that i edit the core and run that from the app and that will be a new instance, so i can test that way, and when there is an error, then i give back that error in the original instance and dont let to finalize stuff that cant run). the lab is for the real live-coding, where i modify the actual instance in place without starting a new instance, so i need sometimes to reset things and whatever like that. live-patching simply means that i overload whatever in `_G` or add anything new, or modify the gui or whatever... i use tekui for the latter, it can really do anything in runtime with the interface. both core and lab has 2 places to save, one is called to be "save" and the other is "history", both contains timestamped files, those are the "versions". core is loaded from save, but gives the text from the history, so i can play with it before i make things permanent, and i can play with the modifications via running a new instance from inside, while lab uses the save directory only to keep its past. save is populated manually, and history is made automatically before running anything, so in case of a crash (hard to reach that :D ) i wont lose data, and the history is rotated, so currently its set to keep the last 50 tries.

[*]: currently im about to reorganize my stuffs as i have the necessary tools, the new base is a graph where nodes will contain other nodes and node specific stuffs like conf, runtime data, general serializable data (like list of lua keywords, character names and whatever i want), codes, docs, self-tests, bidirectional dependencies (for automatized reorganization of the nodes :D ; and maybe anything that i forgot about right now) and the nodes can fallback to eachother and this is also the fund of my menu. so this way i will be able to make run targets, so i can have this mostly ide-like stuff, a server, any cli utils, any other gui apps, and whatever i can just imagine, all on the same codeb ase without making a bloatware, and without the need to reimplement everything to a new app and a new language :D and yep, its not an oop approach :D its something like a mix of procedural and functional programming, and the data is strictly isolated from the functions, cuz of the serialization :D otherwise ive seen a solution after ive found mine, that simply used a json conf inside the objects, so oop could be used, but i generally dont like oop :D i also dont use metatables, cuz of serialization, and its just hiding details, and makes no much real difference...

btw i can use factories for making custom and similar callbacks, so i can serialize the data that is necessary to make them, but not the functions, and simple serializable data can be obtained on every change of the gui, so i can save things like metrics and whatever i just want :D (if u wanna see really overengineered stuffs with similar ideas behind, u can check out the sauce of visual studio code (that ive seen only recently :D ))
[/OFF]

> > while i think that i could do anything even in runtime with my tools, but in the sense of functionality/appearance/whatever, but not syntax, or even that if i translate it to lua, like how moonscript does it, but im not really familiar with it.
> 
> Ok. (I don't really get this bit)

(if im right) moonscript is a dialect of lua with modified syntax, and it translates to lua, similar to coffeescript and javascript

[...]

[OFF]
> I know what that's like. I have tons of ideas myself that I a) can see real-world impact from building and b) roughly know how to build, but finding the concentration is... hard :(

take notes, plan ahead, make ur funds, (or wait for Szoszi, but that can actually be really much time :D ) and start to make ur gems :)
[/OFF]

[...] - your use cases (and other stuffs)

fine, but why u wanna reshape luajit for them? :D 

[OFF]
i was totally thinking about that u r aboutta searching for the programming holy grail that will solve all the problems when u wish for that :D or i still think thats one of ur actual motivations, as we have too much of our backgrounds in common. otherwise this thought exchange probably went somewhat offtopic, and i dunno what the rest of the folks will feel after all, and i think i could already let out the ontopic bits from my head, but we have really intererestings stuffs around, so i would like to suggest to continue it elsewhere, or the ontopic stuffs can come here, and if anyone is interested in anything more or less related, then i will still be around :D so if u think so, then u can add @gmail.com after my username and ping me there :D
[/OFF]

bests! :)
