### ISSUE TITLE
Infinite loop on table lookup

### ISSUE THREAD

**Issue by jdesgats** [LuaJIT/LuaJIT#494]
We found a rare bug that causes infinite loops on table lookups because the nodes in the linked lists sometimes form a loop (or even reference themselves).

It took me quite a while to narrow down the issue, so far I came up with a sample script (see below) that ends up stalling after a few hours or less on the more lucky cases (run many instances at the same time to get issues quicker).

When a stall occurs, we can see that with gdb on a hash lookup:
![image](https://user-images.githubusercontent.com/849031/56675976-37a22e00-66b5-11e9-95de-6b7ed4497bc1.png)

In the above case it loops over 3 nodes, but the most common case I've seen was a self-referencing node. After adding a few asserts in `lj_tab_newkey`, I've seen that it has been introduced by the last commit (046129dbdda526) where [that path](https://github.com/LuaJIT/LuaJIT/blob/046129dbdda5261c1b17469a2895a113d14c070a/src/lj_tab.c#L474) sometimes created loops when `mn == nn` (or with more steps in the loop).

After that I have to admit I don't understand the LuaJIT source code well enough to find a more consistent test case, or fix that issue, but I hope it helps.

```lua
-- luajit hashstress-nolru.lua [<SIZE> [<ROTATE RATE>]]

local STRING_LEN = 64
local CHARS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ '\""
local SIZE = arg[1] and assert(tonumber(arg[1]), string.format("wrong size: %s", arg[1])) or 20000
local ROTATE = arg[2] and assert(tonumber(arg[2])) or 0.5
assert(ROTATE and ROTATE >= 0 and ROTATE <= 1, string.format("wrong rate: %s", arg[2]))

-- this array will store all current strings
local ALL_STRINGS = {}

-- maps strings to random numbers, this is where (supposedly) a corruption will happen eventually
local HASHMAP = {}

os.execute('echo "PID=${PPID}"') -- too lazy to mess with ffi
print(string.format("Creating %d strings... ", SIZE))

local function make_re()
   local re = {}
   for j = 1, STRING_LEN do
      local pos = math.random(#CHARS)
      re[j] = CHARS:sub(pos, pos)
   end
   return table.concat(re)
end

local function make_value()
   return math.random()
end
local function comma_value(amount)
  local formatted = amount
  while true do
    local k
    formatted, k = string.gsub(formatted, "^(-?%d+)(%d%d%d)", '%1,%2')
    if (k==0) then break end
  end
  return formatted
end

for i = 1, SIZE do
   ALL_STRINGS[i] = make_re()
end
print("done\n")

print(string.format('[%s] starting (rotate rate=%f)', os.date(), ROTATE))
for i=1, math.huge do
   local re
   if math.random() <= ROTATE then
      local rotate = math.random(SIZE)
      re = make_re()
      HASHMAP[ALL_STRINGS[rotate]] = nil
      ALL_STRINGS[rotate] = re
   else
      re = ALL_STRINGS[math.random(SIZE)]
   end

   if not HASHMAP[re] then
      HASHMAP[re] = make_value()       -- add a new one
   end

   if i % 20000 == 0 then
      -- just do something with HASHMAP so it doesn't get optimized away
      io.stdout:write(string.format("\r[%s] matched %s (%d)", os.date(), comma_value(i), #(next(HASHMAP)))):flush()
   end
end
```

```
$ git diff src/lj_tab.c 
diff --git a/src/lj_tab.c b/src/lj_tab.c
index c51666d..24a7a5d 100644
--- a/src/lj_tab.c
+++ b/src/lj_tab.c
@@ -505,6 +505,7 @@ TValue *lj_tab_newkey(lua_State *L, GCtab *t, cTValue *key)
              if (mn != freenode) {
                freenode->next = nn->next;
                nn->next = mn->next;
+                lua_assert(mn != nn);
                setmref(mn->next, nn);
              } else {
                freenode = nn;
$ ./luajit hashstress.lua
PID=27361
Creating 20000 strings...
done

[Wed Apr 24 16:45:55 2019] starting (rotate rate=0.500000)
[Wed Apr 24 16:48:59 2019] matched 63,240,000 (64)luajit: lj_tab.c:508: lj_tab_newkey: Assertion `mn != nn' failed.
Aborted (core dumped)                                      
```

**Comment by corsix** [comment]
As per https://www.freelists.org/post/luajit/Fixed-Bug-Fix-rechaining-of-pseudoresurrected-string-keys,4 , I'm of the view that `if (mn != freenode)` should be changed to `if (mn != nn)`.

**Comment by javierguerragiraldez** [comment]
After some tests, I think the best fix is to have _both_ : `if ((mn != freenode) && (mn != nn))`

**Comment by corsix** [comment]
OK, yes, I concur with that. I've also put together https://gist.github.com/corsix/1fc9b13a2dd5f3659417b62dd54d4500 which showcases the problem, and requires `if ((mn != freenode) && (mn != nn))` in order to run to completion. What follows is a very long description of what is going on.

-----

First, some background on hash tables in LuaJIT. A hash table is an array of nodes, and each node consists of a key, a value, and a next node pointer. A node can be in one of three states:
<table><tr><th>State Name</th><th>key</th><th>value</th></tr>
<tr><td>Free</td><td>nil</td><td>nil</td></tr>
<tr><td>Dead</td><td>not nil</td><td>nil</td></tr>
<tr><td>Alive</td><td>not nil</td><td>not nil</td></tr></table>

To start with, every node is free. As keys get inserted, nodes transition from free to alive. If, subsequently, keys get removed (by assigning `nil` to their value), then nodes transition from alive to dead. Crucially, when a node transitions from alive to dead, its key is left unchanged. This crucial observation gets some discussion in `lj_obj.h`:
```
** Note: In contrast to Lua's GC, LuaJIT's GC does *not* specially mark
** dead keys in tables. The reference is left in, but it's guaranteed to
** be never dereferenced as long as the value is nil. It's ok if the key is
** freed or if any object subsequently gets the same address.
**
** Not destroying dead keys helps to keep key hash slots stable. This avoids
** specialization back-off for HREFK when a value flips between nil and
** non-nil and the GC gets in the way. It also allows safely hoisting
** HREF/HREFK across GC steps. Dead keys are only removed if a table is
** resized (i.e. by NEWREF) and xREF must not be CSEd across a resize.
```
Once a table contains some dead nodes, subsequent insertions might transition a node from free to alive, or they might transition a node from dead to alive. If the key in the dead node is equal to the key being inserted, then this transition from dead to alive is referred to as resurrection.

Given a particular table, every potential key has a so-called main node within that table (which is just the node whose index in the array is the hash code of the key modulo the capacity of the table). In the ideal case, every key in a particular table will exist in its main node. However, if there are hash collisions, then there could be multiple keys in the same table which all want the same main node. In this scenario, the next node pointers come into play, and we get the first hash table invariant:
  * If a particular key exists in a table, then the node containing that key can be found by starting at the main node for that key, and then following the next node pointer zero or more times.

The logic for assigning (or inserting) into a table consists of:
  1. Look at the main node for the key. If this node has the right key, return this node (this might be a resurrection). Otherwise:
  2. If the main node has a next node pointer, look at that node. If that node has the right key, return that node (this might be a resurrection). Continue following the next node pointers in turn and considering them, until there are no more. If none of them contained the key then:
  3. If the main node for the key is empty, return the main node. Otherwise:
  4. If the main node for the key is dead, return the main node (this will not be a resurrection, despite being a transition from dead to alive, as the key will change). Otherwise:
  5. If a free node can be found, transition that node from free to alive (not a resurrection), and do some stuff with that node. Otherwise:
  6. Resize the table and try again from step 1.

The "stuff" in step 5 is not entirely trivial, and we'll get to it in a bit.

Changing tack slightly, we can define the predecessor of a node N to be the node P whose next node pointer is N. Then we get the second hash table invariant:
  * A node has at most one predecessor.

We can also rephrase the first hash table invariant in terms of predecessors:
  * Given an alive node, the main node for that alive node's key will be one of that alive node's (transitive reflexive) predecessors. [NB: "transitive reflexive" is a fancy way of saying "walk back through the predecessor zero or more times"]

With that rephrasing in mind, I'm going to pull the third hash table invariant out of thin air, which is basically an optimisation called "Brent's variation":
  * Given an alive node, if the key in that node is not a string, then the main node for that key will be the sole transitive reflexive predecessor which does not have any further predecessor. [NB: again, fancy terminology meaning "walk back through the predecessor as many times as you can - which might be zero times - until there is no more predecessor to walk through"]

Why are strings special? We'll get to that in a bit. For now, we go back to step 5 of the insertion algorithm.

So, step 5. We have some `key` we're trying to insert. Let `n` be the main node of `key`. By virtue of steps 3 and 4, `n` will be alive. Let `collide` be the main node of `n`'s key (so by the first invariant we have `collide -> ... -> n`). Let `freenode` be some free node. Let `nn` be the next node of `n`. So, in summary, we have `collide -> ... -> n -> nn -> ...` and `freenode`. In order to satisfy the first hash table invariant, we need to end up in a state whereby starting at `n` and following the next node pointers will lead us to a node containing `key`. One way of doing this would be to put `key` into `freenode` and then twiddle next node pointers to give `collide -> ... -> n -> freenode -> nn -> ...`. If `collide` is `n`, then we can do this without any problems. However, if `collide` is not `n`, then we might be breaking the third invariant by doing this, as `n` (the main node of `key`, that is, `freenode`'s key) would have a predecessor. Therefore, if `collide` is not `n`, we do something different: we copy `n`'s key and value and next node pointer over to `freenode`, find the predecessor of `n` and change its next node pointer from `n` to `freenode`, and then put `key` into `n`. This leaves us with `collide -> ... -> freenode -> nn -> ...` and `n`. This satisfies the second invariant with respect to `n` (and with respect to `freenode` and all its transitive predecessors), but we also need to think about `nn -> ...` - these nodes no longer have `n` as a transitive predecessor, and what if `n` was the main node for something in `nn -> ...`? By the third invariant, nodes in `nn -> ...` could only have `n` as their main node if they have string keys. Hence we walk through `nn -> ...` looking for nodes with string keys and `n` as their main node, and do "something" to fix them up.

Before 046129dbdda5261c1b17469a2895a113d14c070a, this "something" was to move such nodes over to the new chain starting at `n`. As described in that commit message, this "something" is insufficient, as once the new chain has more than one node in it, what we need to look for in `nn -> ...` changes: we're now looking for nodes with string keys with anything from the new chain as their main node (this was really the condition all along, but it seemed a lot simpler when the new chain consisted of just `n`). As we're walking the old chain, we have `freenode -> nn -> ...`, and let `mn` be the main node of `nn`. If `freenode` is `mn`, then `nn`'s main node is in the old chain. Likewise, if `nn` is `mn`, then `nn`'s main node is in the old chain. Otherwise, `nn`'s main node _might_ be in the new chain (or _might_ be in the old chain), so we do the conservative thing of re-linking it onto whatever the correct chain is (amusingly, though we don't easily know which of the two chains is correct, re-linking it onto the correct chain is easy).

That wraps up step 5, meaning that we can now return to the question of why strings are special.

Types in Lua are either value types or reference types. Value types have a value, and their hash code is based on their value. Reference types have an address, and their hash code is based on their address. Strings straddle this boundary; they have an address, but their hash code is based on their value. This has some nice consequences for determinism, but has a funky interaction with resurrection, and can lead to so-called pseudo-resurrection. Namely, suppose we:
  1. Create some string `a`.
  2. Do `t[a] = true` for some table `t`.
  3. Do `t[a] = nil`.
  4. Remove all other references to `a`, and wait for `a` to be garbage collected.
  5. Create some new string `b`, which just happens to get the same address as `a` used to have.
  6. Do `t[b] = true`.

If we're (un)lucky, then in step 6, we might find the dead node which previously contained `a`, and transition it back to alive to contain `b` (c.f. `It's ok if ... any object subsequently gets the same address` from the `lj_obj.h` comment). This behaves just like a resurrection, in that it happens at step 1 or step 2 of the insert algorithm, but crucially the resurrected node might come back to life with a different hash code (because even though `a` and `b` had the same address, their values - and therefore their string hash codes - might be different).

Steps 4 and 5 in the above are what makes this really fiddly to reproduce. In the interest of reliable reproduction, the easiest option is to cheat. As the root issue is that a given string pointer can appear to change its hash code, I'm going to cheat by reaching into a string and just changing its hash code (don't try this at home, and be aware that bugs discovered whilst cheating only count if you're sure that they could be reproduced without cheating). My cheat function will be called `str_hash`, and given a string object, returns a `uint32_t*` pointing to the hash field of that object:
```lua
local ffi = require"ffi"
ffi.cdef"char* strstr(const char*, const char*)"
local strstr = ffi.C.strstr
local cast = ffi.cast
local str_hash_offset = cast("uint32_t*", strstr("*", ""))[-2] == 1 and 3 or 2
local function str_hash(s)
  return cast("uint32_t*", strstr(s, "")) - str_hash_offset
end
```

Then prepare some strings which will be victims of cheating:
```lua
local victims = {}
for c in ("abcdef"):gmatch"." do
  local v = c .. "{09add58a-13a4-44e0-a52c-d44d0f9b2b95}"
  victims[c] = v
end
```

With these things in hand, we can start by forcing a bunch of hash collisions:
```lua
  for k, v in pairs(victims) do
    str_hash(v)[0] = 0
  end
```

These collisions can be used to construct a nice long chain of nodes:
```lua
  local t = table.new(0, 8)
  -- Make chain a -> b -> c -> d, all with a as their main node
  t[victims.a] = true
  t[victims.d] = true
  t[victims.c] = true
  t[victims.b] = true
```

Then we can employ the cheat some more to change hash codes around. The assignments into `t` aren't strictly required, but they prove that we aren't cheating too much (the cheat is steps 4 and 5, and the assignments are steps 3 and 6, but the step 4 relies on garbage collection which wouldn't happen if step 3 didn't happen).
```lua
  -- Change c's main to b, and d's main to c
  t[victims.d] = nil
  t[victims.c] = nil
  str_hash(victims.c)[0] = 5
  str_hash(victims.d)[0] = 6
  t[victims.c] = true
  t[victims.d] = true
```

Following this, we can insert something which causes the interesting case of the insertion algorithm to fire:
```lua
  -- Insert something with b as primary
  str_hash(victims.e)[0] = 5
  t[victims.e] = true
```

At this point, if we didn't have 046129dbdda5261c1b17469a2895a113d14c070a, then we'd have messed up our hash table, and the following would fail:
```lua
  for c in ("abcde"):gmatch"." do
    assert(t[victims[c]], c)
  end
```

The subsequent two cases in my gist exercise variants of this leading to infinite loops.

**Comment by corsix** [comment]
After some more thought, I'm going to revise the third invariant to the following. If `n` is an alive node, let `main(n)` denote the main node of `n`'s key. Then:
  * For all alive nodes `n`, either `n` has a string key, or `main(n)` is dead, or `main(n)` is `main(main(n))`.

**Comment by corsix** [comment]
Nope, that invariant isn't right either. Furthermore, we have a bigger problem. Even with `if ((mn != freenode) && (mn != nn))`, the following fails, as the edge cases extend beyond strings:
```lua
for i = 0, 10 do
  local k = tonumber((("0x%xp-1074"):format(i)))
  str_hash(victims.a)[0] = 0
  str_hash(victims.b)[0] = 0
  local t = table_new(0, 4)
  -- a -> b, both with a as primary
  t[victims.a] = true
  t[victims.b] = true
  -- Change b's primary to b
  t[victims.b] = nil
  str_hash(victims.b)[0] = 3
  t[victims.b] = true
  -- Might get a -> b -> k, with k's primary as b
  -- This depends on the hash code of k, but _some_ value of i should cause it
  t[k] = true
  -- Change b's primary to a
  t[victims.b] = nil
  str_hash(victims.b)[0] = 0
  t[victims.b] = true
  -- Insert something with b as primary
  str_hash(victims.c)[0] = 3
  t[victims.c] = true
  -- Check for consistency
  assert(t[k], i)
end
```

**Comment by javierguerragiraldez** [comment]
I see.  I hadn't made the connection between dead keys and the "resurrection" term here.  Much less what could "pseudoresurrection" mean.  I assumed dead keys stayed there until rehashing, didn't realize that they could be reused.  It's much more clear now.

When we tried your first suggestion, `if (mn != nn)`, we did hit the "infinite rechaining loop" you mention.  but the "why not both" patch (`if ((mn != freenode) && (mn != nn))`) has been running for at least 50x more than any other experiment so far.  granted, in this test we're only using string keys.

If I follow you correctly, the last problem you mention is that other types could create the same kind of conflicts as strings, if they have the same hash as a dead node's key.  Is that because a dead node could be resurrected with a completely different value, even if it's not a string?  I thought the first two steps (where the resurrection might happen) are in those small loops in `lj_tab_set()`, `lj_tab_setinth()` and `lj_tab_setstr()`, all of which start by comparing the types of the input and node's keys.

Or is the problem within the rechaining tasks within `lj_tab_newkey()`?  there all these corrections begin by testing only string keys, but your last example seems to fail with numbers.  In that case, would it make sense to just remove the `tvisstr()` conditions from lines 489 and/or 503?  it looks like it could make the tasks slightly heavier, but they're already very rare to hit, so it shouldn't be a significant drag.  (and can't be worse than restarting the process!)

thanks a lot for this great walkthrough,

**Comment by jdesgats** [comment]
Wow, this is easily one of the most instructive threads I've seen on GitHub! Thanks for the detailed explanations :+1:

**Comment by corsix** [comment]
> If I follow you correctly, the last problem you mention is that other types could create the same kind of conflicts as strings, if they have the same hash as a dead node's key. Is that because a dead node could be resurrected with a completely different value, even if it's not a string?

In the scenario I posted, the non-string has the same hash as an alive node. At the time of insertion, said alive node was in its main position. The nastiness is that said alive node is later manipulated to no longer be in its main position.

> Or is the problem within the rechaining tasks within `lj_tab_newkey()`?

Yes. A plausibly correct implementation is the following, which tries to retain the `tvisstr` when possible. At the very least, it seems to handle all the cases in my (now updated) gist.

```c
/* Insert new key. Use Brent's variation to optimize the chain length. */
TValue *lj_tab_newkey(lua_State *L, GCtab *t, cTValue *key)
{
  Node *n = hashkey(t, key);
  if (!tvisnil(&n->val) || t->hmask == 0) {
    Node *nodebase = noderef(t->node);
    Node *collide, *freenode = getfreetop(t, nodebase);
    lua_assert(freenode >= nodebase && freenode <= nodebase+t->hmask+1);
    do {
      if (freenode == nodebase) {  /* No free node found? */
	rehashtab(L, t, key);  /* Rehash table. */
	return lj_tab_set(L, t, key);  /* Retry key insertion. */
      }
    } while (!tvisnil(&(--freenode)->key));
    setfreetop(t, nodebase, freenode);
    lua_assert(freenode != &G(L)->nilnode);
    collide = hashkey(t, &n->key);
    if (collide != n) {  /* Colliding node not the main node? */
      Node *nn;
      while (noderef(collide->next) != n)  /* Find predecessor. */
	collide = nextnode(collide);
      setmref(collide->next, freenode);  /* Relink chain. */
      /* Copy colliding node into free node and free main node. */
      freenode->val = n->val;
      freenode->key = n->key;
      freenode->next = n->next;
      setmref(n->next, NULL);
      setnilV(&n->val);
      /*
      ** Nodes after n might have n as their main node, and need rechaining
      ** back onto n. We make use of the following property of tables: for all
      ** nodes m, at least one of the following four statements is true:
      **  1. tvisnil(&m->key)  NB: tvisnil(&m->val) is a stronger statement
      **  2. tvisstr(&m->key)
      **  3. tvisstr(&main(m)->key)
      **  4. main(m) == main(main(m))
      ** Initially, we need to rechain any nn which has main(nn) == n. As
      ** main(n) != n (because collide != n earlier), main(nn) == n requires
      ** either statement 2 or statement 3 to be true about nn.
      */
      if (!tvisstr(&n->key)) {
	/* Statement 3 is not true, so only need to consider string keys. */
	while ((nn = nextnode(freenode))) {
	  if (tvisstr(&nn->key) && !tvisnil(&nn->val) &&
	      hashstr(t, strV(&nn->key)) == n) {
	    goto rechain;
	  }
	}
      } else {
	/* Statement 3 is true, so need to consider all types of key. */
	while ((nn = nextnode(freenode))) {
	  if (!tvisnil(&nn->val) && hashkey(t, &nn->key) == n) {
	  rechain:
	    freenode->next = nn->next;
	    nn->next = n->next;
	    setmref(n->next, nn);
	    /*
	    ** Rechaining one node onto n creates a new dilemma: we now need
	    ** to rechain any nn which has main(nn) == n OR has main(nn) equal
	    ** to any node which has already been rechained. Furthermore, at
	    ** least one of n and n->next will have a string key, so all types
	    ** of nn key need to be considered. Rather than testing whether
	    ** main(nn) definitely _is_ in the new chain, we test whether it
	    ** might _not_ be in the old chain, and if so re-link it into
	    ** the correct chain.
	    */
	    while ((nn = nextnode(freenode))) {
	      if (!tvisnil(&nn->val)) {
		Node *mn = hashkey(t, &nn->key);
		if (mn != freenode && mn != nn) {
		  freenode->next = nn->next;
		  nn->next = mn->next;
		  setmref(mn->next, nn);
		} else {
		  freenode = nn;
		}
	      } else {
		freenode = nn;
	      }
	    }
	    break;
	  } else {
	    freenode = nn;
	  }
	}
      }
    } else {  /* Otherwise use free node. */
      setmrefr(freenode->next, n->next);  /* Insert into chain. */
      setmref(n->next, freenode);
      n = freenode;
    }
  }
  n->key.u64 = key->u64;
  if (LJ_UNLIKELY(tvismzero(&n->key)))
    n->key.u64 = 0;
  lj_gc_anybarriert(L, t);
  lua_assert(tvisnil(&n->val));
  return &n->val;
}
```

**Comment by spacewander** [comment]
@corsix 
It seems that your patch could not pass this test case: `https://github.com/LuaJIT/LuaJIT-test-cleanup/blob/master/test/sysdep/ffi_lib_c.lua`. Or maybe there is something wrong when I try to patch the LuaJIT and run the tests.

**Comment by agentzh** [comment]
Yeah, I can confirm that the latest patch breaks a lot of test files in Mike Pall's test suite: math_special.lua, sink_alloc.lua, ffi_jit_misc.lua, fwd_upval.lua, hook_top.lua, tonumber_tostring.lua, and many more.

**Comment by mejedi** [comment]
@corsix 
You work is amazing! The proposed fix forks for me (all the tests pass) after a trivial correction. I've added the missing `free_node = nn;` statement in the `while` loop below the comment that says `/* Statement 3 is not true, so only need to consider string keys. */`.

It would be nice if the comments were improved. It took me two days to fully comprehend the issue and the fix.

**Comment by corsix** [comment]
@mejedi, good spot. I've retroactively edited that missing line into the code in my earlier comment, and added the following to my gist to exercise it:
```lua
do --- Do not forget to advance freenode in the not-string case
  local t = table_new(0, 4)
  -- Chain of colliding numbers
  t[0x0p-1074] = true
  t[0x4p-1074] = true
  t[0x8p-1074] = true
  -- Steal middle node of the chain to be a main node (infinite walking loop)
  t[0x2p-1074] = true
end
```

I agree with you regarding comments; I certainly found it difficult trying to establish what invariants the hash table implementation was trying to maintain (as evidenced in my repeated attempts in this issue to find a correct formulation of the third invariant). For the benefit of anyone reading text but not code, my latest stab at the third invariant is:
  * For all nodes n, either n is free, or n has a string key, or main(n) has a string key, or main(n) is main(main(n)).

This relies on extending the definition of `main` slightly - I previously only defined it for alive nodes, but it extends to dead non-string keys in the obvious way. Notably the definition cannot extend to dead string keys, as getting the hash code of a dead string key might require dereferencing a garbage-collected pointer (in PUC-Rio Lua, the definition _can_ be extended to dead string keys, as such keys are cleared as part of garbage collection, and the `or n has a string key, or main(n) has a string key` clauses are necessary precisely because the definition cannot be extended).

**Comment by mejedi** [comment]
@corsix
>For all nodes n, either n is free, or n has a string key, or main(n) has a string key, or main(n) is main(main(n)).

Personally, I find the following equivalent statement much easier to reason about. *A list made of nodes with non-string keys is always a proper list (main doesn’t have a predecessor).*

**Comment by agentzh** [comment]
FYI, some of our users observe mysterious table key losses online with @corsix's latest patch, which might have large impact in production. Reverting that patch makes the issue go away (the first one-line patch does not seem to have this problem, at least not observable). My hunch is that the latest patch may still have important corner cases unresolved. Not sure yet.

**Comment by MikePall** [comment]
Applied my own fix. None of the mentioned fixes is correct.

**Comment by Calandiel** [comment]
Hello. I think there's a chance this bug (or at least something similar) still can happen in some edge cases.
I've been struggling with creating a reproducible sample but the behavior I observed is that a for loop over `pairs` of a large table (1 mil+ entries with integer keys) sometimes enters an infinite loop on a subset of entries, similar to what @jdesgats reported in the original post.
If I manage to make a reliable test case for what I've been observing, I'll report it here (unless a new issue would be preferred?) but perhaps it could be worth it to check the original bug report and see if there were no accidental regressions since.

**Comment by MikePall** [comment]
It's unlikely your problem has anything to do with this issue.
First, if it's all integer keys and they form an array, then you shouldn't be using `pairs`.
Second, there have been quite a few fixes for `pairs`, since it started to be compiled around ~1 year ago. The last one was just a few days ago. Upgrade to v2.1 git HEAD and try again.

**Comment by Calandiel** [comment]
Finally had some time to look into it again.
I was using pairs because the table is likely to have holes in it at some point. I was running a build from 2022-01-02. I originally posted in this issue because it was the only one reporting anything similar to what I encountered (pairs getting stuck in an infinite loop on a subset of the elements).
I ran my program again with the latest version from the repo and it does seem to have gone away (tho it's makes it difficult to verify). If I encounter it again, I'll report back.

Apologies for taking up your time!
