### ISSUE TITLE
Cannot submit PR from "legacy" Github forks

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#50]
I discovered that I cannot send Pull Requests to the `LuaJIT/luajit` repository because my existing Github forks of LuaJIT come from a different "fork network" i.e. the [`LuaDist/luajit`](https://github.com/LuaDist/luajit) mirror repo.

Looks like 68 people have forked the LuaDist/luajit repository and everybody is going to have the same problem.

Seems like a general problem on Github when there is an unofficial-but-popular mirror repository and then the canonical repository later joins under a new account.

Github support feedback:

> The only solution here would be for people to re-fork from the new canonical repository. It's unfortunate that the new canonical repository wasn't created in the same fork network as the original, which would have meant that we could change the root repository in that fork network.

The downside of that is that I need to destroy the local history of my Github forks in the process i.e. issues and pull requests. That is not the end of the world but it is a nasty surprise that others may also want to be aware of and deal with sooner rather than later.

I am looking for creative solutions... ideas welcome.

**Comment by hauleth** [comment]
I see some solutions (each with downsides):

1. Use `git format-patch` and `git apply`/`git am` to copy your work. Unfortunately it will delete all your history.
2. Add new remote, fetch data from this repo, rebase or cherry pick your work on top of that repo, delete your fork, fork again from this repo, cleanup your remotes, have fun. Downside - hell lot of work.

**Comment by agladysh** [comment]
In theory one can migrate issues via GitHub API. Look at google code migration kit for inspiration.

**Comment by ignacio** [comment]
@lukego Probably too low-level but maybe using `git fast-import` to apply your commits to a newly forked repo?
https://git-scm.com/docs/git-fast-import

**Comment by rdebath** [comment]
One way to get two repositories into one is like this ...
```
$ git clone https://github.com/LuaJIT/LuaJIT
$ cd LuaJIT
$ git fetch https://github.com/LuaDist/luajit.git master:luadist
```

This works with ANY two repositories, even ones that have no relation what so ever to each other.
These two seem to have split back in 2011 with some later merging so it's not going to be simple to make a plain pull request. However, once they are in the same repo you don't have to mess with "imports" or "format-patches" because your favourite tools will be available.

NB: Usually you'd want the first repo mentioned above to be your fork of LuaJIT/LuaJIT, but it's possible to push any branch to any repo manually like this:
```
git push git@github.com:$GITHUBUSER/$GITHUBREPO.git master:$NEWBRANCHNAME
```
Which creates (or updates) $NEWBRANCHNAME in https://github.com/$GITHUBUSER/$GITHUBREPO

**Comment by NukeRusich** [comment]
Copy and paste your changes from your old repo to your new repo; keep your old repo for bug reporting purposes, and mark it as a legacy repository. Also, it would be best to keep your old repo for knowledge of solved bugs after it is completely supplanted by your new repository, because historic issues can provide insight into our present issues.
