### ISSUE TITLE
[2.1] Performance regression with table.remove (luacov)

### ISSUE THREAD

**Issue by blueyed** [LuaJIT/LuaJIT#516]
I've noticed that LuaJIT 2.1 is much slower when run with luacov in Neovim's test suite.

I've bisected this to https://github.com/LuaJIT/LuaJIT/commit/5e601891fc9faf8cde836e6515bfdd273dd113e9: Replace table.remove with bytecode builtin.

Using `BUSTED_ARGS=--coverage TEST_FILTER=0xffff TEST_FILE=test/unit/mbyte_spec.lua timeout 25 make unittest` in Neovim's test suite.

Normally a single generated test from there (filtered via `TEST_FILTER`) takes ~5s without luacov, and ~14s with luacov.

With 5e60189 however it takes a lot longer (~380s)!
Using cluacov instead (0.1.1-1) still takes ~128s then.

LuaJIT is built using `make CFLAGS=-fPIC CFLAGS+=-DLUA_USE_APICHECK CFLAGS+=-DLUA_USE_ASSERT CCDEBUG+=-g BUILDMODE=static`.

The test code: https://github.com/neovim/neovim/blob/42e3e894cabeed278d908b921969132964a55ab5/test/unit/mbyte_spec.lua#L50-L60

The slowness comes via the `table.remove` call in https://github.com/neovim/neovim/blob/42e3e894cabeed278d908b921969132964a55ab5/test/unit/helpers.lua#L689

The `table.remove` gets called 187559 times there, and is meant to shorten the table holding tracelines from the child process.

I've tried to reproduce this in a single Lua program.
The following takes ~30s on 5e601891, and only 20s on the commit before (b8abb4b).

```lua
local t = {}
for c = 0, 100000 do
  t[#t + 1] = c
end

for c = 0, 100000 do
  t[#t + 1] = tostring(c)
  table.remove(t, 1)
end
```
It does not really explain the much bigger difference really, but appears to go into the direction of triggering a performance issue with the new code.

(as for Neovim's test suite / code, I think it should be optimized there, and can probably even be skipped by default (since no trace is being shown then anyway!))

**Comment by blueyed** [comment]
However, using luacov on the test file shows the big slowdown then.  /cc @hishamhm @mpeterv

1:30m with `-lluacov` (and a table size of 10000), and instant with b8abb4b9.

**Comment by blueyed** [comment]
The problem appears to be that the debug hook is called much more often.  50026 vs. 100070027 (with a table size of 10000).

**Comment by fsfod** [comment]
Mike Paul probably considered removing tables elements not from the end as a uncommon case since traces would of been aborted before that change, but replacing the hand written JIT recorder for table.remove with bytecode will make things slower if the JIT is disabled or blocked by things like active debug hooks.

There is also a code complexity cost with hand written JIT recorders and they can be a source of many bugs, but idk if using bytecode here is really a win since the JIT will have to generate a trace of the loop for each Lua data type. Also if the types found in the table are mixed the JIT will just create a weird mess of traces linked together that might be slower than the old C code.

**Comment by blueyed** [comment]
@fsfod 
Do you suggest reverting it then?

Why is it that the debug hook is being called more often now?
Is it because it would previously only get triggered for the `table.remove` while now being called for the inline code?

**Comment by siddhesh** [comment]
> @fsfod
> Do you suggest reverting it then?

FWIW, I'm all for reverting.  I had a look at this specific recorder and it really only tries to JIT the simple pop case which makes sense since it becomes just two IR ops.

For everything else it continues using the C implementation which is simple enough that it's quite fast.  Looking at the generated code, there may be some scope to make it scale better, but that falls into the enhancement case.

ISTM that the hope with that change (and perhaps it's proven for some cases too, but we may never know since the motivation is not documented) is that the JIT compiler will do a better job of inlining the bytecode and generate more compact code than the C implementation but that does not seem to be the case from a cursory look of the generated code.

> Why is it that the debug hook is being called more often now?
> Is it because it would previously only get triggered for the `table.remove` while now being called for the inline code?

That is correct.

**Comment by hishamhm** [comment]
Very stupid question: is this the per-line debug hook being called? So, if the code snippets in the embedded bytecode used `;` instead of linebreaks the whole pure-Lua implementation of `table.remove` would register as one line and not hit the debug hooks like crazy?

**Comment by blueyed** [comment]
Likely, yes.

**Comment by MikePall** [comment]
First, debug hooks should never be enabled in production. Especially the line hook is dead slow.

Also, a coverage tester is not a benchmarking tool. Drawing conclusions from its performance is unlikely to yield valid insights.

**Comment by hishamhm** [comment]
The issue is not about the fact that debug hooks have performance impact, it's about spurious debug hook calls that should have never have happened in the first place rendering coverage analysis so slow as to make it unusable.

**Comment by MikePall** [comment]
Line hooks are called on every iteration of a loop. That's a feature of Lua (all versions).

``` Lua
debug.sethook(function() print(debug.getinfo(2).currentline) end, "l", 0)
for i=1,5 do end
debug.sethook(nil, "", 0)
```
-->
```
3
3
3
3
3
4
```
