### ISSUE TITLE
random memory value error

### ISSUE THREAD

**Issue by gzgh14** [LuaJIT/LuaJIT#523]
tt = {}
for i = 1, 10000000 do
    local k = string.format( "1kkkk%d" , i )
    local v = string.format( "1vvv%d" , i )
    tt[k] = v
end

when I run the above code，luajit will run error in the near future。thus as
local nValue =100
assert(nValue > 0)
the assert will return false
has anyone Encounter similar problem，may I ask for some idea to solved it？

I embedded luajit to my program，and build with g++ 4.7 on debian 7

**Comment by javierguerragiraldez** [comment]
couldn't reproduce any error.

when you say that

> luajit will run error in the near future。thus as
local nValue =100
assert(nValue > 0)
the assert will return false

you mean typing these two lines in the LuaJIT REPL prompt?  if so, remember that the REPL tries to interpret each line separatedly.  thus the secont line won't get the `local nValue` variable, and will fail because `nValue` there is a new global variable and gets the `nil` value.

you can get the expected behaviour by different means:

1. not using the REPL prompt, put these statements in a file
1. type as a single line, like `local nValue =100  assert(nValue > 0)`
1. wrap with `do ... end` so the REPL is forced to the block and interpret as a whole

here you can see the separate lines triggering an error and then work normally when joined, either as a single line or by wrapping with `do .. end`.  in the last case note how the REPL prompts with `>>` instead of the usual `>`, that's to show it's waiting for some extra input to complete the part already entered.  after the `end` line, the block is valid and executed.

```
$ luajit
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> local nValue =100
> assert(nValue > 0)
stdin:1: attempt to compare number with nil
stack traceback:
        stdin:1: in main chunk
        [C]: at 0x55fceab421d0
> 
> 
> local nValue =100 assert(nValue > 0)
> 
> 
> do
>> local nValue =100
>> assert(nValue > 0)
>> end
> 
> 
> 
```
