### ISSUE TITLE
Performance Issues (micro-freezes) everywhere except Win x86

### ISSUE THREAD

**Issue by eagleivg** [LuaJIT/LuaJIT#541]
We use LuaJit in the OpenXRay game engine. When updating the state of game objects, strange micro-freezes occur.
Example (in normal case execution time less then 3 ms) :
```
* ScriptBinder: sim_default_stalker_110678 too much time consumed by shedule (8ms)
* ScriptBinder: sim_default_stalker_110678 too much time consumed by shedule (7ms)
* ScriptBinder: zat_a2_sr_noweap too much time consumed by shedule (7ms)
* ScriptBinder: zat_b104_zombied too much time consumed by shedule (7ms)
* ScriptBinder: zat_sim_18 too much time consumed by shedule (7ms)
* ScriptBinder: zat_b106_stalker_gonta7018 too much time consumed by shedule (7ms)
* ScriptBinder: zat_b7_stalker_raider_leader7342 too much time consumed by shedule (6ms)
```
The problem appears on Win7 x64, Linux x86 / x64, but is missing on Win7 x32. Any ideas?

**Comment by MikePall** [comment]
Try to use the profiler in v2.1 to find out where the CPU time is spent (or in which VM states, e.g. GC).
Without a standalone test-case, there's not much we can do here.

**Comment by eagleivg** [comment]
Indeed, most freezes occur in garbage collection. We use the incremental GC: 
`lua_gc (GEnv.ScriptEngine-> lua (), LUA_GCSTEP, 100);` 
but even reducing it to single step does not give a result. - GC still takes from 7 to 40 ms.

I also don’t understand why commenting on incremental garbage collection does not stop freezing with state G - garbage collection process should stop if neither LUA_GCSTEP nor LUA_GCCOLLECT is called, right?

**Comment by MikePall** [comment]
No, this doesn't work that way at all (neither in Lua nor in LuaJIT). Why are you stepping the GC by hand? Is this some kind of cargo-cult? The GC works incrementally in any case, as a side-effect of allocations.
Long pauses in the GC are often a side-effect of expensive userdata finalizers. Are you allocating lots of userdata objects? This means you're not making good use of LuaJIT at all. Switch to plain Lua and measure the execution time difference.

**Comment by eagleivg** [comment]
>  Why are you stepping the GC by hand? Is this some kind of cargo-cult?

This is an original decision of the authors of the original engine. In principle, it worked well on win x86, but later we ported the engine first to win x64, and later to linux. Now we trying to solve this problem:)

>  Long pauses in the GC are often a side-effect of expensive userdata finalizers. Are you allocating lots of userdata objects? This means you're not making good use of LuaJIT at all. Switch to plain Lua and measure the execution time difference.

Ok, I’ll try to limit the number of processed objects. The option using lua will take a little longer, need to adapt the game engine, so I'll try it later.

**Comment by edubart** [comment]
@eagleivg  If you don't use lua properly in your game engine then the GC will be your enemy. This scenario of random freezes is specially the case of bad design decisions that makes the GC slower. Might be of your interest to read my answer to a related question about LuaJIT, game engines and GC in [the mailing list](https://www.freelists.org/post/luajit/Write-in-Lua-or-link-an-existing-C-library,1).

Maybe in a future where the new proposed garbage collector for LuaJIT 3.0 by @MikePall see the light of the day, this scenario would be much better, for now we have to deal with Lua/LuaJIT GC constraints.

**Comment by sonoro1234** [comment]
Meanwhile, quick and dirty solution to avoid long gc ocurrences at the cost of loosing some perfomance is to call collectgarbage on a fixed basis (every frame or every 10 frames for example)

**Comment by edubart** [comment]
@sonoro1234 Indeed, although calling a full collect cycle at a frame might be too expansive, this is what I do on some game engines I've created to have predictable frame latency:

1 - After all the game engine initialization do a full collect cycle using `collectgarbage("collect" )` and then stop the GC all together with `collectgarbage("stop")`
2 - At each frame do one GC step with `collectgabage("step", x)`, it returns true when a GC cycle finish, this information is then used to recalculate the `x`. How to adjust `x` is up to the engine design, usually I want to complete a full GC cycle every N seconds and increase/decrement `x` based on that.
3 - Stop the GC again after each GC step, because in LuaJIT the step causes the GC to automatically start again (this does not happen in PUC Lua), you can check this by doing  `collectgarbage("isrunning")`

This algorithm is essentially running the GC manually and incrementally in a more per frame predictable manner, to behave more soft realtime in the engine, meaning there wont be surprise freezes due to the GC as long nothing too crazy happens on lua side between frames. But there is the cost of wasting CPU cycles running the GC consistently at times it wouldn't probably need.

I've worked around random latency from the GC on different game engines by approaching this way.

Note: This algorithm does have flaws if you create new objects faster than you do step then a full cycle might take too long to finish and the lua memory might blow up. But you can come up with some solutions own your own if this happens.

**Comment by fsfod** [comment]
To expand on the cost of userdata to the GC. There is GC atomic phase that is started and completed in a single GC step. One of the things it does is a full walk of the all the currently allocated userdata thats in one big linked list to find dead objects that have a __gc meta functions(this step is opt in in Lua 5.2+ based on a check in setmetatable).
This means the run time of the atomic phase will scale up with the number of userdata objects, if the count is in the hundreds of thousands the atomic phase could take over 20ms but yours is not as high as that though.
