### ISSUE TITLE
Q: can main thread preference be overcome

### ISSUE THREAD

**Issue by glycerine** [LuaJIT/LuaJIT#542]
Last year, LuaJIT on windows/amd64 seemed unhappy when I would call it from a 2nd thread that was not the main thread that it was initialized from. I assumed this was due to thread local storage or something similar. I would be interested in patching LuaJIT to allow it to run on multiple/any thread available.  

Could someone point me to where the main-thread preference originates?

**Comment by MikePall** [comment]
There is no preference for any thread. You can call into the VM from any thread. Except you can't do this concurrently, since the VM is single-threaded.
Also, you can only call into the VM, if it's in an idle state (neither yielded nor in a callback).
If that doesn't fit your needs, then create multiple independent VMs.

**Comment by glycerine** [comment]
Thanks Mike. I think I was always yielded or in a callback, so that probably explains it.
