### ISSUE TITLE
What is best practice for cdata reference cdata?

### ISSUE THREAD

**Issue by vkensou** [LuaJIT/LuaJIT#554]
I have 2 c struct like this:
```
ffi.cdef[[
    struct A { int id; };
    struct B { int id; struct A* a; };
]]

function createB()
    local a = ffi.new("struct A")
    local b = ffi.new("struct B")
    b.a = a
    return b
end
```

I want reference b only. How could make it work properly?

**Comment by MikePall** [comment]
FFI cdata is not traversed by the GC. If you want to reference some cdata from multiple places, then you really need to use references from Lua tables to such a cdata object.

The following solutions only consider the case when there's only a **single reference** from a main cdata to another cdata:

**Solution 1** Flatten your structures: Move referenced data into the main cdata object. Even with optional data this can me more memory efficient, since you don't need the pointers anymore.

**Solution 2** Co-locate cdata: Make one variable-length allocation, then place the main cdata plus the referenced cdata into it and update the pointers. This involves quite a few casts and trickery during initialization (beware of alignment), but it can be used normally. Co-location also helps with cache locality.

**Solution 3** Use cdata only at the edges: Use plain Lua tables for all inner nodes.

**Comment by vkensou** [comment]
> FFI cdata is not traversed by the GC. If you want to reference some cdata from multiple places, then you really need to use references from Lua tables to such a cdata object.
> 
> The following solutions only consider the case when there's only a **single reference** from a main cdata to another cdata:
> 
> **Solution 1** Flatten your structures: Move referenced data into the main cdata object. Even with optional data this can me more memory efficient, since you don't need the pointers anymore.
> 
> **Solution 2** Co-locate cdata: Make one variable-length allocation, then place the main cdata plus the referenced cdata into it and update the pointers. This involves quite a few casts and trickery during initialization (beware of alignment), but it can be used normally. Co-location also helps with cache locality.
> 
> **Solution 3** Use cdata only at the edges: Use plain Lua tables for all inner nodes.

Thanks for your reply.
I write a little library to reference cdatas automatically. There are 2 ways to do this: save all cdatas in one c array (see here), or save references in lua table.
