### ISSUE TITLE
numbers as keys with and without zero

### ISSUE THREAD

**Issue by sonoro1234** [LuaJIT/LuaJIT#560]
Hi,

This program where only secs_now (to measure time with subsecond precission) needs to be provided gives a duration of 4.8 secs, but if I add `A[0]=true` , time goes to 5.6 secs.
The same happens for 1 and 2 but not with other numbers.

```Lua
local floor,random = math.floor, math.random
local initt = secs_now()
local A = {}
--A[0] = true
local N = 1e7
local a
for i=1,N do
	a = random() --*N
	A[a] = true
end

local count = 0
for num in pairs(A) do
	count = count + 1
end
print(count,"time",secs_now()-initt)
```

It seems that only a 16% increment is small, but I was working on a set of tri-dimensional points where the point is in the set if A[x][y][z] == true and changes when using vector <0,0,0> where more dramatic. (300% increment)

Is this expected?
Thanks

**Comment by MikePall** [comment]
You are seeing the performance difference for a Lua table that only has a hash part and one that has both an array and a hash part. For the latter, every index access must check whether it's a potential array index (convert double to int, convert back, compare both, compare against array bounds). The JIT compiler is smart enough to elide that check, if the tables in question generally don't have an array part. Alas, they may grow one, if you store small integer indices.

If you really want to avoid creation of the array part and/or pre-size the array and hash part of a table, then use `table.new`.

But I suspect the real issue is that a multiple-level hash table is probably not the optimal data structure for an N-dimensional set. E.g. consider merging the index into a single key. Algorithmic optimizations are a bit out of scope here, though.

**Comment by sonoro1234** [comment]
Thanks for answering.

> If you really want to avoid creation of the array part and/or pre-size the array and hash part of a table, then use `table.new`.

table.new is nil !!!

> But I suspect the real issue is that a multiple-level hash table is probably not the optimal data structure for an N-dimensional set. E.g. consider merging the index into a single key. Algorithmic optimizations are a bit out of scope here, though.

Sure!! I have tried with tostring(vector) for the table keys, but I have to check other posibilities also.

**Comment by CapsAdmin** [comment]
> Thanks for answering.
> 
> > If you really want to avoid creation of the array part and/or pre-size the array and hash part of a table, then use `table.new`.
> 
> table.new is nil !!!
> 
> > But I suspect the real issue is that a multiple-level hash table is probably not the optimal data structure for an N-dimensional set. E.g. consider merging the index into a single key. Algorithmic optimizations are a bit out of scope here, though.
> 
> Sure!! I have tried with tostring(vector) for the table keys, but I have to check other posibilities also.

`local table_new = require("table.new")` in 2.1

**Comment by sonoro1234** [comment]
I must remember that online docs are 2.0 only!!
Thankyou
