### ISSUE TITLE
Over 60% perf drop with revision b2307c8 (on irrelevant microbenchmark)

### ISSUE THREAD

**Issue by vanc** [LuaJIT/LuaJIT#587]
Ran some benchmarks and found that partialsums.lua was over 60% slower with revision b2307c8.

The code was compiled on Ubuntu 18.04 running on a Intel Xeon(R) CPU E5-1660.

With 5655be45:

```
$ time src/luajit partialsums.lua 100000000
3.000000000	(2/3)^k
19998.539695493	k^-0.5
0.999999990	1/k(k+1)
30.314546113	Flint Hills
42.995234462	Cookson Hills
18.997896414	Harmonic
1.644934058	Riemann Zeta
0.693147176	Alternating Harmonic
0.785398161	Gregory

real	**0m9.309s**
user	0m9.308s
sys	0m0.001s
```

With b2307c8:
```
$ time src/luajit partialsums.lua 100000000
3.000000000	(2/3)^k
19998.539695493	k^-0.5
0.999999990	1/k(k+1)
30.314546113	Flint Hills
42.995234462	Cookson Hills
18.997896414	Harmonic
1.644934058	Riemann Zeta
0.693147176	Alternating Harmonic
0.785398161	Gregory

real	**0m15.272s**
user	0m15.272s
sys	0m0.000s
```

**Comment by vanc** [comment]
@MikePall

**Comment by MikePall** [comment]
This is expected, since the power operator is no longer split into exp/log. See #9.

The splitting caused intolerable inaccuracies and wrong results for special cases. The splitting also caused irreconcilable inconsistencies between the interpreter and the JIT compiler.

The only thing the splitting enabled was to partially hoist the computation for a (very) artificial microbenchmark.

In an actual application you'll probably never compute that particular power series (which allows hoisting), let alone repeatedly. E.g. in computational physics the few things that can be hoisted out of formulas are most certainly manually hoisted. Or such an opportunity simply doesn't exist.

**Comment by vanc** [comment]
Thanks for the clarification.
