### ISSUE TITLE
LuaJIT on AmigaOS

### ISSUE THREAD

**Issue by afxgroup** [LuaJIT/LuaJIT#589]
I'm trying to cross compile LuaJIT for AmigaOS4 that is a powerpc platform but i receive an error on buildasm

Error: DASM error 11000e3d

This is the make parameters i'm using

make CROSS=ppc-amigaos-

What's wrong?

**Comment by MikePall** [comment]
This error indicates some displacement is out of range. Probably relative to the global state, which would be strange, because that structure is not that big (and PPC offsets are +-32K).

OTOH, I doubt you could get LuaJIT running on AmigaOS at all, without considerable changes. First try to disable the JIT compiler and the FFI in `src/Makefile`, then check how far you get.

**Comment by afxgroup** [comment]
Same,
even disabling both FFI and JIT and one of each. However we have a working lua library. So what is the difference between this one (with jit disabled) and the standard LUA?

**Comment by afxgroup** [comment]
Well, if i enable LUAJIT_USE_SYSMALLOC i can go on. Most probably the allocator cause some problems. 
There is also a problem with PPC in lj_arch.h because if it is defined _LP64 you have an error because PowerPC in 64 but mode is not supported but it seems defined if i use an host 64bit gcc compiler and in this case  LJ_ARCH_BITS became 64 that is wrong
So i have to force gcc in 32 bit mode and compile it with -m32 and gcc-multilib..
Well after some small changes in the code (for example we don't have mmap/mmunmap) it is compiled. Now i have to test if everything is working

**Comment by afxgroup** [comment]
![luajit](https://user-images.githubusercontent.com/484672/84920103-06f43380-b0c3-11ea-89b9-5f1b637e8fc7.jpg)

Basic functions seems to work.
Closing it
