### ISSUE TITLE
Performance and wrong result issue of file:seek('cur') on Windows

### ISSUE THREAD

**Issue by hyee** [LuaJIT/LuaJIT#607]
I only test this feature on Win10 and Linux, version is the latest whose last commit time is `Jul 13`. 
On Win7,  the `file:seek('cur')` function doesn't work well in either x86 or x64 bit Luajit.
Below is the test case over a 40MB file:

```lua
local f=io.open('d:\\2jtk0zmftqjmj_slow.trc')
local s,s1=0

local t=os.clock()
for line in f:lines() do
    s=s+#line+1
end
print('no seek',os.clock()-t,s,f:seek('cur'))

f:seek('set',1)
t,s=os.clock(),0
for line in f:lines() do
    s=s+#line+1
    s1=f:seek('cur')
end
print('seek', os.clock()-t,s,s1)
f:close()

Below is the Output:
=============
no seek 0.222   41836432        42373001
seek    3.966   41836431        42373001
```
You can see that the performance is about 20x difference, in Linux the case works well however result of `s` is same to `f:seek()`. 
Another strange case is using another file(around 597KB) as the test file,  case 2 is hung due to running into infinite loop, which `f:seek('cur')` always return the same value and sometimes the line fetched from `file:lines` is wrong, of which some leading chars are missing. I tried disabling `GC64` but no luck.

**Comment by MikePall** [comment]
This has nothing to do with LuaJIT or Lua.

You're opening the file in text mode, because you didn't use `io.open(filename, "b")`. This doesn't matter on Linux, but makes a huge difference on Windows. In particular, as soon as you use a seek on a file opened in text mode, the Windows C library has to synthesize file positions and that's really slow.

**Comment by hyee** [comment]
Thanks, I didn't realize that difference.
