### ISSUE TITLE
Inconsistent conversion of '-' to '_' when byte compiling.

### ISSUE THREAD

**Issue by systemmonkey42** [LuaJIT/LuaJIT#609]
Hi All,

I am in the process of building a runtime for "precompiled" applications.

Each module is compiled to an object file, and all objects are bound into a `.so`, which is preloaded
via `dlopen()`.

When modules are compiled, all `-`'s are automatically converted to `_`'s

As a result, any `require()` call, cannot find the file, even though the un-compiled source works fine.

Since `-`'s are converted to `_`'s automatically when generating binaries, can we please perform
the same conversion automatically before the call to `dlsym()` to ensure consistency?

Many thanks

Example showing automatic conversion -
```
$ luajit -b -n test-func test-func.lua test-func.o
$ objdump -x test-func.o
0000000000000000 g     O .rodata        00000000000001ce luaJIT_BC_test_func
$ cc -o shared -fPIC -o module.so test-func.o
```

runtime looks something like (stripped for brevity):
```
{
    lua_State *L;
    L = luaL_newstate();

    void *lib;

    dlopen("./module.so", RTLD_NOW|RTLD_GLOBAL);
    luaL_openlibs(L);
    lua_getglobal(L, "require");
    lua_pushliteral(L, "test-func");
    lua_pcall(L, 1, 0, 0);
}
```
If I replace `test-func` with `test_func`, it runs correctly.

**Comment by systemmonkey42** [comment]
Sorry, I should have mentioned I am using the pre-built luajit supplied with Ubuntu 20.04.

This version has been heavily patched, and may not reflect *actual* `luajit-2.1.0-beta3` behaviour.

I'll test with the top of GIT (2.1 branch) and update.

**Comment by MikePall** [comment]
The `-` is special in C module names. Avoid it.

Although IMHO not very useful, the specific behavior is mandated by Lua. LuaJIT has to follow for compatibility. It's still part of Lua 5.4 and documented here: https://www.lua.org/manual/5.4/manual.html#pdf-package.searchers Quoting:

```
Moreover, if the module name has a hyphen, its suffix after (and including) the first hyphen is removed.
```

This is/was intended for versioning C modules. With C modules in the filesystem you have the filename (which is loaded without stripping the `-`) and the symbol name (where only the part after the `-` is left).

But this cannot work for embedded bytecode, since there's only one namespace. There's no proper way to fix this. Stripping the symbol name when generating the bytecode only gives the illusion of a fix. But then you'd get a symbol conflict with `test-func` vs. `real-func`.

**Comment by systemmonkey42** [comment]
I understand.  You saying the error is in the luaJIt compiler, because it fails to strip the `-` and all the text that follows it.

I can work around that by simply telling my lua devs to stop using `-`'s, because they are not valid in module names,  and where they DO version modules using `-v2` et al, they must use the `luajit -b -n <stripped_name>` to ensure the everything after the hyphen is removed.  (I dont think that part will be a problem because I suspect they were as unaware of the spec as I was.)

Thanks for clarifying.

Is there any chance LuaJIT will be updated to conform to the spec you are referring to? 

Cheers

**Comment by MikePall** [comment]
Yes, it's weird. The part **before** the hyphen is the version. Not my idea and not how I would have implemented it.

Anyway, ignore that versioning scheme (I don't know of anyone using it) and simply avoid hyphens in module names.
