### ISSUE TITLE
Identify areas for new people to contribute

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#61]
There are people (such as myself) who would love to contribute to LuaJIT, but who are not compiler or GC experts (I, for instance, am still a student).  It would be nice to identify places where such people could contribute (and hopefully learn something in the process).

**Comment by lukego** [comment]
One suggested area:

I would be very interested in cooperating with other people to develop a better mental model of how to optimize for LuaJIT. That could involve working through examples, reading LuaJIT code, and writing diagnostic tools e.g. profiler/dumper extensions.

I am not sure what the best way to arrange this would be but this is a burning need in the Snabb Switch community. We want to be able to quickly get casual programmers productive with LuaJIT and able to write code with predictable performance.

I have been doing some investigations on e.g. lukego/blog#8.

**Comment by drbo** [comment]
The closest production-grade VM to LuaJIT (in terms of concept) is PyPy, which has _excellent_ visualization [tools](https://bitbucket.org/pypy/jitviewer).  Perhaps these could be modified to work for LuaJIT (although they seem somewhat closely tied to the internals of RPython-based interpreters), but the idea sounds like it would be very useful to tune performance of tracing JITs in general.

This is probably not the only way that LuaJIT can learn from PyPy (and visa versa) &ndash; since they and HHVM are the only production-quality JIT compilers, and HHVM is the least optimized.  LuaJIT seems faster, while PyPy seems to have better tooling around it.
