### ISSUE TITLE
coroutine.clone?

### ISSUE THREAD

**Issue by 110yd** [LuaJIT/LuaJIT#612]
Hello,

Is it possible/feasible/reasonable to implement coroutine.clone function? I think about reactive computation engine (like Excel) where you can snapshot coroutine state on every data access and restart evaluation straight from code path affected by source data change.
I've seen old discussion in mailing list http://lua-users.org/lists/lua-l/2006-01/msg00685.html however that was about vanilla Lua interpreter.
Or would it affect JIT compiler to the state, when whole function reevaluation would be faster than that pretty unstable and dangerous trick?

Thanks

**Comment by ExtReMLapin** [comment]
> you can snapshot coroutine state on every data access 

That sounds incredibly slow

**Comment by MikePall** [comment]
While it would be theoretically possible to create some kind of `coroutine.clone` functionality, it would be quite difficult to get it to work properly under all circumstances. I don't see a real need for it, anyway.

Yes, doing permanent snapshots of a coroutine would be very wasteful. And I don't think it would be the right tool to implement reactive state.

There are quite a few reactive frameworks you could take a look at how to implement this. E.g. Vue (in JavaScript) is one of the smaller and more readable ones.

Minimal summary of the core ideas:

It has reactive variables and aggregates. It keeps track which of these variables are accessed directly or indirectly by side-effect-free functions implementing computed variables. Start to evaluate the output variable(s) and work backwards until you reach an input variable. This allows to build a reverse dependency tree.

When any input variable changes, invoke the dependent functions, which in turn may change some computed variables etc. Stop when all updates have been processed. Then you know which output variables have changed and need to be updated on the display.

You can do all of the tracking and simulation of computed variables easily in Lua with the `__index` metamethod. You may need a double indirection for the tracking, because `__index` is only invoked when the corresponding table key is nil/non-existent.
