### ISSUE TITLE
Incorrect stack trace

### ISSUE THREAD

**Issue by PhilipRoman** [LuaJIT/LuaJIT#614]
This bug was found by https://www.reddit.com/user/NotExplosive, full credit to them. I took the liberty of reporting it here.

# Test case:
```lua
local function noOp()
end

local function doSomethingElse()
	assert(false)
end

local function doSomething()
	doSomethingElse()
end

(doSomething or noOp)()
```

Output:
```
luajit: bug.lua:5: assertion failed!
stack traceback:
	[C]: in function 'assert'
	bug.lua:5: in function 'doSomethingElse'
	bug.lua:9: in function 'noOp'
	bug.lua:12: in main chunk
	[C]: at 0x7ffa4b830c20
```

The stack trace is obviously incorrect because noOp shouldn't be on it.

# Affected versions
Tested on:
* 2.1.0-beta3  (ff1e72a)
* 2.0.5
* 2.0.0

**Comment by MikePall** [comment]
Functions in Lua do not have a name. The name can only be inferred for debugging purposes by symbolc reverse-execution of the bytecode. Since the bytecode is turing-complete, this cannot possibly cover all cases within a finite time budget. That's why some heuristics are used, which may fail in specific cases.

Although the heuristics work quite well for most standard programs, there are a variety of cases where no function name or no correct function name can be inferred. The cases may differ between different Lua and LuaJIT versions. This is neither new, nor unexpected and not a bug.
