### ISSUE TITLE
call builtin math.sin/log/exp functions crash on Fedora/i386

### ISSUE THREAD

**Issue by waruqi** [LuaJIT/LuaJIT#625]
For Luajit v2.1 (latest commit)

I'm making my rpm spec file to build luajit sources.

```
%build
%set_build_flags
%make_build
```

`%set_build_flags` will export $LDFLAGS and $CFLAGS to build them. But I call all builtin math functions crash on Fedora/i386.

```console
LDFLAGS=-Wl,-z,relro -Wl,--as-needed -m32 -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
export CFLAGS
export LDFLAGS
make CC="gcc -m32"
./src/luajit 
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2020 Mike Pall. http://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> math.sin(1)
Segmentation fault
```

I found than it will work fine if I remove `-specs=/usr/lib/rpm/redhat/redhat-hardened-ld` from the LDFLAGS.

And it crash on lj_vm.S/`call sin@PLT`.

```
	.globl lj_ff_math_sin
	.hidden lj_ff_math_sin
	.type lj_ff_math_sin, @function
	.size lj_ff_math_sin, 42
lj_ff_math_sin:
	.byte 131,248,2,15,130,35,9,0,0,131,122,4,242,15,131,25
	.byte 9,0,0,242,15,16,2,242,15,17,4,36,137,213
#if __PIC__
	call lj_wrap_sin
#else
	call sin@PLT            <----- will crash
#endif
	.byte 137,234,233,148,254,255,255
```

It will works fine if I add `-fPIC` flags to compile luajit/lj_vm.S.

**Comment by MikePall** [comment]
From looking at the corresponding `redhat-rpm-config` package, this just adds `-fPIE` to the compiler flags and `-pie` to the linker flags.

Since `-fPIE` implies `-fPIC`, the `__PIC__` define is set and the correct part of the assembler code is compiled. This works fine for me here (but I don't use Redhat).

If not, then something is broken with the particular Redhat toolchain. Try something like `echo | gcc -fPIE -dM -E - | grep __PI` for some combinations of `-fPIC`, `-fPIE` or passing the `-specs`. It should not be possible to get `__PIE__` without `__PIC__`.

**Comment by waruqi** [comment]
> Since -fPIE implies -fPIC, the __PIC__ define is set and the correct part of the assembler code is compiled. This works fine for me here (but I don't use Redhat).

Yes, it is true, thanks.
