### ISSUE TITLE
table keys order is not stable

### ISSUE THREAD

**Issue by crasyangel** [LuaJIT/LuaJIT#626]
```
sh-4.1$ src/luajit -v
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2020 Mike Pall. http://luajit.org/
sh-4.1$ src/luajit -e "a = {}; a['a']=1; a['b']=1; a['c']=1; a['d']=1; for k,v in pairs (a) do print (k .. ':' .. v) end"
a:1
b:1
c:1
d:1
sh-4.1$ src/luajit -e "a = {}; a['a']=1; a['b']=1; a['c']=1; a['d']=1; for k,v in pairs (a) do print (k .. ':' .. v) end"
b:1
c:1
d:1
a:1
sh-4.1$ src/luajit -e "a = {}; a['a']=1; a['b']=1; a['c']=1; a['d']=1; for k,v in pairs (a) do print (k .. ':' .. v) end"
b:1
c:1
d:1
a:1
sh-4.1$ src/luajit -e "a = {}; a['a']=1; a['b']=1; a['c']=1; a['d']=1; for k,v in pairs (a) do print (k .. ':' .. v) end"
b:1
c:1
d:1
a:1
sh-4.1$ src/luajit -e "a = {}; a['a']=1; a['b']=1; a['c']=1; a['d']=1; for k,v in pairs (a) do print (k .. ':' .. v) end"
d:1
a:1
b:1
c:1
sh-4.1$ src/luajit -e "a = {}; a['a']=1; a['b']=1; a['c']=1; a['d']=1; for k,v in pairs (a) do print (k .. ':' .. v) end"
c:1
d:1
a:1
b:1
```

**Comment by GitSparTV** [comment]
Isn't it always unstable because hashmap has no order?

**Comment by crasyangel** [comment]
> Isn't it always unstable because hashmap has no order?

https://github.com/LuaJIT/LuaJIT/commit/ff34b48ddd6f2b3bdd26d6088662a214ba6b0288

table keys order is stable, without above changes

**Comment by waruqi** [comment]
> Isn't it always unstable because hashmap has no order?

Yes, I also encountered it, it seems that the order has become random.

Although we should not rely on the order of table keys, all versions before luajit-v2.1.0-beta3 seem to have a fixed order.

Therefore, when I upgraded to v2.1/master, I also encountered many hidden problems. I have modified my code to fix some of these problems. But I don’t know if all related problems have been completely avoided.

**Comment by hippi777** [comment]
hi there! :) 

sure, this is normal, and yes, cuz neirher the hash part nor `pairs()` maintain an order, and if they do, then thats actually an implementation detail that shouldn't be relied on, except if u know the internals and if its also fine for u to stick with a single version, or a possibly limited range of versions, or even a fork...

otherwise u can get and sort the keys in case of need, as if u make an array from the keys, then `ipairs()`, or even a numeric `for` will always keep the order u gave them. u can even make an `spairs()` (made up name for "sorted pairs") function that will do the same behind the scenes, just check out in the lua manual how `for` works, and maybe what `pairs()` and `ipairs()` give back after u call them if u use them outside of `for`...

bests, have fun! :)

**Comment by MikePall** [comment]
Quoting https://www.lua.org/manual/5.1/manual.html#pdf-next

> The order in which the indices are enumerated is not specified [...]

The recently introduced hardening of the VM deliberately randomizes string hashes. This in turn randomizes the iteration order of tables with string keys.

If anyone ever relied on a particular iteration order, this is a bug in their code. They should be glad the hardening of the VM exposed it quickly.
