### ISSUE TITLE
io.popen May Crash In Multi-Thread Environment

### ISSUE THREAD

**Issue by git-blame** [LuaJIT/LuaJIT#630]
I have luajit executing scripts in a multi-threaded environment. Some of these scripts make a call to `io.popen` which calls `popen`. I have been experiencing random crashes. After debugging and searching, it turns out that `popen` may not be [thread-safe under some circumstances](https://sourceware.org/bugzilla/show_bug.cgi?id=22834).

Since it is dependent on the version of libc, compiler/OS, etc., I don't expect luajit to fix this issue. But I have raised it for awareness in case someone runs into the same problem.

I have put locks around that section of code for myself in `lib_io.c`:
```c
#if LJ_TARGET_POSIX
  fflush(NULL);
  iof->fp = popen(fname, mode);
#else
  iof->fp = _popen(fname, mode);
#endif
```

**Comment by MikePall** [comment]
While it may be somewhat interesting to collect pitfalls of various operating systems or toolchains, this is the wrong place to do so. Since this issue isn't specific to LuaJIT, the Lua Wiki may be a more appropriate place. But then, this issue in particular isn't even specific to Lua either.

That's why I have to close this as invalid.
