### ISSUE TITLE
Issues with trying to embed LuaJIT into my project

### ISSUE THREAD

**Issue by VaasKahnGrim** [LuaJIT/LuaJIT#637]
Currently attempting to get LuaJIT embedded into a project of mine but running into an issue with unresolved external symbol popping up after compiling. so for I've done roughly this: 

```
//Unrelated portions of code removed

//For using LuaJIT(located here: https://github.com/LuaJIT/LuaJIT)
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"

//So we have use of the Sleep() function later
#ifdef _WIN32
    #include <Windows.h>
#else
    #include <unistd.h>
#endif


int main(){
    bool NoIssues = true; //We'll be using this later

    //SHOULD create our first lua state
    lua_State* LUA_MAIN;
    LUA_MAIN = luaL_newstate();

    luaL_openlibs(LUA_MAIN);

    //because C++ apparently doesn't have its own way of keeping shit open until explicitly told to close it
    while(NoIssues){
        Sleep(1);
    }
}
```

**Comment by ExtReMLapin** [comment]
you need to include the static lib you built. Typically `lua51.lib`

**Comment by VaasKahnGrim** [comment]
I didn't build anything tho, trying to get luajit inside my exe itself

**Comment by ExtReMLapin** [comment]
You need to build LuaJIT then download the repo, using MSVC CMD build it using the .bat.

It will generate multiple files, luajit.exe, lua51.dll, lua51.lib etc

**Comment by VaasKahnGrim** [comment]
I mean I got the repo sitting in my drive, however I'm not wanting a seperate dll file. I'm trying to have a single file which I can just drop it in, start it up and thats it. no additional files or dependancies needed other than the executable itself

**Comment by ExtReMLapin** [comment]
There are two types of libraries, the dynamic (dll) and the static ones (.lib) (on windows at least).
When you compile your exe and directly include the static libraries, it means you only have to ship the exe, no external dependencies.

**Comment by VaasKahnGrim** [comment]
ok, but wouldn't I still need to ship the dll file with the exe in some way? also why can't VS 2019 just use the source files for luajit instead? don't see why it needs to bother with a lib file at all if it already has the source files for it

**Comment by ExtReMLapin** [comment]
LuaJIT's build system is complicated, it uses a lot of processors, code is generated after compilation started etc etc
[Mike pall advises to build static libs and dynamic and to not directly compile luajit code into project](https://luajit.org/install.html#embed)

>It's strongly suggested to build LuaJIT separately using the supplied build system. Please do not attempt to integrate the individual source files into your build tree. You'll most likely get the internal build dependencies wrong or mess up the compiler flags. Treat LuaJIT like any other external library and link your application with either the dynamic or static library, depending on your needs.

**Comment by VaasKahnGrim** [comment]
Well mike pall should really make an actual tutorial for embedding LuaJIT, because the same error is happening even after doing the lib/dll stuff.

currently in my includes/luajit/ folder I have the lua51.lib luajit.exe and lua51.dll sitting there, still unresolved external symbols

**Comment by ExtReMLapin** [comment]
You're mixing up being a greenhorn at compiling code and bad documentation.
In MSVC, as I said in my very first message, you need to include the .lib in the project.

**Comment by VaasKahnGrim** [comment]
shouldn't it already be included by being inside the luajit folder? one sec lemme go deal with googling how to fix that then

**Comment by ExtReMLapin** [comment]
no, .lib are never auto-included.
With auto-include, you could have multiple .lib in a folder, one for release, one for debug, the compiler would auto include both then ?

**Comment by VaasKahnGrim** [comment]
dunno, just makes no sense to me why it wouldn't automatically find them or why it would need them over just compiling LuaJIT into the compiled .exe itself when hitting compile.

Either way I got the unresolved external symbols issue fixed now. I'll have to look into getting luajit inside the .exe later tho so I don't have to deal with a seperate dll file tho. Thanks man

**Comment by hippi777** [comment]
hi there! :) 

u mix up different things, let me give it a try:

when u build luajit, u can get these:
- a freestanding interpreter, that is a relative thin wrapper around its "core" that is a library by its nature, it is written to be like that. this is the thing u can run from a shell and u can get a repl (an interactive command line interpreter) and/or run a(/many) lua script(s), (and/)or a compiled lua module(s). the latter is the result of using the lua c api, that works on luajit as expected, but it is preferable to use the ffi instead, cuz the jit engine cant make assumptions about the former, as it manipulates lua state without a known behavior, that means less possible automatic optimizations. (probably it is possible to improve this, but probably its a nongoal cuz of the ffi and probably hard, however i can imagine having a way to supply info about it instead of examining the c codes, and that still requires a nontrivial change to be usable...)
- a static and/or a dynamic lib. (whatever its make script or bat file expose.) the former is for including into binaries when the object files (compiled units with functions and whatever else that i dont know) are linked together into a single executable file, and this is what u r looking for. the latter is loaded at runtime, and shared between multiple programs. their functionality is identical, the way of their usage differs, and probably their contents too. also note, that linking against a static library can give more opportunities for optimization (removing unused stuffs, maybe more), it can even become a portable single binary this way (if it was written in a spirit to support this on the 1st place). these are managed at compilation/link time... also, these are basically archives of object files, and maybe more or less metadata, and if i know right, then on w*ndos, an exe and a dll differs only in the existence of a `main` function, and even if im wrong, this is near and probably can be enlightening and a good mental model. the luajit interpreter is basically about providing a `main` function, even if there are utility functions for handling the arguments and implementing the interactive prompt, and actually it just utilized the same functionality that a library version provides, and u are about to redefine this, but back to this point later on.
- header files, that contains macros (that will replace pieces of codes before compilation, so they are nonexistent from the perspective of binaries, but only for the sources) and declarations of various data structures and functions. these are the necessary things for an another application to use the binaries of other programs, the information held in these files are all what a compiler needs to know to make a program be able to use functionality provided in an another one, it will know what functionality is there, what kinda data structures it uses, what does each name should be resolved to, and this is true for the preprocessor macros too. these are the header files that u `#include` into ur own sources. but this will only align ur application to the interface of the other one, while the functionality of that is included in the libraries.

this means that u just dont need to mess with the "genesis" of luajit, it provides everything that u need from ur very own project. u need to include the necessary headers into ur codes, u should have the libs, and link against them. the compiler actually hides different tools and different stages of the compilation by default, but the preprocessor the compiler and the linker (and whatever else?) are different tools, u can run each stage step-by-step, and even if u want to tell the linker to use the libs, u will likely tell the same info to ur compiler, and that will tell it to ur linker. other than these, the headers and the libs should be accessible when u create ur own project, either by providing their paths, or by installing them into their respective well-known places.

i hope i didnt say anything wrong, mostly it should work like this if im not too dumb, and as i dont use w*ndos (as u could have guessed :D ) i cant give u a more specific answer, but that wasnt really my actual goal either, but to give a mental model that is reliable enough to be able to orient urself.

bests, have fun! :)

**Comment by MikuAuahDark** [comment]
I think no one mentioned this, but compile LuaJIT using `msvcbuild.bat static`. You'll have slightly big lua51.lib which you can use to link to LuaJIT without lua51.dll.
