### ISSUE TITLE
Wrong stacktrace and error message with tail-call optimization and nil value

### ISSUE THREAD

**Issue by MikuAuahDark** [LuaJIT/LuaJIT#656]
Consider this code
```lua
-- something.lua
t = {}

function t:f(b)
        return select(t[self].a, b)
end

t[t] = {}
t:f(print)
```

LuaJIT v2.1 ec6edc5c39c25e4eb3fca51b753f9995e97215da:
```
luajit: something.lua:8: calling 'f' on bad self (number expected, got nil)
stack traceback:
        [C]: in function 'f'
        new26.lua:8: in main chunk
        [C]: at 0x7ff63a544950
```

Lua 5.1.5:
```
lua5.1: something.lua:4: bad argument #1 to 'select' (number expected, got nil)
stack traceback:
        [C]: in function 'select'
        new26.lua:4: in function 'f'
        new26.lua:8: in main chunk
        [C]: ?
```

For some reason, in the stack trace, LuaJIT thinks `f` is C function, and the error message is weird too, something that I never seen. Happends both with JIT on and JIT off.

**Comment by MikePall** [comment]
The names of functions in Lua are inferred when reporting errors (see https://github.com/LuaJIT/LuaJIT/issues/614#issuecomment-684759502). There's no guarantee it will guess the right name.
With tailcalls all bets are off, because the original stack frame is already destroyed when the error happens. Also, LuaJIT internally handles tailcalls differently (more efficiently), so the outcome may differ. It's possible to construct similarly confusing cases for any version of Lua.
