### ISSUE TITLE
Microbenchmarking on Mac x64 vs. ARM64

### ISSUE THREAD

**Issue by fastcoding** [LuaJIT/LuaJIT#658]
Tested this small script below

```lua
ffi=require'ffi'
ffi.cdef[[
   uint8_t * malloc(size_t);
   void free(void*);
]]
local W=1920
local H=1080
math.randomseed(os.time())

function test()
    local t0=os.clock()   
    local p=ffi.C.malloc(W*H*3)
    ffi.gc(p,ffi.C.free)
    for i=1,W do
       for j=1,H do
          p[0]=math.random(1,255)
          p[1]=math.random(1,255)
          p[2]=math.random(1,255)
          p=p+3
	end
    end
    print(1000*(os.clock()-t0),'ms')
end
test() 
```

on 2 macbooks:
1. Retina, 15-inch, Early 2013,  2.7 GHz Quad-Core Intel Core i7
2. 13-inch, M1,2020

with JIT off, output : 
1.  	796.31    ms
2.     404        ms

with JIT on, output:
1.      37     ms
2.     67     ms

 In JIT ON case, should I expect the output to be around *20* ms for M1 chip ?

BTW, an interesting thing I noticed JIT on Apple M1, if i call test() in a loop, the 1st time it outputs ~67ms, and later, the taken time will drop down to ~37 ms. It looks like the JIT code will be further optimized after the 1st run.

-------------

There is another issue regarding FFI on M1 chip I raised on openresty weeks ago.

this script will output garbage character after *hello*, rather than the expected *world* .

```lua
local ffi=require'ffi'
ffi.cdef[[
   int printf(const char *fmt,...);
]]
ffi.C.printf("hello %s\n", "world")
```

**Comment by MikePall** [comment]
1. This script is buggy. You should modify a copy of `p` inside the loop, otherwise `p` is no longer an anchor and the finalizer may be called at any time.
2. Execution time measurements below a couple seconds (at least) are useless as a performance indicator on any modern CPU and OS. Anything in the millisecond range is purely a guess, because of the static/dynamic granularity of the system clock. Also, unless you turn off dynamic CPU frequency scaling during all measurements, the CPU could be running at anything between 100 MHz and a couple GHz ... and even slow down when it starts to overheat.
3. I'm not sure what that benchmark should measure, other than the speed of calling the internal PRNG C function. Which is not an indicator of anything useful. That particular C function is partially vectorizable, depending on the available instruction set, which further complicates any comparison.
4. Please do not mix issues, open a new one. But I can already tell you that I do not use Apple gear. Unless you find (or pay) someone else who can contribute a patch, that one will linger unresolved.

**Comment by fastcoding** [comment]
Thanks for reply, I didn't mean to benchmark LuaJIT, but rather just wanna compare the results between 2 machines, because they use the same luajit codes and different hardware.  

The actual luajit application renders a 640x480 realtime video captured from camera.  On Apple m1, it can even hardly run @10 fps, but on that old macbook with intel cpu, the app can reach 60FPS. I know m1 chip can render picture much faster than that old mac, it won't be CPU issue.  Finally I found the bottle neck is at the color conversion, similar to the script I provided above, which spend too long time. In my project, I'd solved it by replacing the loop with a C module. I asked here just for personal curiousity.

**Comment by GitSparTV** [comment]
I would suggest expose native clock function, probably it's called clock_gettime_nsec_np, you might know better.
Also try to see the difference with these changes:
localize ffi variable, localize ffi.C, localize math.random, don't use pointer arithmetics, use offset index. ([i], [i+1], [i+2])
