### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by MeirShpilraien** [LuaJIT/LuaJIT#665]
Hey, thank you for developing LuaJit.

I wanted to ask about the project status. Is it actively maintained? I see that the last release was 3 years ago, is there any plan to make a new release?
In addition, I see that 2.1 is still in beta. Is it considered stable enough to use? I am asking because I see there are many NYI (http://wiki.luajit.org/NYI) which already implemented on 2.1.

Thanks again.

**Comment by MikePall** [comment]
Look at the git v2.1 history and judge yourself. Releases are an antiquated concept. Most everyone is using v2.1, anyway.

**Comment by avih** [comment]
> Look at the git v2.1 history and judge yourself. Releases are an antiquated concept. Most everyone is using v2.1, anyway.

While the 2.1 branch has been great, and indeed I presume most people who build luajit themselves use the tip of the 2.1 branch, distributions and package managers highly dislike using git master for their builds (or, in this context, the tip of the 2.1 branch).

So we end up with distributions which use either the release version of 2.0.5, or 2.1 beta3 which is slightly newer but still nearly 5 years old, and missing many fixes and enhancements since (and users then report issues to projects which allow linking with luajit for issues which were fixed years ago in luajit).

So even a beta4 tag would go a long way, IMHO, towards making modern luajit more popular in distributions and package managers.

**Comment by kabouzeid** [comment]
He won't listen, many of us tried already. It's ridiculous

**Comment by FractalU** [comment]
@MikePall I reported to Msys2, Haiku and T2 Linux to switch from releases to the git v2.1 branch. So much to most everyone is using v2.1. I'd really appreciate if you at least clearly state in the download page that you won't do releases anymore and that everyone needs to use the latest v2.1 git branch. Currently you only recommend it while still keep providing the outdated releases.

Here the statement that you only recommend it.
> Releases are only made occasionally. You're strongly encouraged to follow the git branches.

It would be much better if you state that releases won't be done anymore and that everyone needs to use the latest v2.1 git branch as opposed to strongly encourage it. In addition, the luajit 2.1.0-beta3 and 2.0.5 releases from 2017 should be under historic releases, because they are outdated.

Furthermore, I'd suggest to remove the `beta3` from the `2.1.0-beta3` version and simply call it `2.1.0`. If luajit 2.1 is not beta anymore then it shouldn't be labeled as beta.

**Comment by joaopauloalbq** [comment]
Indeed the word 'beta' brings a very negative impression of the software. Furthermore, if _"releases are an antiquated concept"_ so naming things as 'beta' is also an antiquared concept. How about renaming the `v2.1.0-beta3` tag to `v2.1` only and from there the software would be distributed as `v2.1.<number_of_additional_commits_on_top_of_the_tagged_object>` ?

```
$ git describe | sed 's/-g.*//' | sed 's/-/./'
$ v2.1.493
```

**Comment by kabouzeid** [comment]
He won't listen to reason

**Comment by FractalU** [comment]
I personally would just call it version `2.1` and for the `v2.0` branch version `2.0`. There is already a git issue for appending a commit hash to the version number. See https://github.com/LuaJIT/LuaJIT/issues/711.

**Comment by MikePall** [comment]
@FractalU Done by switching to rolling releases.
