### ISSUE TITLE
Issue with getentropy and App Store

### ISSUE THREAD

**Issue by MoNTE48** [LuaJIT/LuaJIT#668]
> ITMS-90338: Non-public API usage - The app references non-public symbols in ***: _getentropy. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

https://github.com/LuaJIT/LuaJIT/commit/570e758ca7dd14f93efdd43d68cf8979c1d7f984#diff-11fdc83eeaa7032904efe2cb664a276453eb1cf8efcc8880cb69b61a3ad9763f

**Comment by MikePall** [comment]
Errr ... Apple docs present `getentropy()` as the preferred way to get trusted random numbers for iOS:
https://support.apple.com/guide/security/random-number-generation-seca0c73a75b/web
So, why on earth would they not allow using this in an app? That's an insane policy and should be called out on an Apple forum.

Please escalate it there -- I can't do anything about it. I'm not willing to back down on generally recommended security practices.

**Comment by MoNTE48** [comment]
Well, I had to modify the code to set `#define LJ_TARGET_HAS_GETENTROPY=0`. After that, my build was immediately accepted and approved.
I am asking to be able to install this via CFlags, because patches complicate my build system!

**Comment by MoNTE48** [comment]
@MikePall, as the forum said, this is a really private API and Apple does not mention it anywhere in the developer documentation. And indeed, I have checked the documentation. Not a word about using `getentropy()` by third party apps...
Please, make using `getentropy()` optional and configured by compilation flags for iOS/macOS.

**Comment by corsix** [comment]
I don't see anything insightful in those forum comments; just random people trying to draw inferences from nothing. One potential source of insight is what other people/projects do, which seem to point at `SecRandomCopyBytes` for iOS:

1. Docs at https://docs.rs/getrandom/0.2.2/getrandom/ and source at https://docs.rs/crate/getrandom/0.2.2/source/src/ios.rs
2. https://www.mikeash.com/pyblog/friday-qa-2011-03-18-random-numbers.html

**Comment by MikePall** [comment]
Sigh. I really wonder why I still bother to dance around every single instance of Apple eccentricity. I guess my next project will have an: `#if __APPLE__ #error "Buy a computer you really own" #endif`

Anyway, if you disable `getentropy()` you'll just get `/dev/urandom` ... which apparently works on iOS? Otherwise LuaJIT wouldn't even start up.

Can you please confirm that after your change it does access `/dev/urandom` and starts up correctly on iOS (in the released app, not just in developer mode)? Then I can simply disable `getentropy()` for iOS.

Not keen on linking to frameworks for something which is a one-line wrapper around a syscall. A publicly documented cross-platform syscall used by all modern BSD-like operating systems, mind you.

**Comment by MoNTE48** [comment]
Well, on iOS, we either play by the rules or buy Android.
(For me personally, Pure Android like Pixel looks not enough, Samsung or any other looks too bloatware-overloaded. Buying a phone for ~$1000 to disable protection, hack and install Custom ROM – I appreciate my time...)
On macOS, we have ample freedom. Perhaps modifying system files gets harder with each release, but it's still better Windows for me.

> Can you please confirm that after your change it does access /dev/urandom and starts up correctly on iOS (in the released app, not just in developer mode)? Then I can simply disable getentropy() for iOS.

**Yes, my app with `#define LJ_TARGET_HAS_GETENTROPY=0` has been in the App Store for 2 days and I have 80k+ sessions according to analytics. It's okay with that.**

> A publicly documented cross-platform syscall used by all modern BSD-like operating systems, mind you.

Well, I am a developer of a fairly popular application and I think I can try to get an official answer from Apple. But again – I value my time and I think the answer will be exactly the same as on the forum – this is a private API, do not use it... 🙁

**Comment by MoNTE48** [comment]
![image](https://user-images.githubusercontent.com/6764600/110044370-4c3bbc80-7d49-11eb-9619-800e302185f7.png)
![image](https://user-images.githubusercontent.com/6764600/110044404-5cec3280-7d49-11eb-9105-fa7dadc2b89f.png)
Well, in so many years I have never tried this. My English is terrible and if anyone can help with a description of the problem, I'll just post it to Code-Level Support.

**Comment by MikePall** [comment]
Since we seem to have no choice, I've disabled `getentropy()` use for iOS.

**Comment by wyattoday** [comment]
Just FYI, Apple does have a public API since iOS 8.0 and macOS 10.11: `CCRandomGenerateBytes()`

Here are a couple of examples:

https://github.com/wyday/mod_cspnonce/commit/f5c6bf06b7df1bb4da224dfc8b7224373b090827

https://github.com/weidai11/cryptopp/pull/1135

Yes, their `getentropy()` policy is confusing and conflicts with their docs.
