### ISSUE TITLE
Linux/ARM64 memory reallocation failure

### ISSUE THREAD

**Issue by raymond-w-ko** [LuaJIT/LuaJIT#671]
While trying to compile neovim I ran into this issue: https://github.com/neovim/neovim/issues/13760. The root cause appears to be when luarocks tries to `loadstring()` it's main manifest file after unzipping. The manifest file is itself Lua code and can be considered fairly large at around 1MB. neovim builds LuaJIT with assertions (`-DLUA_USE_ASSERT` and `-DLUA_USE_APICHECK`) enabled and when `luarocks` try to install `mpack`, it crashes with:
```
LuaJIT ASSERT lj_gc.c:863: lj_mem_realloc: allocated memory address 0xffffb7a0b010 outside required range
```

Isolated test case here: https://github.com/raymond-w-ko/luajit-aarch64-crash-test-case

I confirmed this is also happening on LuaJIT v2.1 HEAD, while neovim internally uses a slightly older release (but after 2.1.0-beta3).

**Comment by MikePall** [comment]
This seems to be a general problem in the Linux kernel, which hits us on AArch64.

Although the kernel respects address hints to `mmap()` to stay within the 47-bit VA space required by LuaJIT, it happily moves an allocation outside the originally hinted-at space with `mremap(..., MREMAP_MAYMOVE)`. The optional fifth parameter to `mremap()` would theoretically provide such a new address hint, but the kernel code ignores it!

It only honors the new address for `MREMAP_FIXED`, but this does something very different (and dangerous for a general-purpose library). That's also kind of an API problem, because AFAIR the fifth parameter was originally not present and thus has to be considered undefined, if that flag is not set (which was the reason for adding the parameter).

Actually, they *do* limit the default VA space they hand out to userspace. But for whatever reason they decided to limit it to an 48-bit VA space. This misses the mark by 1 bit, since LuaJIT needs to allocate from the low 47-bit VA space. If they just had used that, we wouldn't have to do this randomized allocation hinting dance at all. Ditto for the recently added `lightuserdata` segmentation craziness, caused by stack pointers outside that space.

So I guess we have no choice but to incur a (sometimes drastic) performance-downgrade on Linux/AArch64 by disabling `MREMAP_MAYMOVE`. Could you please try again after applying the following change in `lj_alloc.c` at line 368:

```diff
-#if LJ_64 && !LJ_GC64
+#if LJ_64 && (!LJ_GC64 || LJ_TARGET_ARM64)
 #define CALL_MREMAP_MV         CALL_MREMAP_NOMOVE
 #else
 #define CALL_MREMAP_MV         CALL_MREMAP_MAYMOVE
 #endif
```

**Comment by raymond-w-ko** [comment]
I can confirm that this fixes it. Thanks Mike.

**Comment by MikePall** [comment]
Applied. Thanks!
