### ISSUE TITLE
Sqrt(x) and x^0.5 not interchangeable

### ISSUE THREAD

**Issue by XmiliaH** [LuaJIT/LuaJIT#684]
There are inconsistencies between sqrt(x) and x^0.5 (at least on x64 platforms). These include:

val | sqrt(val) | val ^ 0.5
--- | --- | ---
-0.0 | -0.0 | 0.0
-inf | nan | inf
2921.0 | 0x1.b05ec632536fbp+5 | 0x1.b05ec632536fap+5

However, the fold rule `simplify_numpow_xknum` assumes that these are interchangeable as can be seen in the following example:
```lua
function test_sqrt(num)
    local p, s
    for i = 1, 1000000 do
        p, s = num ^ 0.5, math.sqrt(num)
    end
    print(string.format("(%a) ^ 0.5 = %a optimized %a", num, num ^ 0.5, p))
    print(string.format("math.sqrt(%a) = %a optimized %a", num, math.sqrt(num), s))
end
test_sqrt(-0.0)
test_sqrt(-(1/0))
test_sqrt(2921.0)
```
which outputs for me (x64):
```
(-0x0p+0) ^ 0.5 = 0x0p+0 optimized -0x0p+0
math.sqrt(-0x0p+0) = -0x0p+0 optimized -0x0p+0
(-inf) ^ 0.5 = inf optimized nan
math.sqrt(-inf) = nan optimized nan
(0x1.6d2p+11) ^ 0.5 = 0x1.b05ec632536fap+5 optimized 0x1.b05ec632536fbp+5
math.sqrt(0x1.6d2p+11) = 0x1.b05ec632536fbp+5 optimized 0x1.b05ec632536fbp+5
```
The after the JIT kicks in the values of `x ^ 0.5` change to what `math.sqrt(x)` returns.

Similar happens for the `simplify_numpow_xkint` rule and `x ^ 3` with a value of `-0x1.cf148p+19` for x.
```
x = (-0x1.cf148p+19); x * x * x = -0x1.7ad0e8ad7439cp+59 optimized -0x1.7ad0e8ad7439cp+59
(-0x1.cf148p+19) ^ 3 = -0x1.7ad0e8ad7439dp+59 optimized -0x1.7ad0e8ad7439cp+59
```

**Comment by phillip-mcnallen-tfs** [comment]
Aren't these different things?  
I'm assuming math.sqrt generates a SQRTPD instruction
While X^0.5 generates a vastly different assembly, which is usually numerous instructions for an exponential operation.

**Comment by corsix** [comment]
> Aren't these different things?

You can answer either "yes" or "no" to this question, but there's a (different) bug here either way. If they _are_ different things, then the JIT shouldn't be substituting one for the other, as JIT compilation should affect performance of code but not the computational results. If they _aren't_ different things, then they should give the same result.

**Comment by MikePall** [comment]
This seems to be dependent on the implementation of `pow()` in the system or toolchain math library, too:
* glibc returns different results for the `(-0.0)^0.5` case and the `(-inf)^0.5` case.
* glibc returns identical results for the `2921^0.5` case and the `-0x1.cf148p+19` case (checked with `%a` format).

OK, so what alternatives do we have?
1. Drop the `x^0.5 -> sqrt` fold rule: well, maybe ... since anyone who cares about performance could be convinced to write `math.sqrt(x)`.
2. Drop the `x^k -> unrolled MUL` fold rule: not such a good idea, since many developers write `(complicated_expression)^2` or `^3` to avoid an extra variable.
3. Add all/many of those special cases to the `^` operator in the interpreter to match the JIT compiler fold rules: this leads to the inverse consistency problem when one of the JIT fold rules fail or folding is turned off.
4. Add all/many of those special cases to the `^` operator implementation in the interpreter, call the C function directly from the JIT compiler and drop all fold rules. Considering that many math libraries already do the special casing internally in `pow()`, that's not better than simply dropping all fold rules.

Something to consider: `[MUL a a]` or `[FPMATH a sqrt]` creates substantially better inlined code (1 instruction) than `[CALL pow (x y)]` ever could. Also, the inlined instructions don't need to spill any registers.

**Comment by XmiliaH** [comment]
How about:

5. Add all/many of those special cases to the `^` operator implementation in the interpreter, call this implementation from the JIT compiler if the fold rules fail. This should solve the inverse consistency problem and still allows the optimizations.

**Comment by phillip-mcnallen-tfs** [comment]
> 1. Drop the `x^0.5 -> sqrt` fold rule: well, maybe ... since anyone who cares about performance could be convinced to write `math.sqrt(x)`.

^ I like this one because its easy

There's another perspective here, which is: does it matter?  Both of the results is a 'correct' result.  While the answer to whether it matters is dependent on a case-by-case basis, in many cases the difference would be unimportant.

And where it does matter, maybe changing the `pow()` implementation and building with static libc is a palatable solution?

**Comment by farteryhr** [comment]
we may formulate it like this:

only `+,-,*,/,sqrt` are deterministic. (my humble conclusion in some limited investigation about floating point determinism, across more platforms, if limited to `double`)

(for completeness, maybe also trivial ones like `neg, sign, floor, ceil, round, trunc`) (also need to get rid of any intrinsic like FMA and be aware of x87 80-bit double-rounding and always keep correct rounding flags so on...)

other transcendental functions, like `exp(m1), log(1p), pow, [trig funcs]`, or maybe not, like modulo, cube root, hypot, are all implementation defined, i.e. no warranty.

if the code called `x^0.5` which is synonym of `pow(x, 0.5)`, it's out of warranty. so we can substitute it with `sqrt(x)`. we can't for example do it backwards, substitute a `sqrt(x)` with `x^0.5`.

in fact the same also applies for x^2, x^3.

**Comment by MikePall** [comment]
I've opted to a mixture of the possible options: sqrt optimization dropped, limit integer unroll, always call internal function before delegating to toolchain-provided pow, consistency between interpreter and JIT-compiled code.

**Comment by appgurueu** [comment]
I would have preferred the fold rule be kept. I do not (and should not) care about the sign of a zero. I do not (and should not) care about the square root of negative infinity. I do not (and should not) care which of two equally good approximations to a square root I get [^1].

I see no guarantee that would be broken by keeping this optimization, and I also have a hard time imagining sensible code that breaks. The behavior of `sqrt` is as sensible if not more sensible than that of `x^0.5` shown here.

Now I have to remember this performance oddity and use a more verbose notation if I care about performance, whereas on PUC Lua 5.4, even if `math.sqrt` is localized, it is still slower.

The assumption that performance-wise `x^0.5` is at least as good (given a strong optimizing implementation like LuaJIT) as `math.sqrt(x)` since they are mathematically equivalent and the former provides the implementation with stronger guarantees turns out wrong by an order of magnitude. I think that is probably worse.

[^1]: `math.abs(0x1.b05ec632536fbp+5*0x1.b05ec632536fbp+5 - 2921) == math.abs(0x1.b05ec632536fap+5*0x1.b05ec632536fap+5 - 2921)`
