### ISSUE TITLE
FreeBSD platform compatibility

### ISSUE THREAD

**Issue by n-ham** [LuaJIT/LuaJIT#687]
I tried updating the version of LuaJIT for my project [Nift](https://nift.dev) after the brew folks were a bit snarky about me using the website beta release. However I first came across problems with Snap then only building for i386 and not even amd64 or arm[64/hf]. I also then got a PR from the person who does the Gentoo and FreeBSD releases patching LuaJIT because it broke there too. 

I figured it might be worth mentioning along with [this](https://github.com/nifty-site-manager/nsm/pull/29) PR that might help identify the issue with Gentoo/FreeBSD, I'm not sure if the patch will help at all with amd64 and arm[64/hf] sorry.

**Comment by n-ham** [comment]
Nift has an in-built LuaJIT shell you may find kind of useful too (`nift sh luajit` or `nift interp luajit` for no pwd), it has a nice colourful prompt with pwd and attempts to run anything luajit can't as a system call (so bash statement), I tend to use the default (functionstein) shell extension quite a lot which can also run luajit code(blocks). [These](https://github.com/nifty-site-manager/project-euler/tree/master/3) project euler problems show how to use luajit natively and with fnstein with Nift to solve problem 3 of project euler.

**Comment by MikePall** [comment]
FreeBSD is not an officially supported target. I'm not doing any testing on it.

The latest LuaJIT git version supposedly works on the latest FreeBSD, but that's about all I know. I have no plans to add fixes for older versions.

As for other architectures: show me the compile errors and/or contribute a fix.

**Comment by n-ham** [comment]
It was amd64 that worked not i386 my mistake. 

I copied the build logs from snapcraft:

arm64: https://pastebin.com/SiSUuZXR
armhf: https://pastebin.com/3aXWLe8X
i386: https://pastebin.com/hAZTHbTN

I know neither how the different architectures or luajit work well enough to tinker around with it myself sorry, was just trying to report the issues I came across when trying to update to a more recent beta release. 

I don't tend to test with FreeBSD either, just work with the person who does releases when there's an issue, so I'll let other people worry about any LuaJIT issues with FreeBSD.

**Comment by MikePall** [comment]
No, the problematic lines are these:
```
make[2]: Entering directory '/build/nift/parts/nsm/build/LuaJIT/src'
BUILDVM   lj_vm.S
make[2]: host/buildvm: Command not found
```
It shouldn't ever get to that point without building `host/buildvm` first. A usual compile log starts with `DYNASM` and `HOSTCC` lines. This means something is completely wrong with the dependencies. Or maybe you packed up a final build (for a different architecture) without running `make clean` first?
And, yes, LuaJIT itself builds fine with a parallel `make -j<whatever>`.

What is it pulling here?
```
Pulling nsm 
+ snapcraftctl pull
[11/Apr/2021:06:54:37 +0000] "CONNECT raw.githubusercontent.com:443 HTTP/1.0" 200 3885765 "-" "-"
Downloading 'nsm.zip'
```
Because the size does not match any of the public GitHub releases, which are much smaller.

Also, that's not about FreeBSD anymore? This is the log of a plain Ubuntu native build. This should not fail, since I'm testing on this, too.
