### ISSUE TITLE
GCStr sid is increase linear when STRID_RESEED_INTERVAL is not set 

### ISSUE THREAD

**Issue by CatDroid** [LuaJIT/LuaJIT#696]
set  LUAJIT_SECURITY_STRID = 0 and then STRID_RESEED_INTERVAL is not set 

file  lj_str.c  
methon  GCstr *lj_str_alloc  
s->sid = g->str.id++;  // sid is increased one by one 

file lj_tab.c
#define hashstr(t, s)		hashmask(t, (s)->sid)

that is, 
when table's key is String （e.g  local tbl = {}  tbl["key"] = 123） , 
then it will use 'sid' as the key of table , instead of GCStr.hash （which just depends on the string literal ）

so  I want to know whether it's ok to change " hashstr hashmask(t, (s)->sid)"  to "hashstr(t, s)		hashmask(t, (s)->hash)" ?

the old version(without security, maybe 2017), it use hash as hashkey of table.

**Comment by MikePall** [comment]
Umm, why do you change an internal VM security setting, if you don't understand what it does? That's a very bad idea.

The only place that even talks about these settings is `lj_arch.h`, which clearly tells you that setting the security level to 0 (i.e. ZERO = NO SECURITY), then, yes, the string IDs are linear. And no, you cannot swap `->sid` and `->hash`, because the hash can change during the lifetime of the string.

Taken together with your last question in #693, it's clear that you have not understood the issue at hand. Table iteration order is NOT DEFINED in Lua. As the FAQ says:

> **If your program relies on a deterministic order, IT HAS A BUG. Rewrite it, so it doesn't rely on the key order.**
