### ISSUE TITLE
fix the result order of  calling  pairs() function

### ISSUE THREAD

**Issue by continue567** [LuaJIT/LuaJIT#702]
how can i modify the code in LuaJIT so that every time creating a table with the same content, i can get the same result?
![image](https://user-images.githubusercontent.com/20896273/118912033-c26bba80-b959-11eb-89ae-15e6cea43bae.png)
![image](https://user-images.githubusercontent.com/20896273/118912052-c8fa3200-b959-11eb-9a20-e7a0eab70a23.png)

**Comment by XmiliaH** [comment]
The order in which `pairs` returns the entries in **undefined** as stated in https://luajit.org/faq.html#order. Instead of changing LuaJIT to make this defined you should change your program to not rely on the order in which `pairs` returns the entries. This can be achieved by reading all the keys and sorting them before iterating over the sorted keys and their values.
If you know that the  keys are all strings the following code could be used:
```Lua
local pairs, sort = pairs, table.sort

local function foreach_sorted(map, cb)
    local keys = {}
    local i = 0
    for k in pairs(map) do i = i + 1; keys[i] = k end
    sort(keys)
    for j = 1, i do
        local k = keys[j]
        cb(k, map[k])
    end
end

local tbl = {aa=1,bb=2,ab=3}

foreach_sorted(tbl, print)
```
