### ISSUE TITLE
[Question] Is FFI possible on platforms where JIT is not available?

### ISSUE THREAD

**Issue by LeanderBB** [LuaJIT/LuaJIT#724]
Hello!

I'm trying to investigate whether, on platforms where JIT is not available (e.g: iOS), we can still use FFI.

From what I've gather from the current defines in` lj_arch.h` iOS does not have any defines to disable FFI. Yet in your online documentation and in the same header, FFI is disable for console platforms. 

Is this a general limitation or does FFI only work with certain platforms without JIT?

**Comment by MikePall** [comment]
While JIT x FFI x Console are three orthogonal concerns ...
1. iOS and consoles do not allow running machine code created at runtime.
2. iOS and consoles restrict library loading and symbol resolving at runtime.
3. The JIT compiler needs to create machine code at runtime.
4. The FFI is quite slow without the JIT compiler.
5. The FFI is quite limited without being able to load libraries and resolve symbols at runtime.
6. The FFI callback feature needs to create machine code at runtime.

That's why the FFI is disabled on iOS and consoles.
