### ISSUE TITLE
Q: Can 64 bit luajit produce byte code for a 32 bit target?

### ISSUE THREAD

**Issue by JCash** [LuaJIT/LuaJIT#725]
Hi!

I'm currently in the process of upgrading to the latest luajit version, and I'm finding some of our current usage to be somewhat strange. Our use case is that we provide a luajit for one platform (say macOS) and can compile byte code for another (e.g. armv7-android)

In our setup, we have two luajit's, one for 32-bit targets and one for 64-bit). Both executables are 64 bit (macOS).
The difference is that the luajit-64 is compiled with `-DLUAJIT_ENABLE_GC64` (for the currently released beta version).

And when generating the byte code output, the sizes of the files are the same, only a few bytes differ.

What are these bytes representing, and is there a way for me to only have _one_ executable (as opposed to two)?

Any insights are helpful. Thanks!

Regards,
Mathias

Example:
```patch
--- a/test3-32.luac.hex
+++ b/test3-64.luac.hex
@@ -1,6 +1,6 @@
-00000000: 1b4c 4a02 0009 7465 7374 332e 6c75 616b  .LJ...test3.luak
-00000010: 0200 0400 0401 0a0f 000f 3600 0000 2701  ..........6...'.
-00000020: 0100 4200 0202 3901 0200 2902 0300 2903  ..B...9...)...).
+00000000: 1b4c 4a02 0809 7465 7374 332e 6c75 616b  .LJ...test3.luak
+00000010: 0200 0500 0401 0a0f 000f 3600 0000 2702  ..........6...'.
+00000020: 0100 4200 0202 3901 0200 2903 0300 2904  ..B...9...)...).
 00000030: 0400 4201 0302 1601 0001 3701 0300 4b00  ..B.......7...K.
 00000040: 0100 0f67 6c6f 6261 6c76 6172 3109 6675  ...globalvar1.fu
 00000050: 6e63 1569 6e69 745f 7363 7269 7074 2e69  nc.init_script.i
 ```

**Comment by GitSparTV** [comment]
That byte is a flag indicating the bytecode is using FR2 (Frame Size 2). Basically it means on 64-bit systems it actually stores 2 values in one TValue structure due to the size.
Mike planned to make 32 and 64 bits compatible.
I'm sure you can't just remove that flag, I didn't find any code that behaves different on FR2

**Comment by JCash** [comment]
Thanks for the quick response @GitSparTV !

> I'm sure you can't just remove that flag, I didn't find any code that behaves different on FR2

These two statements seem to contradict themselves. Did you mean "I'm sure you can just" ?

**Comment by GitSparTV** [comment]
No. Well, try it, but it's weird that LuaJIT restricts you from loading incompatible bytecode and you just bypass it by removing that flag

**Comment by JCash** [comment]
Ok, I'll to try it, but I'm pretty sure my previous colleague already did test it all those years ago and it's the reason why we currently have two executables. The question is if anything has changed for the better.

Currently I've tried to build the 64-bit macOS version with `LUAJIT_DISABLE_GC64=1` but then the vanilla version complains that it needs 64 bit on macOS, and just removing that warning didn't work (it cannot create a lua state due to mmap_map32), so that seems like a precarious road to go down on.

What about abi-compatibility, can I use the luajit from beta3 release, to use with the new luajit libraries?

**Comment by GitSparTV** [comment]
LuaJIT 2.x and 3.x bytecodes are not compatible for sure.
I think I just never encountered misaligned 64-bit TValue, so removing the flag worked

**Comment by XmiliaH** [comment]
The LuaJIT bytecode created from 32 bit and 64 bit executables are different. This is due to the larger pointer size. The difference can be seen here:
*64 bit:*
https://github.com/LuaJIT/LuaJIT/blob/3f9389edc6cdf3f78a6896d550c236860aed62b2/src/lj_frame.h#L34-L38
*32 bit:*
https://github.com/LuaJIT/LuaJIT/blob/3f9389edc6cdf3f78a6896d550c236860aed62b2/src/lj_frame.h#L53-L58
The 64 bit version needs 2 slots in front of base while the 32 bit version only uses 1.
Inspecting the x64 and x86 interpreter shows the same:
**CALL:**
Note the different offset calculated in `lea BASE, [BASE+RA*8+...] `
*64 bit:*
https://github.com/LuaJIT/LuaJIT/blob/3f9389edc6cdf3f78a6896d550c236860aed62b2/src/vm_x64.dasc#L3973-L3981
*32 bit:*
https://github.com/LuaJIT/LuaJIT/blob/3f9389edc6cdf3f78a6896d550c236860aed62b2/src/vm_x86.dasc#L4682-L4691
**RET:**
Note the different offset in the move, the 64 bit version moves to `BASE-16` while the 32 bit version to `BASE-8`.
*64 bit:*
https://github.com/LuaJIT/LuaJIT/blob/3f9389edc6cdf3f78a6896d550c236860aed62b2/src/vm_x64.dasc#L4243-L4245
*32 bit:*
https://github.com/LuaJIT/LuaJIT/blob/3f9389edc6cdf3f78a6896d550c236860aed62b2/src/vm_x86.dasc#L5020-L5029

On 64 bit the parser/compiler adds the extra slot beneath the arguments passed to a function. If this bytecode would be loaded in a 32 bit environment the extra slot would be unexpected and interpreted to hold the first parameter, while the actual first will be passed as the second and the last be discarded.
While it would be possible to patch the 32 bit version to understand the extra slot this would need at least changes in the interpreter `vm_x86.dasc`.

**Comment by JCash** [comment]
@corsix In my case, I have two 64-bit executables on macOS (also on linux/win)
One is built with GC64, the other isn't ([build_script here](https://github.com/defold/defold/blob/dev/share/ext/luajit/build_luajit.sh#L158-L170))

@GitSparTV 
>LuaJIT 2.x and 3.x bytecodes are not compatible for sure.

I'm using the 2.1 branch, I'm assuming that's still LuaJIT 2.1 bytecode? (all version number I've seen seem to say 2.1 at least)

> I think I just never encountered misaligned 64-bit TValue, so removing the flag worked
Which flag are we talking about here exactly?

**Comment by corsix** [comment]
> @corsix In my case, I have two 64-bit executables on macOS (also on linux/win)

Not sure why you're mentioning me?

**Comment by GitSparTV** [comment]
> I'm using the 2.1 branch, I'm assuming that's still LuaJIT 2.1 bytecode? (all version number I've seen seem to say 2.1 at least)

Sorry, I meant 2.0.x and 2.1.x not being compatible

**Comment by JCash** [comment]
@corsix I'm so sorry!

I meant to tag @XmiliaH :)

**Comment by XmiliaH** [comment]
With the xx bit I meant how many bits the GC pointers have. You can have GC64 or GC32 on 64 bit platforms. If you use GC32 on x64 LuaJIT still uses the `vm_x86.dasc` interpreter.

I'm sorry if that didn't came across on my previous post.
