### ISSUE TITLE
[2.0.5] io.close on a closed file results in a segfault

### ISSUE THREAD

**Issue by farmboy0** [LuaJIT/LuaJIT#735]
This script https://github.com/farmboy0/luaj/blob/cleanup/luaj-test/src/test/resources/compatibility/iolib.lua
will cause a segfault when line 152 https://github.com/farmboy0/luaj/blob/76ef5c794610572454641dab1b92cd83b88e3606/luaj-test/src/test/resources/compatibility/iolib.lua#L152
is commented in.

**Comment by GitSparTV** [comment]
Use 2.1

**Comment by MikePall** [comment]
Fixed in both v2.0 and v2.1. Thanks!

**Comment by fperrad** [comment]
in https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lib_io.c#L67, I think that the error message must `LJ_ERR_IOCLFL` ("attempt to use a closed file") instead of `LJ_ERR_IOSTDCL` ("standard file is closed").
It is never a "real" standard file, because trying to close a standard throws an error ("cannot close standard file"), see https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lib_io.c#L115

**Comment by MikePall** [comment]
OK, I've changed the error message. Thanks!
