### ISSUE TITLE
How hard is to create a new debug function like debug.createLocal

### ISSUE THREAD

**Issue by yamaken93** [LuaJIT/LuaJIT#741]
How hard/problematic is to create a function like debug.createlocal(2, "localvariablename") which returns the local variable index so  i can use it in debug.setlocal like debug.setlocal(2, index, value). I don't want this to be added to the main luajit project, i can maintain it in a fork.

**Comment by GitSparTV** [comment]
It's easy to create a function but does it have sense? How createlocal would work?

**Comment by yamaken93** [comment]
its create a new local variable for that level/function. I want to make a automated require system for modules where the module return table members can be created as local values so we have access to all functions and values locally like when we import stuff in python or javascript.

**Comment by GitSparTV** [comment]
It's impossible because local stack indexes are known at the compile time and they are used in the bytecode, you can change the value of the local but adding a new local won't do anything besides instant GCing (because unused).
If you create a local at runtime bytecode doesn't know that and `module.key` will either be "Get global `module`, store at index 0" -> "Get Field `key` from index 0 and store in index 1"
