### ISSUE TITLE
x86_64 LuaJIT Unwind  receive SIGSEGV

### ISSUE THREAD

**Issue by libing0526** [LuaJIT/LuaJIT#748]
1，On a Linux 64 bit machine, I used the heap check of gperftools to analyze the memory of my program, but unfortunately, it always crashes, and the crash stack is displayed in unwind-dw2. C of GCC (GCC 4.9.4)
![image](https://user-images.githubusercontent.com/52499845/135200288-f63b8583-2866-4895-8355-b534c1701b99.png)

2，GCC does not parse inline assembly, so adjusting SP in inline assembly often results in imprecise CFI。so，i think is a known problem，Does luajit not support the heap check of gperftools?

**Comment by MikePall** [comment]
JIT-compiled code does not have associated static unwind info. But it does have an installed unwind handler, which always catches. This works for regular stack unwinding, but not for backtraces. 

One would have to either limit the depth of the backtrace or stop unwinding before it hits such a frame. The code to look for is the callback passed to `_Unwind_Backtrace()`.

It's probably easier to not override the LuaJIT allocator to prevent the profiler from intercepting these calls. Whatever it might derive for those allocations likely wouldn't be very interesting without diving deep into the VM internals.

FYI: Putting screenshots of code in issue trackers is generally discouraged, because it's not possible to search or cut'n'paste the code. Please always use Markdown code blocks. Thank you!

**Comment by libing0526** [comment]
Mike pal, thank you for your answer. I'm trying to use libunwind library instead of GCC_ Unwind_ Backtrace, everything is working properly.

_ Unwind_ Backtrace does not seem to determine whether the stack frame is valid, so when backtracking to JIT compiled code, illegal address access is generated.

However, in the libunwind library, it checks the validity of stack frames.
