### ISSUE TITLE
CSE over IR_RETF with REF_BASE

### ISSUE THREAD

**Issue by XmiliaH** [LuaJIT/LuaJIT#784]
The guard https://github.com/LuaJIT/LuaJIT/blob/1d20f33d2905db55fb7191076bbac10f570f9175/src/lj_record.c#L1779-L1781 allows for CSE of `uref - REF_BASE`. This becomes a problem when there is a `IR_RETF` instruction in between since it will change the value of `REF_BASE`.
The following example demonstrates the issue:
```lua
-- jit.off()

local function exit_with_retf(c)
    -- Force stich.
    string.find("", ".")
    -- Call the closure so that we have emitted uref - REF_BASE.
    c(0)
    -- Exit with IR_RETF. This will change REF_BASE.
    return c

end

local function func(c)
    local up
    if c == nil then
        c = function (val)
            local old = up
            up = val
            return old
        end
        -- First create a trace where the open upvalue is always < REF_BASE.
        func(c)
    end
    for i = 1, 10000 do
        c = exit_with_retf(c)
        up = 1
        -- The open upvalue guard will use CSE over IR_RETF for uref - REF_BASE.
        -- This will result in wrong results since IR_RETF will change the value of REF_BASE.
        up = c(0)
    end
    return up
end

print(func())
```
Expected output `1` but with JIT it is `0`.

**Comment by MikePall** [comment]
The 'SSA-correct' way to fix this would be to completely overhaul the frame handling. Use the `RETF` result instead of `BASE` and also avoid the implicit base ref in `SLOAD`. But that would cause major changes for the IR and all backends.

I've opted for the simpler fix of preventing CSE of `BASE` refs across `RETF`. Fortunately, there are only a few variations of this.

Fixed. Thanks!
