### ISSUE TITLE
Issue with narrowing

### ISSUE THREAD

**Issue by ernstmoritzhahn** [LuaJIT/LuaJIT#800]
If I run this program

```
local ffi = require("ffi")
for i=1,200000000 do
  local a = (i % 2 == 0 and 1 or 0)
          + (i % 3 == 0 and 1 or 0)
	  + (i % 5 == 0 and 1 or 0)
	  + (i % 7 == 0 and 1 or 0)
	  + (i % 11 == 0 and 1 or 0)
	  + (i % 13 == 0 and 1 or 0)
	  + (i % 17 == 0 and 1 or 0)
end
```
with
`time luajit -jdump test1.lua | grep TRACE`
I get
```
...
---- TRACE 149 stop -> interpreter
real	0m5.465s
```
Thus, there are quite a number of traces generated. I tried to avoid this using the following program which does not use Booleans:
```
local ffi = require("ffi")
local bit = require("bit")
local bit_rshift = bit.rshift

function is_mod_zero(number, mod)
  local a = number % mod
  a = -a
  a = bit_rshift(a, 31)
  a = 1-a
  return a
end
for i=1,200000000 do
  local a = is_mod_zero(i, 2)
          + is_mod_zero(i, 3)
          + is_mod_zero(i, 5)
          + is_mod_zero(i, 7)
          + is_mod_zero(i, 11)
          + is_mod_zero(i, 13)
          + is_mod_zero(i, 17)
end
```
Running this with
`time luajit -jdump test2.lua | grep TRACE`
I get
```
...
---- TRACE 130 stop -> interpreter
real	0m9.883s
```
which has slightly less traces but is even slower. However, if I instead use
`time luajit -jdump -O-narrow test2.lua | grep TRACE`
to disable number narrowing, I get
```
...
---- TRACE 2 stop -> loop
real	0m0.204s
```
and thus the number of traces is smaller and the program runs faster.

I do not really know this happens. I think however that this might be a relevant issue, in particular because it is encouraged to reduce the number of unpredictable branches using bit operators
http://wiki.luajit.org/Numerical-Computing-Performance-Guide, "Reduce number of unbiased/unpredictable branches."
which does not seem to work reliable at least in this case if narrowing is enabled.

**Comment by XmiliaH** [comment]
This seems to be caused by `-a` since this might result in `-0` which is not representable with int.

You could change `is_mod_zero` if not already done to:
```lua
function is_mod_zero(number, mod)
  local a = number % mod
  a = bit_rshift(a-1, 31)
  return a
end
```

**Comment by ernstmoritzhahn** [comment]
Thank you! This works:
```
---- TRACE 2 stop -> loop
real	0m0.070s
```
I still wonder why the failure of number narrowing would lead to the large number of traces being generated - sorry if this is not an issue.

**Comment by XmiliaH** [comment]
The large number of traces are generated due to the `a = -a`. LuaJIT will install a guard which checks that `a` is not `0` before doing the negation (presumably since double values can represent `0` and `-0` and this might be lost). Since the code will often hit the case that `a` is `0` side traces will spawn.

**Comment by ernstmoritzhahn** [comment]
OK, thank you. So I assume that this is expected behaviour such that I should close the issue then?

**Comment by XmiliaH** [comment]
While I think this is expected behavior it might be improved (though this seems to be hard to do).

**Comment by MikePall** [comment]
Note 1: The very low execution time is due to the expression being completely eliminated (`a` is local to the loop) -- which probably doesn't happen for any realistic use case.
Note 2: The modulo operator is a floating-point operator in Lua. It's slow by definition.
Note 3: The multiplicative-inverse optimization might still work, but only under quite limited circumstances. So far, there hasn't been any demand from real-world use cases, which is why I have no plans to implement it.
