### ISSUE TITLE
Allow coroutine.isyieldable to be used outside of a coroutine

### ISSUE THREAD

**Issue by nikneym** [LuaJIT/LuaJIT#825]
Currently `coroutine.isyieldable` implementation takes no arguments, it just checks if the running thread is yieldable or not. This leads following code to output `false` on LuaJIT but `true` on Lua 5.2+(?? tested on Lua 5.4.4 though)
```lua
local test = coroutine.create(function()
  coroutine.yield("test")
end)

print(coroutine.isyieldable(test))
```

**Comment by MikePall** [comment]
Given the execution model of Lua coroutines, why would this be helpful? One can only yield from the currently executing coroutine, anyway.

`coroutine.yield()` simply doesn't have a thread parameter. And the C equivalent must only be used on the currently executing coroutine (otherwise this is a misuse of the Lua/C API and will likely crash the VM).

**Comment by MikePall** [comment]
Closing due to lack of further discussion.
