### ISSUE TITLE
lua table iterate terminated early

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [LuaJIT/LuaJIT#827]
openresty user reports a bug about the lua table iteration.
the reported issue is at https://github.com/openresty/openresty/issues/817.

The bug should be a regression. This latest merger is the most suspicious
the merge PR:  https://github.com/openresty/luajit2/pull/151/commits.

Since this bug can only reproduce in the production environment, the user reported can not try a binary search to find which commit introduced the issue exactly.
@MikePall  @XmiliaH  do you have any idea how to make the bug reproduce more easily?

**Comment by vfprintf** [comment]
Here's a reduced test case. It works with JIT off but the assertion (eventually) fails with JIT on.
```lua
local t = {1,2,3,4,5}
local tab = {a=t,b=t,c=t,d=t,e=t}

local function f(...)
	for j=1,100 do end
end

for i=1, 100000 do
	f() -- force return to interpreter
	local c = 0
	for k,v in pairs(tab) do   -- this will eventually be blacklisted and patched to ITERC/JMP
		for _ in pairs(v) do end
		c = c+1
	end
	assert(c == 5)  -- eventually c=1
end
```

Output with `-jv`:
```
[TRACE   1 test1.lua:5 loop]
[TRACE   2 test1.lua:12 loop]
[TRACE   3 (2/1) test1.lua:12 -> 1]
[TRACE   4 (2/3) test1.lua:12 -> 2]
[TRACE   5 (1/3) test1.lua:6 return]
[TRACE   6 (4/3) test1.lua:11 -> 1]
[TRACE --- test1.lua:11 -- inner loop in root trace at test1.lua:12]
... repeats a few times...
[TRACE --- test1.lua:11 -- inner loop in root trace at test1.lua:12]
/tmp/LuaJIT/src/luajit: test1.lua:15: assertion failed!
```

It tries to compile the `pairs(tab)` loop a few times, until it eventually blacklists the ITERN and patches the bytecode to ITERC+JMP. On the next iteration, after trace 5 returns to the interpreter, it will begin iterating with ITERC and then jump to trace 2. Then trace 2 will exit to trace 3. But this time ITERC called `next` and stored the loop control variable (current table key) as a `TValue *` pointer, while ITERN stores a numeric index. When trace 3 was compiled the bytecode was ITERN so now the `lj_vm_next` call in trace 3 gets a pointer instead and just skips the rest of the table.

This can also happen without blacklisting:
```lua
local tab = {}
for i=1, 100 do
	tab[i] = i
end

local function f(pairs)
	local c = 0
	for _ in pairs(tab) do
		for j=1, 100 do end
		c = c+1
	end
end

f(pairs)
f(ipairs)
```
This code works with JIT off but with JIT on it fails with `bad argument #2 to '(for generator)' (number expected, got userdata)` because on the second call the interpreter patches the bytecode but the compiled code still calls `lj_vm_next`.

**Comment by MikePall** [comment]
Fixed. Thanks!

**Comment by zhuizhuhaomeng** [comment]
thanks
