### ISSUE TITLE
Makefile MacOSX M1 Monterey ld: unknown option: -soname

### ISSUE THREAD

**Issue by QuattroCS-Myriad** [LuaJIT/LuaJIT#832]
Hello,

I'm having this issue, I was not able to find a solution yet after searching

UILDVM   jit/vmdef.lua
DYNLINK   libluajit.so
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libluajit.so] Error 1
make: *** [default] Error 2

any help appreciated
Thank you

**Comment by MikePall** [comment]
This shouldn't happen, because the `-soname` option is not used at all for macOS builds. The Makefile assumes `uname -s` returns `Darwin` on macOS. If that's not the case in your build environment, then I'd like to know what it returns. Maybe try with a standard account without any environment variables set except for `MACOSX_DEPLOYMENT_TARGET`.

**Comment by QuattroCS-Myriad** [comment]
```
 ~  uname -s
Darwin
```

I realized what my issue was, I commented out more than mentioned 

https://github.com/LuaJIT/LuaJIT/issues/653

Made a new copy started fresh, it completed `make`.

Thank you for the assistance.
