### ISSUE TITLE
DynASM ARM64: Data storage operations are only defined for x86/x64

### ISSUE THREAD

**Issue by indianakernick** [LuaJIT/LuaJIT#892]
My issue is around DynASM. Being able to mix C with assembly like this is really cool. However, I seem to have found a limitation with ARM 64. It seems that the data storage operations are not defined. To be specific, I'm talking about [this](https://github.com/LuaJIT/LuaJIT/blob/03080b795aa3496ed62d4a0697c9f4767e7ca7e5/dynasm/dasm_x86.lua#L2164-L2195). I would have thought that this would be architecture independent. Although I guess an endianness difference between the host and the target might come into play...

I want to be able to embed constants but that doesn't seem to be possible on the architecture I'm interested in. As a workaround, I've been allocating the data block separately and passing in a pointer. That works but it's not as efficient as it could be. I'd rather have the data embedded and call the generated function with no arguments. Another workaround that would achieve the expected result would be to fill up a region with dummy instructions and then `memcpy` on top of them later. That's certainly not ideal.

**Comment by MikePall** [comment]
On ARM64 the operators are called `.long` (4 bytes), `.quad` and `.addr` (8 bytes). This is to mirror the conventional assembler names. There is no byte-addressability, since DynASM is primarily concerned with code generation and code segments have 4-byte elements on ARM64.
Anyway, it's not a good idea to put constants into the code segment anymore. Modern CPUs have segregated caches and there are issues with segment permissions and aliasing.
Put read-only data into a separate memory mapping. If it's conveniently co-located, you can use PC-relative addressing. But in most cases it's easier to reference it from an argument or a fixed register.

**Comment by indianakernick** [comment]
Ah! I didn't spot that when I was going through the source. Also thanks for the tips. I might do some further research on this.
