### ISSUE TITLE
Why not constify all constant upvalues?

### ISSUE THREAD

**Issue by TurkeyMcMac** [LuaJIT/LuaJIT#895]
I was looking at `rec_upvalue_constify` in `lj_record.c`, and I was wondering why some upvalues such as tables are not constified. I changed the code to let them be constified and things continued to work at first glance.

**Comment by MikePall** [comment]
The comment in the function pretty much says it all:
> /* Don't constify objects that may retain large amounts of memory. */

Constant objects are attached to the trace and cannot be collected as long as the trace lives. Neither can objects referenced from these objects.

**Comment by TurkeyMcMac** [comment]
@MikePall Another question: Is it the case that traces can live longer than the functions they pass through, but will not run after the functions have died?

**Comment by TurkeyMcMac** [comment]
Actually, I've been looking at `rec_call_specialize` and it seems that traces keep all monomorphic Lua functions around as constants anyway. Doesn't this mean that traces may as well keep all monomorphic immutable upvalues as constants?

**Comment by MikePall** [comment]
Traces are referenced by (the bytecode of) prototypes. Closures are only referenced from traces, if the trace is specialized to them, i.e. if a closure is called on-trace. A trace that starts inside a closure does not necessarily reference it.

Also, what's the point of constifying a table? Its contents are not necessarily constant. Constifying only saves one `UREFO` or `UREFC`. This is quite cheap and the memory access can often be fused, too.

The main gain from constifying is for number or string upvalues, because they can be inlined and constant-folded.

**Comment by TurkeyMcMac** [comment]
You're probably right.
