### ISSUE TITLE
Increase limit for tables [table overflow]

### ISSUE THREAD

**Issue by Rugau** [LuaJIT/LuaJIT#907]
I Have a huge lua file (53 mb), with tables.

Its possible to increase limit for tables? 

I having this error: table overflow

i tryed to change LJ_MAX_HBITS, and BCMAX_D, but not works.

**Comment by Rugau** [comment]
...and if I use the default lua 5.1 version, it works perfectly.

**Comment by MikePall** [comment]
Since Lua files need to be parsed and turned into bytecode, this hits a limit in the bytecode encoding format.
Due to the high overhead for reading (and writing), Lua code files are not well suited for storing large amounts of structured data. A better solution would be to use a serialization format or even a database.
