### ISSUE TITLE
Whether luajit will support lua 5.4

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [LuaJIT/LuaJIT#929]
Hello. Whether luajit will support lua5.4. Some people want to use newer lua,than 5.1,but they can't do this,because luajit not support new versions of lua. Whether you will add support for lua 5.4?

**Comment by MikePall** [comment]
The [documentation on extensions](https://luajit.org/extensions.html) explicitly states that LuaJIT is API + ABI-compatible with Lua 5.1. It adds a handful of upwards-compatible extensions from higher versions plus its own extensions.

Historically, Lua has broken the API, the ABI and existing Lua scripts on *every* minor 5.x release. And for no good reason. The language has not been evolved in forward-looking ways after Lua 5.1, the real issues of the language have not been tackled, the language has been severely fragmented due to the introduction of irrelevant or not-well-thought-out features and needless incompatibilities.

Apart from the extra performance that LuaJIT has to offer, developers prefer its stability guarantees and the prudent introduction of upwards-compatible extensions.

If you were to compare the actual user base of Lua 5.4 vs. the user base of LuaJIT, you'd quickly find out who successfully painted itself into a shrinking corner.

[Hints for LuaJIT: 92 million web sites (12/2022), huge SaaS installations, 50% global market share in network switches (2020), set-top boxes, embedded devices, FinTech, HPC, games, ...]

**Comment by tigercoding56** [comment]
i need support to run  a minetest mod that uses goto statements

**Comment by sonoro1234** [comment]
https://luajit.org/extensions.html

**Comment by cos4ni2s** [comment]
I love that the Lua maintainers don't preserve past mistakes because people rely on them (backward compatibility), the opposite of other languages who are growing like a cancer.
