### ISSUE TITLE
Wrong error message "calling 'f' on bad self" when using tail call

### ISSUE THREAD

**Issue by appgurueu** [LuaJIT/LuaJIT#979]
https://github.com/LuaJIT/LuaJIT/commit/505e2c03de35e2718eef0d2d3660712e06dadf1f

`test.lua`:
```lua
local t = {}
function t:f()
	return pairs(nil)
end
t:f()
```

LuaJIT throws:

```
luajit: test.lua:5: calling 'f' on bad self (table expected, got nil)
stack traceback:
	[C]: in function 'f'
	test.lua:5: in main chunk
	[C]: at 0x564e5a233310
```

This is wrong since the table `t` is not `nil` *and* the `nil` passed to `pairs` is not the `self`. I suspect this is an issue with LuaJIT not properly keeping status information after a tail call.

PUC Lua 5.1 (and 5.2) on the other hand correctly throw:

```
lua5.1: luajitfck.lua:3: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	test.lua:3: in function 'f'
	test.lua:5: in main chunk
	[C]: ?
```

**Comment by MikePall** [comment]
No, this is because Lua doesn't really do proper tail calls to C functions, whereas LuaJIT does. OTOH LuaJIT [doesn't count tail calls](https://luajit.org/status.html). These are implementation details.
Anyway, debug information is inferred from the bytecode, not the source code. There are many other examples with slightly misleading error message, since this is not fully information preserving. And these happen in *both* Lua and LuaJIT.
