### ISSUE TITLE
[Syntax Extension] ...[x]

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#98]
`...[x]` should emit an opcode which return the x-th (which can be a variable) vararg, similarly to `(select(x, ...))` (parentheses relevant). This, unlike `#...`, errors in plain old Lua, so adding it would do no harm. `select()` could use it internally and thus be JIT-compiled. It should return nil for out of bound indices, round non-integral floats, and error for non-numbers (ooh, so this is how NaN-tagging makes LuaJIT faster?!).

**Comment by corsix** [comment]
One has to question why it is that you want this. As a language, one of Lua's philosophies is to prefer libraries over syntax, and you are proposing the opposite: taking something which is perfectly expressible using a library, and instead giving it special syntax. If your argument is based around implementing `select` in bytecode, then note that the technique applied elsewhere in the standard library is to have one special bytecode for the entire function (`select` in this case), and do magic during standard library initialisation to make the library function be implemented as this one bytecode instruction (as opposed to the alternative, which is being implemented as a single bytecode instruction which says "run this `lua_CFunction`"). If your argument is based around making `select` JIT-able, then not even special bytecode is required: in theory, the JIT compiler is perfectly capable of spotting calls to `select` and emitting native code for them (in practice, little effort has so far been spent in making varargs and vararg handling as efficient as it could be).

**Comment by SoniEx2** [comment]
...[x] isn't very useful but if we had ...[x] then we could also have ...[x]=y which would be VERY useful. (think sorting varargs)

**Comment by corsix** [comment]
> think sorting varargs

I'm going to use the term vararg-pack for the implicit data structure created/used by `...`. With that term in place, a vararg-pack is an immutable [1] stack-allocated pass-by-value array (in contrast, a table is a mutable heap-allocated pass-by-reference array/hash). If you want to be able to sort varargs, then at the very least vararg-packs need to lose immutability. If you want to be able to sort them using a library function (as opposed to writing out the full sorting logic in every function in which vararg sorting is desired), then you also need some way of passing a vararg-pack by reference rather than by value. At this point, you basically have a table, and so you might as well use a table, rather than trying to turn vararg-packs into tables.

[1] Immutable if one ignores the debug library.

**Comment by SoniEx2** [comment]
The C API can sort varargs. Just use tail calls instead of "pass by reference varargs".

e.g.

```lua
local vargs = require'vargs' -- some C library which provides varargs sorting

local function myf_cont(...)
  for i=1,select('#', ...) do
    io.write(tostring(select(i, ...)), '\n')
  end
  return true
end
local function myf(...)
  return myf_cont(vargs.sort(...)) -- tail call, semantically equivalent to passing ... by reference, but more verbose
end
```

It'd be nice if such vargs.sort() could be written in Lua thus making it JITtable.

**Comment by corsix** [comment]
> It'd be nice if such vargs.sort() could be written in Lua thus making it JITtable.

As already outlined, writing something in Lua is neither necessary nor sufficient for making something JITable.

**Comment by SoniEx2** [comment]
And how would one go about JITting Lua/C API calls? As far as I know LuaJIT doesn't provide a C/JIT API. Doing it in pure Lua is the only way to make it *potentially* JITtable.

**Comment by corsix** [comment]
If you're writing code that is part of LuaJIT, then there are several routes to making something JITable. If you're not writing code inside of LuaJIT, there is no route to making something JITable. This may seem like a strange disclaimer to make, but it is worth pointing out, and fairly obvious once you think about it: LuaJIT would have to expose a massive and complicated API to allow you to JIT new things.

Once you're inside the LuaJIT interpreter, there are several ways to implement a library function:
  1. In pure Lua (e.g. `math.deg`, whose implementation is exactly `function(x) return x * 57.29577951308232 end`)
  2. In semi-pure Lua: this involves a variant of the LuaJIT bytecode compiler which recognises certain sequences and converts them into private bytecode (e.g. `table.getn`, whose implementation is `function(t) CHECK_tab(t) return #t end`, modulo a variant compiler which turns `CHECK_tab(t)` into a special bytecode instruction rather than being a function call).
  3. In pure C (e.g. `table.maxn`), like PUC-Rio Lua does for all library functions.
  4. In pure assembly (e.g. `type`). Note that this assembly implementation has to cover all the control flow paths of the library function in question, and has to be implemented separately for every architecture supported by LuaJIT.
  5. In assembly with a C fallback for uncommon/slow code paths (e.g. `tonumber`). Note that this gives most of the speed benefits of option 4, while retaining some of the portability benefits of option 3.

If you then want to JIT a library function, it doesn't matter what option you chose from the previous list: they are all potentially JITable. Options 1 and 2 will JIT with no additional effort, but only if the bytecodes that they use all have JIT logic. Options 3, 4, and 5 require JIT logic to be written for them in order to be JITable. In particular, note that "invent a new bytecode and write JIT logic for it" and "invent a new C library function and write JIT logic for it" both involve writing JIT logic, and the former option is only appealing if the bytecode in question can be used to implement several different library functions.
