### ISSUE TITLE
Does CVE's of Lua affects LuaJIT

### ISSUE THREAD

**Issue by jmpokar** [LuaJIT/LuaJIT#989]
I apologize if below question may seem a bit silly, but I would really appreciate it if you could provide some clarification, 

We use Envoy Proxy which bundles in Lua for LuaJIT here,
https://github.com/envoyproxy/envoy/blob/330d001b5ad85a0a82fce10946ae30df53cda478/source/extensions/filters/common/lua/BUILD#L16

and here is how LuaJIT is included in Docker Image of Envoy Proxy,
https://github.com/envoyproxy/envoy/blob/v1.26.0/bazel/repository_locations.bzl#L427 

Now when BlackDuck Binary Analysis tool scan the Envoy Image It reports some vulnerabilities,
For Lua 5.1, It reports

CVE-2021-43519
Stack overflow in lua_resume of ldo.c in Lua Interpreter 5.1.0~5.4.4 allows attackers to perform a Denial of Service via a crafted script file.

CVE-2020-15888
Lua through 5.4.0 mishandles the interaction between stack resizes and garbage collection, leading to a heap-based buffer overflow, heap-based buffer over-read, or use-after-free.

CVE-2022-33099
An issue in the component luaG_runerror of Lua v5.4.4 and below leads to a heap-buffer overflow when a recursive error occurs.

CVE-2014-5461
Buffer overflow in the vararg functions in ldo.c in Lua 5.1 through 5.2.x before 5.2.3 allows context-dependent attackers to cause a denial of service (crash) via a small number of arguments to a function with a large number of fixed arguments.

For Lua 5.2, It reports  
CVE-2020-15888
CVE-2022-33099
CVE-2021-43519

From this page of LuaJIT https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/extensions.html I understand that LuaJIT is compatible with Lua 5.1 

I am wondering does the above Lua CVE's impact LuaJIT since it uses Lua?

**Comment by MikePall** [comment]
The LuaJIT 2.x VM has been rewritten from the ground up. Almost none of the original code from Lua remains. So Lua CVEs generally do not apply. LuaJIT implements Lua (the language), not Lua (the VM from lua.org).

Even if you could repro a modification of any of them, here's the [FAQ on LuaJIT sandboxing](https://luajit.org/faq.html#sandbox), which basically says: you need a process level sandbox, otherwise **do not even think about running untrusted Lua code**.

That means none of the above CVEs would even be considered a vulnerability in the context of LuaJIT.

Also, Envoy Proxy doesn't have any sandbox whatsoever. All Lua code must be trusted. Otherwise anyone could simply run `os.execute("rm -rf /whatever")` without bothering with any CVEs.
