### ISSUE TITLE
Use "the stack" (e.g. rsp) for args and varargs?

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#99]
Could LuaJIT potentially use "the stack" for args and varargs? (I don't know much about x86 assembly so this might be a bad idea, but it doesn't seem to do so)

**Comment by corsix** [comment]
For JIT-compiled code, the question is irrelevant. For interpreted code, the answer borne out by experimentation is no: if you want to pass arguments on the C stack, then every Lua coroutine needs its own C stack. LuaJIT1 took the approach of giving every Lua coroutine its own C stack, but (unsurprisingly) this made coroutine creation rather expensive, and in LuaJIT2 the decision was made to not give every coroutine its own C stack. With that decision made, passing Lua arguments on the C stack is not an option. Note that even if it were an option, it would still be a bad idea (one argument amongst many being that the ABI for `lua_CFunction` is that arguments are passed on the Lua stack rather than the C stack, and it is very nice to have the same ABI for all kinds of functions).

**Comment by mraleph** [comment]
@SoniEx2 Issue tracker is not the best place for comments and questions like this. Issue tracker exists to track *issues*. Please consider asking these questions on the mailing list instead. 

As explained above this is infeasible.

**Comment by SoniEx2** [comment]
It would potentially make my [Forth VM](https://github.com/SoniEx2/Stuff/tree/master/lua/Forth) faster. (Not that it isn't fast enough already... But it'd be nice to squeeze a little more performance out of it, even if it's just 1%.)
